### ISSUE TITLE
Exception on reload

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#102]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.0.0-Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Run /questadmin reload with the linked quests.yml.

```
[13:04:24] [Server thread/INFO]: Wahrheit issued server command: /questadmin reload
[13:04:24] [Server thread/INFO]: [PLAYERCOMMAND} Wahrheit: [-63 88 194] => "/questadmin reload"
[13:04:24] [Server thread/INFO]: [Quests] There are new language phrases with the current version. They have been stored in /lang/en_new.yml
[13:04:24] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.0.0-Naomi-b${env.BUILD_NUMBER}
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-edd0396-2a927e8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-edd0396-2a927e8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quest.updateCompass(Quest.java:167) ~[?:?]
	at me.blackvein.quests.Quester.checkQuest(Quester.java:2384) ~[?:?]
	at me.blackvein.quests.Quests.reloadQuests(Quests.java:1928) ~[?:?]
	at me.blackvein.quests.Quests.adminReload(Quests.java:662) ~[?:?]
	at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:617) ~[?:?]
	at me.blackvein.quests.Quests.onCommand(Quests.java:606) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-edd0396-2a927e8]
	... 15 more
```

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/zyMDX5fu

**Comment by FlyingPikachu** [comment]
Incoming dev build should fix this. In the event it doesn't, post the new error and we'll go from there. Thanks!

**Comment by SXRWahrheit** [comment]
Just to be clear, does the error mean one of my quest locations is wrong?
