### ISSUE TITLE
Exception on reload

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#104]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.0.1-b174

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Run /questadmin reload with attached quests.yml

```
[10:28:03] [Server thread/INFO]: Wahrheit issued server command: /questadmin reload
[10:28:03] [Server thread/INFO]: [PLAYERCOMMAND} Wahrheit: [4374 64 543] => "/questadmin reload"
[10:28:03] [Server thread/INFO]: [Quests] There are new language phrases with the current version. They have been stored in /lang/en_new.yml
[10:28:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.0.1-b174
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-edd0396-2a927e8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-edd0396-2a927e8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quest.updateCompass(Quest.java:168) ~[?:?]
	at me.blackvein.quests.Quester.checkQuest(Quester.java:2384) ~[?:?]
	at me.blackvein.quests.Quests.reloadQuests(Quests.java:1928) ~[?:?]
	at me.blackvein.quests.Quests.adminReload(Quests.java:662) ~[?:?]
	at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:617) ~[?:?]
	at me.blackvein.quests.Quests.onCommand(Quests.java:606) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-edd0396-2a927e8]
	... 15 more
```

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/zyMDX5fu

**Comment by SXRWahrheit** [comment]
https://www.spigotmc.org/threads/quests.47772/page-53#post-2614457

This user also can't run reload, but didn't provide much information.

**Comment by FlyingPikachu** [comment]
Continued from #102, possibly related to #100 

@SXRWahrheit Would you mind reposting your example quest? The Pastebin expired.

**Comment by SXRWahrheit** [comment]
This one will last a month: https://pastebin.com/fiiHJLMP

**Comment by FlyingPikachu** [comment]
Although I can't replicate the reload error, I did notice this in the startup log:

`[13:41:53 ERROR]: [Quests] block-start: for Quest Cavernous Jaunt is not in prop
er location format!
[13:41:53 ERROR]: [Quests] Proper location format is: "WorldName x y z"`

That said this is very likely a result of the fix for #100. Hopefully amending my fix will resolve both issues.

**Comment by SXRWahrheit** [comment]
```
    block-start: prosperus 29.0 24.0 -84.0
```

I used the in-game editor to create that quest, too.

**Comment by FlyingPikachu** [comment]
It seems I spoke too soon. In my rush, I simply misspelled the world name in my test environment.

Cannot replicate. I've tried _/questadmin reload_ with and without a compass and in different worlds.

Please try this build, attempt to reproduce the error, and post back the debug messages from console:

https://www.dropbox.com/s/zgdlolaeu1be54u/Quests-3.0.1.jar?dl=0

**Comment by SXRWahrheit** [comment]
Will give it a go tonight - internet at work is unstable right now.

**Comment by SXRWahrheit** [comment]
Got to test earlier than anticipated. It looks like that fixed it! Now where can I grab a version that doesn't spam my logs with debug info? :P

**Comment by FlyingPikachu** [comment]
Next dev build will contain this fix, minus the debug messages. Thanks for the report!

Unrelated to #100
