### ISSUE TITLE
2 issues with the plugin

### ISSUE THREAD

**Issue by jeannen** [FlyingPikachu/Quests#105]
Hi ! :)
I've got a problem, when a player accept a quest using the GUI, he can take the GUI-item to his inventory, and i've  got this error in logs:

[22:08:26 ERROR]: Could not pass event InventoryClickEvent to Quests v2.4.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1588) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
at me.blackvein.quests.Quester.getBaseData(Quester.java:2083) ~[?:?]
at me.blackvein.quests.Quester.saveData(Quester.java:2031) ~[?:?]
at me.blackvein.quests.Quester.takeQuest(Quester.java:398) ~[?:?]
at me.blackvein.quests.PlayerListener.onInventoryClickEvent(PlayerListener.java:172) ~[?:?]
at sun.reflect.GeneratedMethodAccessor302.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
... 14 more

And i've also this error: 

01:28:03 ERROR]: Could not pass event PlayerQuitEvent to Quests v2.4.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.PlayerList.disconnect(PlayerList.java:322) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:832) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.NetworkManager.l(NetworkManager.java:242) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:79) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:800) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
at me.blackvein.quests.Quester.getBaseData(Quester.java:2083) ~[?:?]
at me.blackvein.quests.Quester.saveData(Quester.java:2031) ~[?:?]
at me.blackvein.quests.PlayerListener.onPlayerQuit(PlayerListener.java:914) ~[?:?]
at sun.reflect.GeneratedMethodAccessor838.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot_vgbin.jar:git-Spigot-bf0ac55-3ee97a3]
... 12 more

Here is my config:
http://pastebin.com/NFbPUfb7
And my quest.yml:
http://pastebin.com/mt0bnQAL

**Comment by Neoblade298** [comment]
I have a similar problem, and I think I've got something to add: Does this only happen if the player takes at least 2 quests from the same NPC? Cause for me, if you only take one quest, it won't have this problem, but if you take 2 or more, players can take out items.

**Comment by jeannen** [comment]
I diden't notice that, but probably, somes NPC give more than one quest

**Comment by FlyingPikachu** [comment]
Bug #57 (mentioned earlier) may have been related to this issue and has since been resolved. Please update to at least this dev build and check if it resolves the issue.

http://ci.ac3-servers.eu/job/Quests/81/

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
