### ISSUE TITLE
ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet

### ISSUE THREAD

**Issue by seema84** [FlyingPikachu/Quests#123]
Bukkit 1.8.6

[Server thread/WARN]: [Quests] Task #43 for Quests v2.4.0-b79 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
	at me.blackvein.quests.NpcEffectThread.showEffect_1_8_R1(NpcEffectThread.java:245) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:69) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:43) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-c5146ba-01930e2]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [craftbukkit.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-c5146ba-01930e2]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-c5146ba-01930e2]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[craftbukkit.jar:git-Spigot-c5146ba-01930e2]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-c5146ba-01930e2]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	... 10 more

**Comment by Volkenstein666** [comment]
29.05 10:37:18 [Server] INFO ... 10 more
29.05 10:37:18 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
29.05 10:37:18 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
29.05 10:37:18 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[custom.jar:git-Bukkit-01930e2]
29.05 10:37:18 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[custom.jar:git-Bukkit-01930e2]
29.05 10:37:18 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
29.05 10:37:18 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
29.05 10:37:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:540) [custom.jar:git-Bukkit-01930e2]
29.05 10:37:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:632) [custom.jar:git-Bukkit-01930e2]
29.05 10:37:18 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [custom.jar:git-Bukkit-01930e2]
29.05 10:37:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:683) [custom.jar:git-Bukkit-01930e2]
29.05 10:37:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [custom.jar:git-Bukkit-01930e2]
29.05 10:37:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[custom.jar:git-Bukkit-01930e2]
29.05 10:37:18 [Server] INFO at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:44) ~[?:?]
29.05 10:37:18 [Server] INFO at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:70) ~[?:?]
29.05 10:37:18 [Server] INFO at me.blackvein.quests.NpcEffectThread.showEffect_1_8_R1(NpcEffectThread.java:246) ~[?:?]
29.05 10:37:18 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
29.05 10:37:18 [Server] WARN Task #57 for Quests v2.3.4 generated an exception

me too- except its task #57- just runs over and over

**Comment by FlyingPikachu** [comment]
"Duplicate" of #117
