### ISSUE TITLE
Error with plugins

### ISSUE THREAD

**Issue by croderdai** [FlyingPikachu/Quests#134]
[19:11:19] [Server thread/WARN]: [Quests] Quester data for UUID "4b92ae5b-227b-3ba9-8417-9025feefd2e3" not stored. Attempting manual data retrieval...
[19:11:19] [Server thread/WARN]: java.lang.NullPointerException
[19:11:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester.getObjectives(Quester.java:507)
[19:11:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:356)
[19:11:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester.updateJournal(Quester.java:256)
[19:11:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester$4.put(Quester.java:181)
[19:11:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester$4.put(Quester.java:174)
[19:11:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester.hardDataPut(Quester.java:2563)
[19:11:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester.addEmpties(Quester.java:1353)
[19:11:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester.loadData(Quester.java:1968)
[19:11:19] [Server thread/WARN]: 	at me.blackvein.quests.Quests.getQuester(Quests.java:1944)
[19:11:19] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:33)
[19:11:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[19:11:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[19:11:19] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829)
[19:11:19] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[19:11:19] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
[19:11:19] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
[19:11:19] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:11:19] [Server thread/WARN]: [Quests] Task #879 for Quests v3.0.0-Naomi-b${env.BUILD_NUMBER} generated an exception
java.lang.NullPointerException
	at me.blackvein.quests.Quester.getObjectives(Quester.java:507) ~[?:?]
	at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:356) ~[?:?]
	at me.blackvein.quests.Quester.updateJournal(Quester.java:256) ~[?:?]
	at me.blackvein.quests.QuestData$10.clear(QuestData.java:420) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2083) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:1944) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [PaperSpigot-latest.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[19:11:20] [Server thread/WARN]: [Quests] Quester data for UUID "4b92ae5b-227b-3ba9-8417-9025feefd2e3" not stored. Attempting manual data retrieval...
[19:11:20] [Server thread/WARN]: java.lang.NullPointerException
[19:11:20] [Server thread/WARN]: 	at me.blackvein.quests.Quester.getObjectives(Quester.java:507)
[19:11:20] [Server thread/WARN]: 	at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:356)
[19:11:20] [Server thread/WARN]: 	at me.blackvein.quests.Quester.updateJournal(Quester.java:256)
[19:11:20] [Server thread/WARN]: 	at me.blackvein.quests.Quester$4.put(Quester.java:181)
[19:11:20] [Server thread/WARN]: 	at me.blackvein.quests.Quester$4.put(Quester.java:174)
[19:11:20] [Server thread/WARN]: 	at me.blackvein.quests.Quester.hardDataPut(Quester.java:2563)
[19:11:20] [Server thread/WARN]: 	at me.blackvein.quests.Quester.addEmpties(Quester.java:1353)
[19:11:20] [Server thread/WARN]: 	at me.blackvein.quests.Quester.loadData(Quester.java:1968)
[19:11:20] [Server thread/WARN]: 	at me.blackvein.quests.Quests.getQuester(Quests.java:1944)
[19:11:20] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:33)
[19:11:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[19:11:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[19:11:20] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829)
[19:11:20] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[19:11:20] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
[19:11:20] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
[19:11:20] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by croderdai** [comment]
[13:15:03] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Quests v3.0.0-Naomi-b${env.BUILD_NUMBER}
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:917) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-latest.jar:git-Paper-1104]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [PaperSpigot-latest.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [PaperSpigot-latest.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(Unknown Source) ~[?:1.8.0_141]
	at java.util.LinkedList.set(Unknown Source) ~[?:1.8.0_141]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:79) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:73) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:1983) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:1944) ~[?:?]
	at me.blackvein.quests.PlayerListener.onPlayerInteract(PlayerListener.java:175) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor774.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot-latest.jar:git-Paper-1104]
	... 18 more
[13:15:03] [Server thread/INFO]: [Quests] Disabling Quests v3.0.0-Naomi-b${env.BUILD_NUMBER}

**Comment by FlyingPikachu** [comment]
Closing as OP did not follow issue template. If this is still a problem, try the latest dev build, then open a new ticket with an updated error if the problem persists.
