### ISSUE TITLE
UUID-Related Errors Filling Logs

### ISSUE THREAD

**Issue by NathanWolf** [FlyingPikachu/Quests#14]
This error seems to occur a *lot*, though I'm not sure of the cause:

```
[12:34:00 WARN]: java.lang.IllegalArgumentException: Invalid UUID string: somePrefix*
[12:34:00 WARN]: 	at java.util.UUID.fromString(UUID.java:194)
[12:34:00 WARN]: 	at me.blackvein.quests.Quests.checkQuester(Quests.java:4766)
[12:34:00 WARN]: 	at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:864)
[12:34:00 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:34:00 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[12:34:00 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:34:00 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[12:34:00 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[12:34:00 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:34:00 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[12:34:00 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:255)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInPosition.a(SourceFile:57)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[12:34:00 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[12:34:00 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:685)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[12:34:00 WARN]: 	at java.lang.Thread.run(Thread.java:744)
[12:34:00 WARN]: java.lang.IllegalArgumentException: Invalid UUID string: *someSuffix
[12:34:00 WARN]: 	at java.util.UUID.fromString(UUID.java:194)
[12:34:00 WARN]: 	at me.blackvein.quests.Quests.checkQuester(Quests.java:4766)
[12:34:00 WARN]: 	at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:864)
[12:34:00 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:34:00 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[12:34:00 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:34:00 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[12:34:00 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[12:34:00 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:34:00 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[12:34:00 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:255)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInPosition.a(SourceFile:57)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[12:34:00 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[12:34:00 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:685)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[12:34:00 WARN]: 	at java.lang.Thread.run(Thread.java:744)
[12:34:00 WARN]: java.lang.IllegalArgumentException: Invalid UUID string: *someRegex*
[12:34:00 WARN]: 	at java.util.UUID.fromString(UUID.java:194)
[12:34:00 WARN]: 	at me.blackvein.quests.Quests.checkQuester(Quests.java:4766)
[12:34:00 WARN]: 	at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:864)
[12:34:00 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:34:00 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[12:34:00 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:34:00 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[12:34:00 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[12:34:00 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:34:00 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[12:34:00 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:255)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInPosition.a(SourceFile:57)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[12:34:00 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[12:34:00 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:685)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[12:34:00 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[12:34:00 WARN]: 	at java.lang.Thread.run(Thread.java:744)
```

**Comment by NathanWolf** [comment]
I'm not sure, but this may be a duplicate of issue#4?

**Comment by FlyingPikachu** [comment]
Remove the old 'quester-blacklist' nodes in config.yml or regen the config.

**Comment by NathanWolf** [comment]
Thank you!
