### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by hsndmrts** [FlyingPikachu/Quests#140]
skillapi-quests moduls is bug, i dont make "Class Experience Reward" bug:

[22:30:47] [Server thread/ERROR]: Error handling conversation prompt
java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.LinkedList
	at me.blackvein.quests.QuestFactory.saveQuest(QuestFactory.java:1277) ~[?:?]
	at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1040) ~[?:?]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1033) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnection$5.evaluate(PlayerConnection.java:988) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:726) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]

**Comment by FlyingPikachu** [comment]
The authors of the module need to update it so that it uses newer Quests code. This is not something I can fix - speak to the author of the module.

**Comment by hsndmrts** [comment]
oket thanks

2015-06-11 17:25 GMT+03:00 FlyingPikachu <notifications@github.com>:
