### ISSUE TITLE
Boot Error on Spigot 1.8.3

### ISSUE THREAD

**Issue by hornemans** [FlyingPikachu/Quests#142]
[23:50:42] [Server thread/INFO]: [Quests] Enabling Quests v2.5.1-b89
[23:50:42] [Server thread/ERROR]: Error occurred while enabling Quests v2.5.1-b89 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensPlugin
	at me.blackvein.quests.Quests.linkOtherPlugins(Quests.java:398) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:182) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-183.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-183.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-183.jar:git-Spigot-870264a-0a645a2]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
	... 13 more
Using Citizens Version 2.0.16.b1244

**Comment by hornemans** [comment]
why? and How do i fix it?

**Comment by hornemans** [comment]
Noticed you had newer versions so i tried that too! BUT it did not work either :(

**Comment by hornemans** [comment]
[23:50:42] [Server thread/INFO]: [Quests] Enabling Quests v2.5.1-b89
[23:50:42] [Server thread/ERROR]: Error occurred while enabling Quests v2.5.1-b89 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensPlugin
	at me.blackvein.quests.Quests.linkOtherPlugins(Quests.java:398) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:182) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-183.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-183.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-183.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-183.jar:git-Spigot-870264a-0a645a2]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
	... 13 more

**Comment by Deathinflames** [comment]
Looks like you might be running an older version of Citizens, try updating it.

**Comment by Neoblade298** [comment]
This is a problem with Citizens, the latest build of Quests has not been updated to be with the latest build of citizens. I suggest you downgrade to build 1230

**Comment by hornemans** [comment]
@Deathinflames 
Thanks for trying to help, but if you would have read more carefully you would realize that IS the NEWEST version!

@Neoblade298 
Thanks!  That worked just fine.  I used the 1230 build of citizens and it loaded just fine.  Hopefully it will get update to work with the newer citizens version soon :)

**Comment by DNx5** [comment]
latest build of Citizens2 is work fine for me. That class is exist. maybe you've downloaded wrong file.
http://ci.citizensnpcs.co/job/Citizens2/lastBuild/

**Comment by FlyingPikachu** [comment]
Thanks @Neoblade298 !
