### ISSUE TITLE
Error occurred while enabling Quests v2.5.1-b82

### ISSUE THREAD

**Issue by AsylumDreams** [FlyingPikachu/Quests#147]
Running Spigot 1.8.7-R0.1-SNAPSHOT

 As it seems to be related I also had this Citizens error, which I'm chasing up too:

I'm aware that this is likely the same issue as those before me, but as some of the integers are different I'm posting it up nonetheless.

-
[Server thread/ERROR]: [Citizens] v2.0.16-SNAPSHOT (build 1239) is not compatible with Minecraft v1.8.7 - try upgrading or downgrading Citizens. Disabling.
-

[Server thread/ERROR]: Error occurred while enabling Quests v2.5.1-b82 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensPlugin
	at me.blackvein.quests.Quests.linkOtherPlugins(Quests.java:398) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:182) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensPlugin
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
	... 13 more

**Comment by FlyingPikachu** [comment]
Closing because this is not the issue tracker for Citizens.
