### ISSUE TITLE
Error plugins with quest

### ISSUE THREAD

**Issue by croderdai** [FlyingPikachu/Quests#148]
[11:52:46] [Server thread/WARN]: [Quests] Task #3238933 for Quests v3.0.0-Naomi-b${env.BUILD_NUMBER} generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(Unknown Source) ~[?:1.8.0_141]
	at java.util.LinkedList.set(Unknown Source) ~[?:1.8.0_141]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:79) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:73) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:1983) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:1944) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[11:52:46] [Server thread/WARN]: [Quests] Quester data for UUID "9383c1a9-f310-39b2-8ac4-1d748266a9a6" not stored. Attempting manual data retrieval...
[11:52:46] [Server thread/INFO]: [Quests] Quester not found for UUID "9383c1a9-f310-39b2-8ac4-1d748266a9a6". Consider adding them to the Quester blacklist.
[

**Comment by Formula350** [comment]
This happens for me as well, though I don't receive an error like you do. 
I don't know about you, but in my case it's caused by NPCs (Citizens) that load and before Citizens can say "This isn't really a player...", Quests catches it, tries to find a Quest Data file, and can't; thus, the error.

I suspect that if you placed a default new-player YML file into the data folder that has that UUID, it'd "solve" the issue. I don't know if a completely blank file would cause problems, which is why I suggested copying one from a new-player, so that it has the proper formatting. 

This ***should*** be all you need in the file. Hopefully it will fill in the `lastKnownName:` line on its own _(which I removed from the below code)_, as the one I took this from had the player's name...

Filename: `9383c1a9-f310-39b2-8ac4-1d748266a9a6.yml`
````YAML
currentQuests: none
currentStages: none
quest-points: 0
completed-Quests: none
hasJournal: false
````
