### ISSUE TITLE
Quest Problem, load Plugin Problem

### ISSUE THREAD

**Issue by haruh09** [FlyingPikachu/Quests#155]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.0.0-Naomi

(__Required__) Please describe the problem and how to replicate it. Any console errors?
If Two players with the NPC interoperating cannot continue one.

And..

If the Plugin reloaded becomes, mistakes originate in some Quests

**Comment by haruh09** [comment]
[18:21:56 ERROR]: Could not pass event NPCRightClickEvent to Quests v3.0.0-Naomi-b${env.BUILD_NUMBER}
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:415) [citizens-2.0.22-SNAPSHOT.jar:?]
        at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1575) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.Quester.interactWithNPC(Quester.java:900) ~[?:?]
        at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:93) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor350.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
        ... 23 more
