### ISSUE TITLE
Error on /questsadmin reload

### ISSUE THREAD

**Issue by ChimeraMusic** [FlyingPikachu/Quests#156]
Hi,

I just made my second quest, where this happened. I have no idea what this is. I'm on spigot 1.8.7 with the version before 2.5.1 because the download link is down. So until then i'm stuck with this error:

[23:32:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questsadmin' in plugin Quests v2.0.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [?:1.6.0_65]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [?:1.6.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:138) [?:1.6.0_65]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.managers.RegionManager.getRegionExact(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/regions/ProtectedRegion;
	at me.blackvein.quests.Quests.regionFound(Quests.java:3147) ~[?:?]
	at me.blackvein.quests.Quests.loadQuests(Quests.java:2578) ~[?:?]
	at me.blackvein.quests.Quests.reloadQuests(Quests.java:2439) ~[?:?]
	at me.blackvein.quests.Quests.adminReload(Quests.java:845) ~[?:?]
	at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:784) ~[?:?]
	at me.blackvein.quests.Quests.onCommand(Quests.java:765) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	... 16 more

**Comment by FlyingPikachu** [comment]
According to your error, you're using Quests v2.0.0 - please update. Thanks!
