### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by haruh09** [FlyingPikachu/Quests#159]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
1.12.2 - Quests v3.0.0-Naomi
(__Required__) Please describe the problem and how to replicate it. Any console errors?
`
[12:21:04] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v3.0.0-Naomi-b${env.BUILD_NUMBER}
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
[12:22:06] [Spigot Watchdog Thread/ERROR]: The server has stopped responding!
[12:22:06] [Spigot Watchdog Thread/ERROR]: Please report this to http://www.spigotmc.org/
[12:22:06] [Spigot Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[12:22:06] [Spigot Watchdog Thread/ERROR]: Spigot version: git-Spigot-93e20b3-b8f84f3 (MC: 1.12.2)
`

**Comment by FlyingPikachu** [comment]
Related to #139
Fixed in 2f08800e8c2af936d00b80249e7194752d3c33d0
