### ISSUE TITLE
Mystery Error, spammed then ceased.

### ISSUE THREAD

**Issue by Formula350** [FlyingPikachu/Quests#16]
I don't even have a clue what could be causing this. I was getting all the quests sorted on the test server, and when I went live on the main, with user-data, after one of them joined there was this. It eventually stopped after I'm not sure how many times of spamming the same thing (I think) over and over. 

Is it the plugin, player file related, or quest related? I was converting the quests on build#22, this occured on build#24.
http://pastebin.com/x3TZLwHY

Thanks.

**Comment by Formula350** [comment]
As a followup, after having gotten sleep and looking at that Pastebin again... PlayerMoveEvent and PlayerJoinEvent are in there, and I also have a PlayerQuitEvent as well:
```java
[04:22:38] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to Quests v2.1.6
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerList.disconnect(PlayerList.java:299) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:801) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.disconnect(PlayerConnection.java:173) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerList.attemptLogin(PlayerList.java:357) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:69) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:150) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(SourceFile:151) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:718) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quester.getBaseData(Quester.java:2086) ~[?:?]
	at me.blackvein.quests.Quester.saveData(Quester.java:2034) ~[?:?]
	at me.blackvein.quests.PlayerListener.onPlayerQuit(PlayerListener.java:844) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor816.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	... 17 more
```

**Comment by Formula350** [comment]
**I am leaving the below, in case it helps to track down the code problem, but I have found the cause, and will open a new issue simply because this one is rather "messy" and could be complicated to understand**

Some updates... I uploaded the latest Quests, 2.2.0 (build 27). First oddity is that after the server is done loading, Quests is the last plugin to do anything by displaying it's info. No real errors to speak of; HOWEVER, there is a definite oddity....

A bit of backstory, since I think it's rather relevant, is before we went to 1.8 we had just started a "limited time" series of quests where each quest only lasts a week. When we went to 1.8 there was issues with quests as I went to v2.0.0 and we put that on hold. We left the quest in place and removed the NPC associated with it, so people couldn't take it until things were sorted and we'd reinstate the NPC. Well, some folks still had the quest accepted, and even though we have since deleted that quest before remaking it (with a different name), it appears that it may still be causing issues behind the scenes? Enter the "oddity", as this is what shows up at start:
``` java
 17.02 12:55:29 [Server] ERROR npc-giver-id: for Quest Challenge of the Gods W2 is not a valid NPC id!
```
Yet, as I mentioned, there is no quest with that name in the YML anymore, it is now:
``` yaml
  custom34:
    name: Champion of Gods Week 2
```
So I have just been deleting any player's data files that appear to be causing problems.

Observations: Errors occur on only SOME player quits, which I assume may have some link to lingering old quest names in their file. Looks a bit different from the other... 
``` javascript
[12:57:11] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to Quests v2.2.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerList.disconnect(PlayerList.java:299) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:801) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.NetworkManager.l(NetworkManager.java:229) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(SourceFile:148) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:718) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quester.getBaseData(Quester.java:2086) ~[?:?]
	at me.blackvein.quests.Quester.saveData(Quester.java:2034) ~[?:?]
	at me.blackvein.quests.PlayerListener.onPlayerQuit(PlayerListener.java:875) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	... 13 more
```

**Comment by FlyingPikachu** [comment]
Should note that the first error in your second post ("ERROR npc-giver-id...") is saying that the NPC id is invalid; not the quest name.
