### ISSUE TITLE
OutOfMemoryError, not incrementing index in location builder.

### ISSUE THREAD

**Issue by NachtRaben** [FlyingPikachu/Quests#173]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Build 193 - Latest

(__Required__) Please describe the problem and how to replicate it. Any console errors?
OOME when loading the quests files due to non-incremented index at.
https://github.com/FlyingPikachu/Quests/blob/master/src/main/java/me/blackvein/quests/Quests.java#L3399

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://gist.github.com/NachtRaben/ebf4b1cab5431701376185a3f72dec19

`java.lang.OutOfMemoryError: null
        at java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:161) ~[?:1.8.0_151]
        at java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:155) ~[?:1.8.0_151]
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125) ~[?:1.8.0_151]
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448) ~[?:1.8.0_151]
        at java.lang.StringBuilder.append(StringBuilder.java:136) ~[?:1.8.0_151]
        at me.blackvein.quests.Quests.getLocation(Quests.java:3397) ~[?:?]
        at me.blackvein.quests.Event.loadEvent(Event.java:556) ~[?:?]
        at me.blackvein.quests.Quests.processStages(Quests.java:3084) ~[?:?]
        at me.blackvein.quests.Quests.loadQuests(Quests.java:2061) ~[?:?]
        at me.blackvein.quests.Quests$1.run(Quests.java:197) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1270]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1270]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1270]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1270]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1270]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1270]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
`

**Comment by FlyingPikachu** [comment]
Thanks, 1cd293c33abc67cf690aac64464857b8d5524f02 should fix this.

Please try the build at the link below and let us know if it worked.
http://ci.ac3-servers.eu/job/Quests/194/

**Comment by Sprax2013** [comment]
> Thanks, 1cd293c should fix this.

It does on my server :) Thanks

**Comment by Coolguy3289** [comment]
I work on the same server @NachtRaben does. I have just implemented the plugin and I am no longer receiving the error.
