### ISSUE TITLE
Unable to set deliver items stage 2

### ISSUE THREAD

**Issue by Koz4Christ** [FlyingPikachu/Quests#174]
Running git-Spigot-f928e7a-e91aed8 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT) and quests 2.5.1, Vault 1.5.3, Citizens 2.0.16, Pex 1.23.3.

Basically when I add a second stage to a quest that requires me to deliver items back to the NPC I get this error when I select "Deliver items"

[09:13:28] [Server thread/ERROR]: Error handling conversation prompt
java.lang.NullPointerException
	at me.blackvein.quests.util.ItemUtil.getDisplayString(ItemUtil.java:168) ~[?:?]
	at me.blackvein.quests.prompts.CreateStagePrompt$DeliveryListPrompt.getPromptText(CreateStagePrompt.java:2058) ~[?:?]
	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1034) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:984) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:732) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

After getting this I did the following steps:
-Deleted the quests plugin folder and restarted
-Completely recreated the server
-Restarted my client
-Tried doing the deliver items at first stage (This actually worked)

Really bummed that it was working while I was testing and then broke while I was recording the tutorial.  Thoughts?

**Comment by Koz4Christ** [comment]
Continued testing with a Dev version (Quests-2.5.1-b89.jar) and I found out that this problem is raised when I attempt to set a GUI item display for accepting the quest.  If I set that, even with no lore or anything, I get this error.
