### ISSUE TITLE
Cannot spawn more than one mob at a time

### ISSUE THREAD

**Issue by gtwy** [FlyingPikachu/Quests#184]
Here's my Event:

  LegacyMobs:
    mob-spawns:
      '0':
        spawn-location: useast2015 1725.0 59.0 1404.0
        mob-type: ZOMBIE
        spawn-amounts: 5

This event is not inside a block. It's a totally open area. When a player triggers the event, the following error is thrown in console. What's confusing is that it still spawns 1 mob.

[01:30:56 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.5.1-b82
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:269) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_85]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_85]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_8_R1/entity/CraftLivingEntity
        at me.blackvein.quests.util.QuestMob.spawn(QuestMob.java:111) ~[?:?]
        at me.blackvein.quests.Event.fire(Event.java:252) ~[?:?]
        at me.blackvein.quests.Quest.setStage(Quest.java:151) ~[?:?]
        at me.blackvein.quests.Quest.nextStage(Quest.java:110) ~[?:?]
        at me.blackvein.quests.Quester.finishObjective(Quester.java:1358) ~[?:?]
        at me.blackvein.quests.Quester.reachLocation(Quester.java:1224) ~[?:?]
        at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:975) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_85]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_85]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.7.jar:git-Spigot-6d16e64-87b9f46]
        ... 15 more

This lead me to believe that they were getting stuck in each other. So I tried to change the quantity to 1 and spawn multiple mobs (each in a different location.) When I tried to do this, the in game event editor would crash and I'd get a console error. So, I manually edited my config file to look like this

  LegacyMobs:
    mob-spawns:
      '0':
        spawn-location: useast2015 1725.0 59.0 1404.0
        mob-type: ZOMBIE
        spawn-amounts: 1
      '1':
        spawn-location: useast2015 1727.0 59.0 1400.0
        mob-type: ZOMBIE
        spawn-amounts: 1

But it still crashes.

**Comment by bartonsweb** [comment]
+1 have the same issue, any chance of a fix? Love this plugin but there are a lot of bugs that stop me using it to create large quest chains
