### ISSUE TITLE
hello i need you help

### ISSUE THREAD

**Issue by abc605521864** [FlyingPikachu/Quests#185]
[quests.zip](https://github.com/FlyingPikachu/Quests/files/1579173/quests.zip)

[20:21:19 ERROR]: Could not pass event InventoryClickEvent to Quests v3.1.6-b203
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_152]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.Quest.testRequirements(Quest.java:185) ~[?:?]
        at me.blackvein.quests.Quester.takeQuest(Quester.java:298) ~[?:?]
        at me.blackvein.quests.PlayerListener.onInventoryClickEvent(PlayerListener.java:137) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
        ... 15 more

**Comment by FlyingPikachu** [comment]
Hello, I see you did not follow the issue template. Please describe the problem and how to replicate it.

**Comment by abc605521864** [comment]
hello~
(Required) What is your Quests version / build number (do not say "latest")?
Quests-3.1.6

(Required) Please describe the problem and how to replicate it. Any console errors?
The task is created and saved will prompt an error
Using / Questsadmin reload loading task will prompt an error

[20:21:19 ERROR]: Could not pass event InventoryClickEvent to Quests v3.1.6-b203
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_152]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
at me.blackvein.quests.Quest.testRequirements(Quest.java:185) ~[?:?]
at me.blackvein.quests.Quester.takeQuest(Quester.java:298) ~[?:?]
at me.blackvein.quests.PlayerListener.onInventoryClickEvent(PlayerListener.java:137) ~[?:?]
at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
... 15 more

**Comment by FlyingPikachu** [comment]
One of your quest requirements involves money. Although you have Vault installed, you do not have an economy plugin (or, at least not one that Vault could recognize). This latest dev build will eliminate this error, but I recommend installing an economy plugin if you want that money requirement to work.
