### ISSUE TITLE
Bugs 1.8.8

### ISSUE THREAD

**Issue by mixaxdd** [FlyingPikachu/Quests#188]
When player join in to server 1.8.8 :

[Server thread/WARN]: [Quests] Task #17 for Quests v2.5.1-b89 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
	at me.blackvein.quests.NpcEffectThread.showEffect_1_8_R1(NpcEffectThread.java:373) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:76) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	... 10 more

But quests work!

**Comment by whoshenry** [comment]
Same error I'm getting on 1.8.8.

**Comment by vanjavk** [comment]
Same error ^^
