### ISSUE TITLE
Issue with enchantments

### ISSUE THREAD

**Issue by AlexTeal03** [FlyingPikachu/Quests#207]
(__Required__) What is your Quests version / build number (do _not_ say "latest")? 3.1.6

(__Required__) Please describe the problem and how to replicate it. Any console errors?
[13:52:02 WARN]: null was not found in Lang.yml, please ask the developer to update the file or simply add an entry for the enchantment
[13:52:02 ERROR]: Error handling conversation prompt
java.lang.NullPointerException
        at me.blackvein.quests.Quester.enchantmentString(Quester.java:1570) ~[?:?]
        at me.blackvein.quests.Quester.prettyEnchantmentString(Quester.java:1562) ~[?:?]
        at me.blackvein.quests.prompts.CreateStagePrompt$EnchantTypesPrompt.acceptInput(CreateStagePrompt.java:1813) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:1011) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:729) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
I was unable to recreate this specific error, however I noticed a similar bug with the Sweeping Edge enchantment while investigating this. Hopefully the fix I've just pushed might resolve your issue as well. 

Please give http://ci.ac3-servers.eu/job/Quests/216/ a try. If the issue persists, please let me know what steps you're taking to experience the error.
