### ISSUE TITLE
[20:27:22] [Server thread/WARN]: java.lang.NoSuchFieldException: a

### ISSUE THREAD

**Issue by dopplerradar** [FlyingPikachu/Quests#211]
[20:27:22] [Server thread/WARN]: java.lang.NoSuchFieldException: a
[20:27:22] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[20:27:22] [Server thread/WARN]: 	at me.blackvein.quests.util.ReflectionUtil.setValue(ReflectionUtil.java:8)
[20:27:22] [Server thread/WARN]: 	at me.blackvein.particles.Eff_1_7_R4.sendToPlayer(Eff_1_7_R4.java:56)
[20:27:22] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.showEffect_R4(NpcEffectThread.java:495)
[20:27:22] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:67)
[20:27:22] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45)
[20:27:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[20:27:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[20:27:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:873)
[20:27:22] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[20:27:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[20:27:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[20:27:22] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by SykoUSS** [comment]
I am also getting this error on a 1.7.10 KCauldron-1.7.10-2.1403.1.54 build server, setting Npc effect to false stops it of course but the effect is very much needed.

**Comment by AdminZero** [comment]
I too seem to be getting similar errors when players quit the server or timeout:  

Example #1: http://pastebin.com/PCR2ee5k
Example #2: http://pastebin.com/rSATqtjw
Example #3: http://pastebin.com/uK5fLrLs

Is there and easy fix for this or something that perhaps configured wrong?

Hope this helps. Thanks,
AdminZero

**Comment by FlyingPikachu** [comment]
OP needs to post Quests version (don't say "latest" - take a screenshot or c/p from the console).

**Comment by xxmarijnw** [comment]
Is there any plugin that changes particles? (ParticleMenu, UltimateParticles, PlayerParticles etc...). A list of plugins would be appreciated.

**Comment by AdminZero** [comment]
Hi, You can see the FULL list of my plugins from this timings report:
http://timings.aikar.co/?url=14370824

**Comment by Smackzter** [comment]
Experiencing the same problem on version 2.5.5-b95

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP. For those mentioning Cauldron, that server software is not officially supported by Quests.
