### ISSUE TITLE
Delay is not working

### ISSUE THREAD

**Issue by BryceTheCoder** [FlyingPikachu/Quests#220]
Hello there! This is a very simple issue, I am using the latest version of Quests on spigot.

The delay stage is setup properly and is not working after the specific time :/

Please let me know when you can fix this! Thanks.

**Comment by BryceTheCoder** [comment]
[10:56:33 WARN]: [Quests] Task #96 for Quests v2.5.2-b90 generated an exception
java.lang.NullPointerException
        at me.blackvein.quests.StageTimer.run(StageTimer.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java
:71) ~[spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
22) [spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
53) [spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:556) [spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

**Comment by BryceTheCoder** [comment]
Line 75 in StageTimer.java is getting a null.
quester.getQuestData(quest).delayOver = true;
I'm guessing either the quester object or getQuestData(quest) is returning a null.

Can you please fix this?
Or is Quests inactive now?

**Comment by FlyingPikachu** [comment]
Strange since it also checks those objects on line 24. Please try the latest build of Quests and post the full error here if the issue persists.
