### ISSUE TITLE
Task #57 Exception

### ISSUE THREAD

**Issue by SkyliaTeam** [FlyingPikachu/Quests#221]
Console output:

[15:51:38] [Server thread/WARN]: [Quests] Task #57 for Quests v2.5.2-b90 generated an exception
java.lang.NullPointerException
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:41) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-e497721-96d09e3]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-e497721-96d09e3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by FlyingPikachu** [comment]
The version of Spigot you are running is not compatible with Quests.
