### ISSUE TITLE
errors with the plugin

### ISSUE THREAD

**Issue by uraqtlee** [FlyingPikachu/Quests#223]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.16
(__Required__) Please describe the problem and how to replicate it. Any console errors?
When my players were trying to break blocks for the quest
[16:13:58 ERROR]: Could not pass event BlockBreakEvent to Quests v3.1.6-b203
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) [craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) [craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(Player
InteractManager.java:290) [craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractM
anager.java:217) [craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.jav
a:889) [craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [
craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [
craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:
13) [craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukk
it.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:
748) [craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
406) [craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
679) [craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:577) [craftbukkit.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:351) ~[?:?
]
        at me.blackvein.quests.Quester.updateJournal(Quester.java:256) ~[?:?]
        at me.blackvein.quests.QuestData$2.set(QuestData.java:80) ~[?:?]
        at me.blackvein.quests.QuestData$2.set(QuestData.java:72) ~[?:?]
        at me.blackvein.quests.Quester.breakBlock(Quester.java:708) ~[?:?]
        at me.blackvein.quests.PlayerListener.onBlockBreak(PlayerListener.java:3
45) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[craftbukkit.jar:git-Spigot-3d850ec-809c399]
        ... 17 more
[16:14:00 INFO]: Title command successfully executed
[16:14:00 INFO]: Title command successfully executed
[16:14:01 INFO]: yuh3ng issued server command: /quest
[16:14:01 WARN]: java.lang.NullPointerException
[16:14:01 WARN]:        at me.blackvein.quests.Quests.showObjectives(Quests.java
:1759)
[16:14:01 WARN]:        at me.blackvein.quests.Quests.questCommandHandler(Quests
.java:1599)
[16:14:01 WARN]:        at me.blackvein.quests.Quests.onCommand(Quests.java:566)

[16:14:01 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[16:14:01 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[16:14:01 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchC
ommand(CraftServer.java:649)
[16:14:01 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handle
Command(PlayerConnection.java:1397)
[16:14:01 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(Play
erConnection.java:1232)
[16:14:01 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(Pack
etPlayInChat.java:45)
[16:14:01 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(Pack
etPlayInChat.java:1)
[16:14:01 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1
.run(SourceFile:13)
[16:14:01 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[16:14:01 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:14:01 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFil
e:46)
[16:14:01 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(Minec
raftServer.java:748)
[16:14:01 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(Dedic
atedServer.java:406)
[16:14:01 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(Minec
raftServer.java:679)
[16:14:01 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(Min
ecraftServer.java:577)
[16:14:01 WARN]:        at java.lang.Thread.run(Unknown Source)
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/AX7HxNsh

**Comment by FlyingPikachu** [comment]
What is the name of the quest that causes this error?

**Comment by uraqtlee** [comment]
I'm pretty sure it happens to most of the quests which involves block breaking : "Mining Adventure, Light it up" <-- These are the notable ones that my players have reported that when they destroy the needed block, in the quest the counter doesn't go up.

**Comment by johnsoncui02** [comment]
you could try using the bleeding edge builds which works fine on all ore types. here's the link to download the latest 3.1.9 builds.
http://ci.ac3-servers.eu/job/Quests/

IMPORTANT: use at your own risk.

**Comment by uraqtlee** [comment]
I tried updating to the 3.1.9, although it doesn't show the BlockBreakEvent error, when they destroy the needed blocks the counter still doesn't go up.
A new error seems to appear also:
https://pastebin.com/g7Ucgr5p

**Comment by uraqtlee** [comment]
i hope the error can be determined soon because using BetonQuest just makes me wanna kill my self

**Comment by FlyingPikachu** [comment]
This error was resolved a few days ago through #146. Dev build 233 or higher should resolve this issue. Thanks for using Quests!

http://ci.ac3-servers.eu/job/Quests/234/
