### ISSUE TITLE
Citizens NPC error

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#229]
Quests 3.2.0 stable

NPC citizens error

[18:19:42] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v3.2.0-b232
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:415) [citizens-2.0.22-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor692.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1580) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.CustomObjective.equals(CustomObjective.java:160) ~[?:?]
	at java.util.AbstractList.equals(AbstractList.java:523) ~[?:1.8.0_121]
	at me.blackvein.quests.Stage.equals(Stage.java:227) ~[?:?]
	at java.util.AbstractList.equals(AbstractList.java:523) ~[?:1.8.0_121]
	at me.blackvein.quests.Quest.equals(Quest.java:637) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:940) ~[?:1.8.0_121]
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:1.8.0_121]
	at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:110) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor695.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	... 23 more

**Comment by FlyingPikachu** [comment]
Are you using any extra modules or plugins that link with Quests? This part of your error:
`at me.blackvein.quests.CustomObjective.equals(CustomObjective.java:160) ~[?:?]`
seems to indicate that a module/plugin has neglected to include an author in its [API](https://github.com/FlyingPikachu/Quests/wiki/Quests-API#objectives-api) integration.

If not, please provide the quest from quests.yml that your NPC is hosting.

**Comment by SwimUp29** [comment]
Yes, i use mythicmobs custom objectives, but I found that I did not use the latest version of the module, so if the error recurs, I'll let you know. Thank you!
