### ISSUE TITLE
1.7.10 Can not be loaded

### ISSUE THREAD

**Issue by Xiazihong** [FlyingPikachu/Quests#239]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
v3.2.1-b235
(__Required__) Please describe the problem and how to replicate it. Any console errors?
[18:36:43] [Server thread/INFO]: [Quests] Enabling Quests v3.2.1-b235
[18:36:44] [Server thread/ERROR]: Error occurred while enabling Quests v3.2.1-b235 (Is it up to date?)
java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Unknown Source) ~[?:1.8.0_151]
	at java.util.regex.Matcher.replaceAll(Unknown Source) ~[?:1.8.0_151]
	at java.lang.String.replaceAll(Unknown Source) ~[?:1.8.0_151]
	at me.blackvein.quests.Quests.saveResourceAs(Quests.java:242) ~[?:?]
	at me.blackvein.quests.Quests.setupLang(Quests.java:219) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:185) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:420) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:352) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:507) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:481) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:441) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:353) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
The default configuration has no tasks

**Comment by FlyingPikachu** [comment]
Resolved in 861eb4185267ff95edc2dbe4d16f554ee3ff44d3

Dev build which contains the fix:
http://ci.ac3-servers.eu/job/Quests/236/
