### ISSUE TITLE
PlayerMoveEvent

### ISSUE THREAD

**Issue by SwimUp29** [FlyingPikachu/Quests#240]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.1 b234
(__Required__) Please describe the problem and how to replicate it. Any console errors?
[10:37:59] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v3.2.1-b234
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:365) ~[?:?]
	at me.blackvein.quests.Quester.updateJournal(Quester.java:268) ~[?:?]
	at me.blackvein.quests.Quester$1.put(Quester.java:69) ~[?:?]
	at me.blackvein.quests.Quester$1.put(Quester.java:62) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:1914) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2017) ~[?:?]
	at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:692) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[java8.jar:git-Spigot-b66ad9e-e1fb9cb]
	... 15 more

**Comment by FlyingPikachu** [comment]
This is likely the result of #238
