### ISSUE TITLE
Use mods.flammpfeil.slashblade.ItemSlashBlade kill monster error

### ISSUE THREAD

**Issue by Xiazihong** [FlyingPikachu/Quests#257]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.2-b246
(__Required__) Please describe the problem and how to replicate it. Any console errors?
[12:42:51] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Quests v3.2.2-b246
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:361) [CraftEventFactory.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1074) [sv.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:980) [sv.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) [yg.class:?]
	at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:249) [yq.class:?]
	at mods.flammpfeil.slashblade.ItemSlashBlade.doAttack(ItemSlashBlade.java:1238) [ItemSlashBlade.class:?]
	at mods.flammpfeil.slashblade.ItemSlashBlade.nextAttackSequence(ItemSlashBlade.java:1182) [ItemSlashBlade.class:?]
	at mods.flammpfeil.slashblade.ItemSlashBlade.func_77659_a(ItemSlashBlade.java:1171) [ItemSlashBlade.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:165) [add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:384) [mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:748) [nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:176) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quester.killMob(Quester.java:952) ~[?:?]
	at me.blackvein.quests.PlayerListener.killMob(PlayerListener.java:509) ~[?:?]
	at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:475) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor355.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
	... 23 more
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
  副本每日任务1:
    name: '§E每日任务.1'
    ask-message: '§b任务要求 §7> §A击杀 §c10 §a只僵尸       §6奖励§7:§6 1千 金币'
    finish-message: '§8[§6任务系统§8] §7> §a出色的完成了任务 收下你的奖励吧 冒险家'
    redo-delay: 86400
    npc-giver-id: 1
    gui-display: name-5598:amount-1
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 10
    rewards:
      money: 1000

**Comment by FlyingPikachu** [comment]
The "SlashBlade" modification has changed Zombies in a way which interferes with Quests. Typically, no support is provided for such mods. I will push out a dev build which should minimize these errors. However, no further assistance will be provided. If you continue to experience problems, remove the modification.
