### ISSUE TITLE
EntityDeathEvent -> NullPointerException

### ISSUE THREAD

**Issue by seema84** [FlyingPikachu/Quests#259]
Could not pass event EntityDeathEvent to Quests v2.5.3
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:874) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.EntityEnderman.damageEntity(EntityEnderman.java:294) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
at me.blackvein.quests.Quester.killMob(Quester.java:1104) ~[?:?]
at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:711) ~[?:?]
at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
... 22 more

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
