### ISSUE TITLE
Quest is unable to save

### ISSUE THREAD

**Issue by clayper** [FlyingPikachu/Quests#261]
I am using it alongside Citizens 2, if that means anything regarding my issue
We are running 1.8.8 Spigot on the server that we are trying to make quests on

[20:13:13] [Server thread/ERROR]: Error handling conversation prompt
java.lang.NullPointerException
at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1031) ~[?:?]
at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:1011) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:729) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
