### ISSUE TITLE
Paper Spigot not supported

### ISSUE THREAD

**Issue by PengBread** [FlyingPikachu/Quests#263]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.2
(__Required__) Please describe the problem and how to replicate it. Any console errors?

[14:12:17] [Server thread/ERROR]: [Quests] Failed loading lang files for en-US because they were not found. Using default en-US
[14:12:17] [Server thread/ERROR]: Error occurred while enabling Quests v3.2.2-b246 (Is it up to date?)
java.lang.NullPointerException: null
	at java.io.Reader.<init>(Unknown Source) ~[?:1.8.0_121]
	at java.io.InputStreamReader.<init>(Unknown Source) ~[?:1.8.0_121]
	at me.blackvein.quests.util.Lang.loadLang(Lang.java:113) ~[?:?]
	at me.blackvein.quests.Quests.setupLang(Quests.java:225) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:185) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1318]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1318]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1318]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
What about this leads you to believe Paper Spigot is the issue?

Based on Quests failed to load lang files, I believe the latest dev build should resolve this issue.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP. Paper Spigot is also not officially supported (although I'm still doubtful that's the issue).
