### ISSUE TITLE
Could not pas NPCRightClickEvent to NPC when delivering a quest item

### ISSUE THREAD

**Issue by Volkenstein666** [FlyingPikachu/Quests#266]
I can't remember when exactly but I started having issues with Quests about 2 months ago with quests involving multiple stages (usually no more than 3). The quest would 'complete' but no reward would be issued. That is- the text (complete) would fire on the screen but the quest would still be in the quests journal and no reward would be given. I remember also seeing 'null' happen a few times- anyway this time I am trying to complete a 2 stage quest with the last stage involving the delivery of a rabbits foot to a citizen NPC. The rabbit's foot WAS removed from my inventory- and the (completed delivery of rabbits foot) text fired as well as the complete quest text as it was suppose to- but no reward was given. I am using the latest #94 build of Quests and the latest Citizens build from Jenkins. As a side note- booting the server prompts no error text from the Quests plugin about improperly formatted quests. I use the plugin heavily and have combed through all 108 quests many times to keep them straight. 

Here it is- the command box error text in all its glory:

[21:24:25 ERROR]: Could not pass event NPCRightClickEvent to Quests v2.5.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[custom.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[custom.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:501) [custom.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:486) [custom.jar:git-Bukkit-53fac9f]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:
385) [citizens-2.0.16-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:300) [custom.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) [custom.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:501) [custom.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:486) [custom.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:1249) [custom.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [
custom.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [
custom.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [custom.jar:git-Bukkit-53fac9f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [custom.jar
:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:6
72) [custom.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
35) [custom.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
28) [custom.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:536) [custom.jar:git-Bukkit-53fac9f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at com.gmail.nossr50.datatypes.player.PlayerProfile.addLevels(PlayerProf
ile.java:276) ~[?:?]
        at me.blackvein.quests.Quest.completeQuest(Quest.java:379) ~[?:?]
        at me.blackvein.quests.Quest.nextStage(Quest.java:106) ~[?:?]
        at me.blackvein.quests.Quester.finishObjective(Quester.java:1455) ~[?:?]

        at me.blackvein.quests.Quester.deliverItem(Quester.java:1301) ~[?:?]
        at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:74)
~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja

**Comment by Volkenstein666** [comment]
I have discovered the issue- I was using MCMMO skill rewards on all the quests that were buggy for me. It turns out you cant select SALVAGE as an MCMMO quest reward because it is a 'child' or 'secondary' skill. All quests where I was rewarding SALVAGE as a skill reward were returning the above error. Simple fix for this one-- I just wont use that skill as a reward anymore. :)
