### ISSUE TITLE
Can someone help me? -error-

### ISSUE THREAD

**Issue by Zeuscp1** [FlyingPikachu/Quests#274]
[11:04:12 ERROR]: Could not pass event InventoryClickEvent to Quests v3.2.2-b246
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalArgumentException: Item cannot be null
        at org.apache.commons.lang.Validate.noNullElements(Validate.java:364) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.addItem(CraftInventory.java:282) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        at me.blackvein.quests.Quests.addItem(Quests.java:3730) ~[?:?]
        at me.blackvein.quests.Event.fire(Event.java:208) ~[?:?]
        at me.blackvein.quests.Quester.takeQuest(Quester.java:364) ~[?:?]
        at me.blackvein.quests.PlayerListener.onInventoryClickEvent(PlayerListener.java:150) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
        ... 15 more

**Comment by Zeuscp1** [comment]
The problem happens when i put an event that gives item

**Comment by FlyingPikachu** [comment]
Do you mean the "Give Items": event from _/quests events_, or "Deliver Items" from _/quests editor_? What item are you using? Did you load it from hand, or type it in? Please explain further how to replicate this issue.

**Comment by Zeuscp1** [comment]
@FlyingPikachu I need help with this, i know you may be bussy but is the only thing stopping me to continue making my server :/

**Comment by FlyingPikachu** [comment]
@Zeuscp1 This may take some time to resolve as there's suddenly a lot on my plate. I recommend not using the Give Items event until there's time to push a fix. Of course, I will notify you here once the issue can be resolved. Thanks!

**Comment by Zeuscp1** [comment]
@FlyingPikachu How long do you think this will take? Sorry if im bothering you, the problem is that i'm making my server and without this im kinda stopped. I would like to know an estimated time to see if i could wait or not

**Comment by Zeuscp1** [comment]
@FlyingPikachu  BTW it was working before, i dont know what happened, i tried everything i reinstalled the plugin a couple of times already and all...

**Comment by Midnight9746** [comment]
@FlyingPikachu Hey, I'm helping Zeuscp1 with trying to solve the issue, what he means is that he set it to when you click an NPC, it sends a GUI to allow you to click an item to take the quest.

Right now we have been having the quest give item rewards like a leather helmet named "Hunter Wizard" with some lore and the quest would spit out a normal one.

Another thing that it's doing now, is when we save the quest and edit it again, it resets the item reward. I'm not sure what's going on exactly, however is plugins like MCCore, Skill API, Command NPC, and any other messes with item names and lore?

P.S., take your time, we're gunna try to figure some work around.

**Comment by FlyingPikachu** [comment]
@Zeuscp1 I cannot provide an estimated time.

@Midnight9746 Are you implying that the error occurs when a player uses the GUI? Zeus gave me the impression the error happens when creating the event in-editor.

Can either of you provide the quests.yml and events.yml being worked on?

**Comment by Midnight9746** [comment]
@FlyingPikachu uh no. Just letting you know that's what's going on now.

The GUI is working now, it's just the name and lore that's bugging out

**Comment by Zeuscp1** [comment]
@FlyingPikachu  The error occurs with everything related to give an item with lore or custom name, in the events give item it crashes, in the events command it gives you a vanilla item with no name or lore, in the rewards it gives you a vanilla item too... and sure, here is the Quests and Events. 

https://www.dropbox.com/s/2gy6b0x3g0jmzb7/server.tar?dl=0

**Comment by FlyingPikachu** [comment]
Found some time to take a look at this today.

@Zeuscp1 stated earlier that you were using the Give Items event. This is not true, as your events.yml shows you are using the Run Command event to try and _/give_ an item to the player.

This does not work because your command contains advanced formatting including colons (":"), which are not allowed in commands. You've essentially corrupted your events.yml file.

You to use the Give Items event, shown here:

![Give Items event](https://i.imgur.com/sMxoheQ.png)

In your events.yml, it should end up looking something like this:

>   Test:
    items:
    - name-DIAMOND_SWORD:amount-1:enchantment-Sharpness 2:lore-Hello

**Comment by Midnight9746** [comment]
Ah, that's what he ment by events... thanks @FlyingPikachu

**Comment by ScuroK** [comment]
#318 i suggest you rather remove the give items event completely since users can use give commands instead. to deny th colons breaks more things like command events. and they are crucial.

**Comment by ScuroK** [comment]
i never had any problems with the "give items" fuction. no matter i used special names and lores or not.
