### ISSUE TITLE
Can't save the quest

### ISSUE THREAD

**Issue by InfroDaz** [FlyingPikachu/Quests#278]
(__Required__) What is your Quests version 3.2.4/ build 255 ?

(__Required__) While saving quest this error occurs:

`[17:15:19 WARN]: [Quests] Plugin Quests v3.2.4-b255 generated an exception whilst handling conversation input
java.lang.NullPointerException: null
        at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:788) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:228) ~[spigot.jar:git-Spigot-4bd94dc-015bda4]
        at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1123) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1246) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-015bda4]`

(__Optional__) quests.yml empty

**Comment by FlyingPikachu** [comment]
Looks like you didn't follow the instructions in the update notes on Spigotmc.org:

> BREAKING: This marks the completion of the new localization system! :) However, updating requires that you regenerate your preferred language file (/lang/****/strings.yml) after backing up your old one. Failing to do so will, at the very least, break the Quests Editor for that locale. First time installers can disregard this message.

**Comment by InfroDaz** [comment]
I am kind of misunderstanding the instructions or something wrong with my config or Idk. I've deleted lang folder and plugin generated new folder for different languages. I've choosen ru-RU lang in config and restarted again. Tried to make a quest and still have the same error.

**Comment by InfroDaz** [comment]
Nevermind I've just deleted entire folder
