### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by KeinNerd** [FlyingPikachu/Quests#278]
After i copy my MC Server to an new Dedicated Server. I get these Error. 

`Starting server with command: java -Xincgc -Xmx4096M -XX:MaxPermSize=128M -jar spigot.jar nogui

Loading libraries, please wait...

>
[23:09:35 INFO]: Starting minecraft server version 1.8.8

>
[23:09:35 INFO]: Loading properties

>
[23:09:35 INFO]: Default game type: SURVIVAL

>
[23:09:36 INFO]: This server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

>
[23:09:36 INFO]: Debug logging is disabled

>
[23:09:36 INFO]: Server Ping Player Sample Count: 12

>
[23:09:36 INFO]: Using 4 threads for Netty based IO

>
[23:09:36 INFO]: Generating keypair

>
[23:09:36 INFO]: Starting Minecraft server on 94.23.210.226:25565

>
[23:09:36 INFO]: Using epoll channel type

>
[23:09:36 ERROR]: Could not load 'plugins/Quests-2.5.3-b92.jar' in folder 'plugins'

org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]

        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-5f38d38-18fbb24]

        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-5f38d38-18fbb24]

        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-5f38d38-18fbb24]

        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-5f38d38-18fbb24]

        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

Caused by: java.util.zip.ZipException: error in opening zip file

        at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_80]

        at java.util.zip.ZipFile.<init>(ZipFile.java:215) ~[?:1.7.0_80]

        at java.util.zip.ZipFile.<init>(ZipFile.java:145) ~[?:1.7.0_80]

        at java.util.jar.JarFile.<init>(JarFile.java:154) ~[?:1.7.0_80]

        at java.util.jar.JarFile.<init>(JarFile.java:118) ~[?:1.7.0_80]

        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]

        ... 5 more`

Someone an idea?

**Comment by i9hdkill** [comment]
plugin.yml is missing or wrong version
Redownload the plugin to fix it

**Comment by ImSoFancyy** [comment]
I have the same proble already redownloaded the plugin twice from diferent browsers even different version still same error

**Comment by ApolluZed** [comment]
people are still having the same problem and it hasn't been fixed. It's been a while since someone has actually reported it too.

Just gonna have to keep looking.
