### ISSUE TITLE
1.7.10 Console Spam

### ISSUE THREAD

**Issue by caxerx** [FlyingPikachu/Quests#28]
I am using the last build, same issue on previous build
[13:03:05] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v2.2.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:249) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInFlying.a(SourceFile:137) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInPosition.handle(PacketPlayInPosition.java:35) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:1.8.0_25]
	at java.util.concurrent.ConcurrentHashMap.put(Unknown Source) ~[?:1.8.0_25]
	at me.blackvein.quests.Quester$1.put(Quester.java:50) ~[?:?]
	at me.blackvein.quests.Quester$1.put(Quester.java:44) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2573) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2503) ~[?:?]
	at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:909) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	... 13 more

**Comment by caxerx** [comment]
Another Error
[13:03:05] [Server thread/WARN]: [Quests] Task #95 for Quests v2.2.2 generated an exception
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:1.8.0_25]
	at java.util.concurrent.ConcurrentHashMap.put(Unknown Source) ~[?:1.8.0_25]
	at me.blackvein.quests.Quester$1.put(Quester.java:50) ~[?:?]
	at me.blackvein.quests.Quester$1.put(Quester.java:44) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2573) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2503) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [bukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]

**Comment by Leescar** [comment]
The plugin has been tweaked because of 1.8 updates, your not going to get backwards compatibility using 1.7.x or lower anything.

**Comment by caxerx** [comment]
ok thanks. I will consider upgrade to 1.8 server

**Comment by FlyingPikachu** [comment]
For the record, this was not related to the Minecraft server version, but rather a HashMap issue I've been working on.
