### ISSUE TITLE
Block-Break-Event Issue

### ISSUE THREAD

**Issue by johnsoncui02** [FlyingPikachu/Quests#282]
Quest Version: 3.2.4
Server Version: Spigot 1.12.2

Issue: Block Break Event for REDSTONE_ORE does not work

Replicating GIF example
![mc3](https://user-images.githubusercontent.com/23487437/35966191-f5406142-0c71-11e8-8bc9-2a551fd5400a.gif)

**Comment by Midnight9746** [comment]
Maybe it's thinking you're supposed to break an unpowered redstone ore, since hitting it or walking over it changes the data values.

**Comment by FlyingPikachu** [comment]
@Midnight9746 might be right. @johnsoncui02 Try GLOWING_REDSTONE_ORE and let us know what happens

**Comment by johnsoncui02** [comment]
After a couple tries of using
GLOWING_REDSTONE_ORE
LIT_REDSTONE_ORE
74

It would always provide some sort of bug that couldn't make it work correctly.
![image](https://user-images.githubusercontent.com/23487437/36097015-d04f8324-0fad-11e8-8bc5-f1969755ae06.png)

Bug report over here.
> [12:32:27 INFO]: CornChowderSoup issued server command: /questsadmin reload
> [12:32:27 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questsadmin' in plugin Quests v3.2.4-b255
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-9b8bba4-bdcc7c7]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-9b8bba4-bdcc7c7]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-9b8bba4-bdcc7c7]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [server.jar:git-Spigot-9b8bba4-bdcc7c7]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [server.jar:git-Spigot-9b8bba4-bdcc7c7]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-9b8bba4-bdcc7c7]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-9b8bba4-bdcc7c7]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-9b8bba4-bdcc7c7]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-9b8bba4-bdcc7c7]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-9b8bba4-bdcc7c7]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-9b8bba4-bdcc7c7]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-9b8bba4-bdcc7c7]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-9b8bba4-bdcc7c7]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[server.jar:git-Spigot-9b8bba4-bdcc7c7]
at me.blackvein.quests.Quests.processStages(Quests.java:2614) ~[?:?]
at me.blackvein.quests.Quests.loadQuests(Quests.java:2168) ~[?:?]
at me.blackvein.quests.Quests.reloadQuests(Quests.java:1983) ~[?:?]
at me.blackvein.quests.Quests.adminReload(Quests.java:721) ~[?:?]
at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:676) ~[?:?]
at me.blackvein.quests.Quests.onCommand(Quests.java:665) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-9b8bba4-bdcc7c7]
... 15 more

**Comment by FlyingPikachu** [comment]
It seems GLOWING_REDSTONE_ORE is the correct value to use. However, VaultAPI (which currently processes item names), considers this block unimportant and ignores it, resulting in errors. I'll attempt to see if we can get around this in VaultAPI, otherwise I may have to code specifically for Redstone Ore.

**Comment by FlyingPikachu** [comment]
With VaultAPI no longer being used, this issue should be resolved in recent builds of Quests.
