### ISSUE TITLE
PlayerDeathEvent on build 256

### ISSUE THREAD

**Issue by PortGasMC** [FlyingPikachu/Quests#283]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Build 256

(__Required__) Please describe the problem and how to replicate it. Any console errors?
I installed the plugin without no quest configured,just the default config 
And it is spamming my console 
https://pastebin.com/PrMY6d4p
My plugins: 
https://pastebin.com/ZXhqnBPG
I'm using spigot 1.12.2 latest build

**Comment by datitisev** [comment]
Same in paperspigot 1.11 build.

```sh
[19:32:01 ERROR]: Could not pass event EntityDeathEvent to Quests v3.2.4-b255
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1072]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.2.jar:git-Paper-1072]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1072]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1072]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1072]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:395) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1100) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.EntityZombie.die(EntityZombie.java:429) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:954) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.EntityZombie.damageEntity(EntityZombie.java:163) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.Explosion.a(Explosion.java:140) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.World.createExplosion(World.java:2010) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.WorldServer.createExplosion(WorldServer.java:1196) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.EntityTNTPrimed.explode(EntityTNTPrimed.java:101) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.EntityTNTPrimed.A_(EntityTNTPrimed.java:81) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1740) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1715) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1532) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:621) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:898) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1072]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1072]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:465) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor804.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1072]
        ... 24 more
```

**Comment by datitisev** [comment]
Seems like the issue is that the tnt source is null.
 https://github.com/FlyingPikachu/Quests/blob/master/src/main/java/me/blackvein/quests/PlayerListener.java#L462-L468

**Comment by FlyingPikachu** [comment]
@datitisev I believe you're right, although it's odd that it doesn't have a source. Will add a null check shortly!
