### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by InfroDaz** [FlyingPikachu/Quests#285]
3.2.4 b256

Console is being constantly spammed by this

`        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-015bda4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NumberFormatException: For input string: "Bundle"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_151]
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_151]
        at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_151]
        at me.blackvein.quests.Quester.loadData(Quester.java:2113) ~[?:?]
        at me.blackvein.quests.Quests.getQuester(Quests.java:2022) ~[?:?]
        at me.blackvein.quests.PlayerListener.onPlayerInteract(PlayerListener.java:189) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor604.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at`

**Comment by FlyingPikachu** [comment]
There’s something wrong with your quests.yml file (or how it’s being loaded). Please upload the file for review.

**Comment by InfroDaz** [comment]
More errors https://pastebin.com/abyDzGwG
https://cdn.discordapp.com/attachments/358630608747888651/412009708304465920/quests.yml

**Comment by InfroDaz** [comment]
Error related to another problem https://pastebin.com/1MKCRVrn

As I think this is because my world name contains spaces (Biome Bundle)
