### ISSUE TITLE
Console spam 1.8 spigot

### ISSUE THREAD

**Issue by ye8us** [FlyingPikachu/Quests#29]
keep getting this eeror

[03:48:16] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v2.2.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[sp.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[sp.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [sp.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [sp.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:255) [sp.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126) [sp.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInPosition.a(SourceFile:57) [sp.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [sp.jar:git-Spigot-8a983f9-e81edfc]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [sp.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [sp.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [sp.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [sp.jar:git-Spigot-8a983f9-e81edfc]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quester.getCurrentStage(Quester.java:324) ~[?:?]
	at me.blackvein.quests.Quester.hasObjective(Quester.java:873) ~[?:?]
	at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:909) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[sp.jar:git-Spigot-8a983f9-e81edfc]
	... 14 more
every time someone move in the server..

**Comment by Formula350** [comment]
I had that problem too (mind you, I'm on CraftBukkit and not Spigot), and I am pretty sure it's caused from one of the two:
Player's Data file contains: - null
Player's Data file contains: An old quest that did not properly get purged from their file.

Fixes: Either delete their file, **or** edit them so it no longer contains either of the above. (the second method is more involved but is better since it won't reset all of their quest progress.

No matter which fix you use, **make sure the player is not online** or it won't recognize the new file data. What I've been doing is I'll edit the file, save it and start the upload (or Copy, if you have Remote access), then when it asks if you want to Overwrite? I ask the player to leave for 10 seconds, at which point I hit OK (to overwrite). If they ignore you I just tempban them for 1 minute with the reason being you needed them to leave to fix their quests :P

Hope that helps!

**Comment by FlyingPikachu** [comment]
Quests v2.3.3 should resolve this: http://www.spigotmc.org/resources/quests.3711/update?update=15550

**Comment by FlyingPikachu** [comment]
Scratch that, use Quests v2.2.4: http://www.spigotmc.org/resources/quests.3711/update?update=15610
