### ISSUE TITLE
Quests is having issues... Somewhere

### ISSUE THREAD

**Issue by NomzHD** [FlyingPikachu/Quests#298]
[17:42:38] [Server thread/WARN]: [Quests] Task #78 for Quests v2.5.5-b95 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/World
	at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:125) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.java:131) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:41) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.World
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
	... 10 more

**Comment by FlyingPikachu** [comment]
Please try the build I just pushed which _should_ be compatible with 1.9. If this still occurs create a new ticket. Thanks!
