### ISSUE TITLE
Console Spam - Particle Related (Latest Build for 1.9)

### ISSUE THREAD

**Issue by RyanEvenstar** [FlyingPikachu/Quests#300]
07:39:06] [Server thread/WARN]: [Quests] Task #157 for Quests v2.6.0-b98 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/Packet
	at me.blackvein.quests.NpcEffectThread.showEffect_1_9_R1(NpcEffectThread.java:134) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:79) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_71]
	... 10 more
[07:39:06] [Server thread/INFO]: [CommandTimer] Saving timers...
[07:39:07] [Server thread/WARN]: [Quests] Task #157 for Quests v2.6.0-b98 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/Packet
	at me.blackvein.quests.NpcEffectThread.showEffect_1_9_R1(NpcEffectThread.java:134) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:79) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_71]
	... 10 more
[07:39:08] [Server thread/WARN]: [Quests] Task #157 for Quests v2.6.0-b98 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/Packet
	at me.blackvein.quests.NpcEffectThread.showEffect_1_9_R1(NpcEffectThread.java:134) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:79) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [custom_server.jar:git-Spigot-129f87a-6067e54]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[custom_server.jar:git-Spigot-129f87a-6067e54]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_71]
	... 10 more

**Comment by FlyingPikachu** [comment]
Please post your Spigot version number **as it appears when you start your server (at the top of the log).**

**Comment by RyanEvenstar** [comment]
07:33:37] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-129f87a-6067e54 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Comment by FlyingPikachu** [comment]
Fixed in #304
