### ISSUE TITLE
console spam (over and over) related to Task #93

### ISSUE THREAD

**Issue by Volkenstein666** [FlyingPikachu/Quests#301]
[20:28:39 WARN]: [Quests] Task #93 for Quests v2.6.0-b98 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/Packet
        at me.blackvein.quests.NpcEffectThread.showEffect_1_9_R1(NpcEffectThread
.java:134) ~[?:?]
        at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:7
9) ~[?:?]
        at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:
?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:53) ~[custom.jar:git-Bukkit-712213d]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:349) [custom.jar:git-Bukkit-712213d]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:6
86) [custom.jar:git-Bukkit-712213d]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:3
61) [custom.jar:git-Bukkit-712213d]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:6
35) [custom.jar:git-Bukkit-712213d]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java
:539) [custom.jar:git-Bukkit-712213d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Packet

        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:67) ~[custom.jar:git-Bukkit-712213d]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:62) ~[custom.jar:git-Bukkit-712213d]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
        ... 10 more

no idea what this is related to... happens upon me logging onto the server
I am using the craftbukkit.jar created by the latest BuildTools as of 3/30/16
also using the latest Citizens2 and Denizens jarfile

**Comment by Formula350** [comment]
It's related to the NPC Particles that indicate it has a quest. Looks like this was fixed: 
https://github.com/FlyingPikachu/Quests/commit/1329fe45293797f9797582f2bd8ad8fb4b50a22e 
 
Give it a try, [here's the version](http://ci.ac3-servers.eu/job/Quests/lastSuccessfulBuild/artifact/target/Quests-2.6.0.jar) which includes that code, so if it fixes your problem I suggest clicking the Closed button to close this issue. 

Alternatively, if this DOESN'T fix it for you, I had this issue when 1.8 came out, and just going into the config to disable the particles will at least prevent this from happening.

**Comment by FlyingPikachu** [comment]
Fixed in build mentioned by @Formula350
