### ISSUE TITLE
Quests MythicMobs kill error

### ISSUE THREAD

**Issue by Sefreneth** [FlyingPikachu/Quests#308]
Quests version 3.2.4-b255
 So a few months ago I did quests for killing some bosses made in MythicMobs, no problem at all, but now it started to throw error in console every time we kill these bosses, and when i take the quest it just won't count that kill... any ideas? Outdated MythicMobs mod maybe?

Could not pass event EntityDeathEvent to Quests v3.2.4-b255
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:395) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1114) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.EntityZombie.die(EntityZombie.java:429) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.MobEffectList.applyInstantEffect(MobEffectList.java:103) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.EntityPotion.a(EntityPotion.java:185) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.EntityPotion.a(EntityPotion.java:100) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.EntityProjectile.B_(EntityProjectile.java:167) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NoSuchFieldError: currentQuests
at com.gmail.berndivader.questsMythicMobsKillObjective.QuestMMKillObjective.onMythicMobDeathEvent(QuestMMKillObjective.java:68) ~[?:?]
at sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-4bd94dc-bacaf92]
... 22 more

**Comment by FlyingPikachu** [comment]
This is an error with the MythicMobs module. Please seek help from the developers of that module.
