### ISSUE TITLE
Random EntityDeathEvent console error (Quests v2.2.2)

### ISSUE THREAD

**Issue by Formula350** [FlyingPikachu/Quests#31]
This may or may not be a fluke, but I had just updated to the latest Quests build (from Jenkins) and restarted, when players were getting back to doing what they had been doing when this showed up:

``` javascript
[16:33:54] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Quests v2.2.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:346) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.EntityLiving.die(EntityLiving.java:830) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.EntityZombie.die(EntityZombie.java:540) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.EntityLiving.damageEntity(EntityLiving.java:768) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.EntityMonster.damageEntity(EntityMonster.java:44) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.EntityZombie.damageEntity(EntityZombie.java:168) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.EntityArrow.s_(EntityArrow.java:232) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1374) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.World.g(World.java:1352) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1222) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:539) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:700) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333) ~[?:1.7.0_72]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1125) ~[?:1.7.0_72]
	at me.blackvein.quests.Quester$1.put(Quester.java:50) ~[?:?]
	at me.blackvein.quests.Quester$1.put(Quester.java:44) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2573) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2503) ~[?:?]
	at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:597) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor425.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	... 20 more
```

I don't really know much about what was going on except that SOME player was fighting one of our Citizen NPC bosses; however,  none of them are Zombies but 'Player' NPCs.  I only know this because console was being spammed with that UUID and that I should "consider blacklisitng them" (which I did, side-request on that topic: allow for the Blacklist to support Citizen NPC ID#s as well as UUIDs)

I'll gladly provide anything else I can though.
Thanks!

**Comment by Formula350** [comment]
The spammed UUID that was occurring at the same time turns out to NOT be a Citizens NPC as I thought, but a player. I don't know if it's related to this issue or not, but it is it turns out it's happening again, with a different player... So I am creating a new issue for this.

**Comment by FlyingPikachu** [comment]
Quests v2.3.3 should resolve this: http://www.spigotmc.org/resources/quests.3711/update?update=15550

**Comment by Formula350** [comment]
I'm a derp, I should've updated this one instead of the other, given the relevance... Either way, see my other issue for the response on everything. TL;DR though is: 2.2.3 caused similar errors almost continually (albeit not on a restart, but a live-reload going from Build 36 to Build 40)

**Comment by FlyingPikachu** [comment]
Quests v2.2.4 should resolve that console spam: http://www.spigotmc.org/resources/quests.3711/update?update=15610
