### ISSUE TITLE
Command as reward not working (NPCRightClickEvent)

### ISSUE THREAD

**Issue by Regnak85** [FlyingPikachu/Quests#317]
What is your Quests version / build number (do _not_ say "latest")?
3.2.5-b264

As an Quest Reward, Quests should do a command.
But if someone finish the Quest:

[15:29:11] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v3.2.5-b264
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:414) [Citizens.jar:?]
	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1580) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'hf' in plugin HexenFraktionen v0.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at me.blackvein.quests.Quest.completeQuest(Quest.java:316) ~[?:?]
	at me.blackvein.quests.Quest.nextStage(Quest.java:114) ~[?:?]
	at me.blackvein.quests.Quester.finishObjective(Quester.java:1238) ~[?:?]
	at me.blackvein.quests.Quester.deliverItem(Quester.java:1089) ~[?:?]
	at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:71) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor189.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	... 23 more
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
	at de.HexenFraktionen.Main.onCommand(Main.java:62) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	at me.blackvein.quests.Quest.completeQuest(Quest.java:316) ~[?:?]
	at me.blackvein.quests.Quest.nextStage(Quest.java:114) ~[?:?]
	at me.blackvein.quests.Quester.finishObjective(Quester.java:1238) ~[?:?]
	at me.blackvein.quests.Quester.deliverItem(Quester.java:1089) ~[?:?]
	at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:71) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor189.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-4bd94dc-fb414fe]
	... 23 more

**Comment by FlyingPikachu** [comment]
Can you provide the quest from quests.yml which causes this error (use Pastebin)?

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
