### ISSUE TITLE
questadmin reload problem

### ISSUE THREAD

**Issue by RescoolCZ** [FlyingPikachu/Quests#321]
quest-3.2.5

>[2K [21:34:52 WARN]: Unexpected exception while parsing console command "questadmin reload" 
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.2.4-b263 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-4bd94dc-8bb4f6c] 
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-4bd94dc-8bb4f6c] 
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-4bd94dc-8bb4f6c] 
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [server.jar:git-Spigot-4bd94dc-8bb4f6c] 
at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [server.jar:git-Spigot-4bd94dc-8bb4f6c] 
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [server.jar:git-Spigot-4bd94dc-8bb4f6c] 
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-4bd94dc-8bb4f6c] 
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-4bd94dc-8bb4f6c] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144] 
Caused by: java.lang.IllegalArgumentException: Enchantment cannot be null 
at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[server.jar:git-Spigot-4bd94dc-8bb4f6c]
at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaItem.addEnchant(CraftMetaItem.java:710) ~[server.jar:git-Spigot-4bd94dc-8bb4f6c] 
at me.blackvein.quests.util.ItemUtil.readItemStack(ItemUtil.java:114) ~[?:?] 
at me.blackvein.quests.Quests.processStages(Quests.java:2852) ~[?:?] 
at me.blackvein.quests.Quests.loadQuests(Quests.java:2159) ~[?:?] 
at me.blackvein.quests.Quests.reloadQuests(Quests.java:1984) ~[?:?] 
at me.blackvein.quests.Quests.adminReload(Quests.java:722) ~[?:?] 
at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:677) ~[?:?] 
at me.blackvein.quests.Quests.onCommand(Quests.java:666) ~[?:?] 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-4bd94dc-8bb4f6c] 
... 8 more

https://pastebin.com/GcPQcf1Q

**Comment by FlyingPikachu** [comment]
One of your enchantments in your quests.yml is invalid. You'll have to post your quests.yml for us to investigate this any further.

**Comment by RescoolCZ** [comment]
https://pastebin.com/GcPQcf1Q

**Comment by FlyingPikachu** [comment]
So, it turns out your enchantments are fine. I believe your quests.yml is not encoded in UTF-8.

If you're on Windows, shut down your server and open the quests.yml in Notepad. Go to Save As and, at the bottom of the window, you'll see "Encoding:". Make sure it's set to UTF-8 and overwrite the old file.

220e0c0 should help make this more evident in the future.

**Comment by FlyingPikachu** [comment]
You're overwriting it, not deleting it. If you've edited your lang file, make sure that's UTF-8 as well.
