### ISSUE TITLE
error spam 1.9.4

### ISSUE THREAD

**Issue by seema84** [FlyingPikachu/Quests#323]
[Quests] Task #44 for Quests v2.6.0-b99 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/Packet
at me.blackvein.quests.NpcEffectThread.showEffect_1_9_R1(NpcEffectThread.java:134) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:79) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.Packet
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-4af49dc-e22506f]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
... 10 more

**Comment by Liphius** [comment]
This is extremely annoying as I've just updated to 1.9.4. Please fix it asap!

**Comment by FlyingPikachu** [comment]
Fixed in latest test build - http://ci.ac3-servers.eu/job/Quests/100/
