### ISSUE TITLE
[Quests] Task #72 for Quests v2.6.0-b99

### ISSUE THREAD

**Issue by sandmonkey** [FlyingPikachu/Quests#326]
[19:38:41 WARN]: [Quests] Task #72 for Quests v2.6.0-b99 generated an exception
java.lang.NullPointerException
        at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot_server.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot_server.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot_server.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot_server.jar:git-Spigot-4af49dc-23da8b0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]

**Comment by sandmonkey** [comment]
I am running 1.9.4 version MC. I will provide further details if needed

**Comment by FlyingPikachu** [comment]
@sandmonkey Update to the latest dev build. Your current build does not support 1.9.4
