### ISSUE TITLE
events.yml and other files don't exist

### ISSUE THREAD

**Issue by Seff300** [FlyingPikachu/Quests#329]
Quests 3.2.5
When I make events and save them they aren't saved and don't show up. I have tried regenerating the config but still doesn't work.
[19:17:38] [Server thread/INFO]: Seff300 issued server command: /quests events
[19:19:01] [Server thread/WARN]: java.io.FileNotFoundException: plugins/Quests/events.yml (No such file or directory)
[19:19:01] [Server thread/WARN]:        at java.io.FileInputStream.open0(Native Method)
[19:19:01] [Server thread/WARN]:        at java.io.FileInputStream.open(FileInputStream.java:195)
[19:19:01] [Server thread/WARN]:        at java.io.FileInputStream.<init>(FileInputStream.java:138)
[19:19:01] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[19:19:01] [Server thread/WARN]:        at me.blackvein.quests.EventFactory.saveEvent(EventFactory.java:751)
[19:19:01] [Server thread/WARN]:        at me.blackvein.quests.EventFactory.access$1800(EventFactory.java:57)
[19:19:01] [Server thread/WARN]:        at me.blackvein.quests.EventFactory$FinishPrompt.acceptInput(EventFactory.java:663)
[19:19:01] [Server thread/WARN]:        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:228)
[19:19:01] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.j$
[19:19:01] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1114)
[19:19:01] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1246)
[19:19:01] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24)
[19:19:01] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758)
[19:19:01] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[19:19:01] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[19:19:01] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[19:19:01] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by FlyingPikachu** [comment]
Are you saying the events.yml is not generated on startup? Or that it's there, but the files empty? What steps did you take to regenerate the file? Please elaborate.

**Comment by Seff300** [comment]
Weird today those files exist.

**Comment by FlyingPikachu** [comment]
Odd. Well if you experience further issues, don't hesitate to open a new ticket :)
