### ISSUE TITLE
Console keeps spamming "Task #40 for Quests v2.6.0-b99 generated an exception"

### ISSUE THREAD

**Issue by Esarte** [FlyingPikachu/Quests#331]
[12:11:31 WARN]: [Quests] Task #40 for Quests v2.6.0-b99 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/Packet
        at me.blackvein.quests.NpcEffectThread.showEffect_1_9_R1(NpcEffectThread.java:134) ~[?:?]
        at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:79) ~[?:?]
        at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-8a048fe-d8637df]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.Packet
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-8a048fe-d8637df]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-8a048fe-d8637df]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        ... 10 more

**Comment by Esarte** [comment]
I'm running Spigot 1.9.4 
I can see that quests that their stage has "Talk to NPC", once completed, they don't progress to the next stage and quests get stucked.

**Comment by Zalakoth** [comment]
I too have the issue with having them talk to NPCs. We just have to wait for a bug fix. :/

**Comment by FlyingPikachu** [comment]
@Esarte Use the latest dev build. Your current build is not compatible with Spigot 1.9.4.
