### ISSUE TITLE
Unable to edit ONE specific Quest. (Title is: "Tutorial")

### ISSUE THREAD

**Issue by Zalakoth** [FlyingPikachu/Quests#334]
I'm having this problem where after I create a quest, under specific, unknown circumstances, I cannot edit it again. Here are the logs when I execute the command:

[18:45:17 INFO]: Zalakoth issued server command: /quests editor
«types to edit quests»
«types Quest name ("Tutorial")»
[18:45:21 ERROR]: Error handling conversation prompt
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_91]
	at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_91]
	at me.blackvein.quests.Stage$3.equals(Stage.java:104) ~[?:?]
	at me.blackvein.quests.Stage.equals(Stage.java:236) ~[?:?]
	at java.util.LinkedList.indexOf(LinkedList.java:605) ~[?:1.8.0_91]
	at me.blackvein.quests.QuestFactory.loadQuest(QuestFactory.java:1895) ~[?:?]
	at me.blackvein.quests.QuestFactory$SelectEditPrompt.acceptInput(QuestFactory.java:458) ~[?:?]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at org.bukkit.craftbukkit.v1_9_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at org.bukkit.craftbukkit.v1_9_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.PlayerConnection$5.evaluate(PlayerConnection.java:1198) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at org.bukkit.craftbukkit.v1_9_R2.util.Waitable.run(Waitable.java:24) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:740) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by Zalakoth** [comment]
Version 2.6.0

**Comment by Zalakoth** [comment]
I believe it could have something to do with the "Talk with NPC" objective. I will test this out and tell you what I find.

**Comment by Zalakoth** [comment]
Quest is given below, I could not find any issues in the .yml file, but I know .yml can sometimes be mean. Also I *did* create the quest in-game so there should be no issues with it.

  custom1:
    name: Tutorial
    npc-giver-id: 16
    ask-message: I heard some strange noises in the tomb. Someone should go check it out.
    finish-message: Quest Complete!
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 26
        '2':
          locations-to-reach:
          - world 366.0 42.0 305.0
          reach-location-radii:
          - 2
          reach-location-names:
          - TWP1
          objective-override: Explore the Cave in the Tomb.
        '3':
          npc-ids-to-kill:
          - 18
          npc-kill-amounts:
          - 1
        '4':
          locations-to-reach:
          - world 391.0 57.0 323.0
          reach-location-radii:
          - 1
          reach-location-names:
          - TWP3
          objective-override: That was an Undead Bandit. Maybe there is a Necromancer hiding in this cave. Find him!
        '5':
          npc-ids-to-kill:
          - 21
          npc-kill-amounts:
          - 1
        '6':
          locations-to-reach:
          - world 444.0 74.0 323.0
          reach-location-radii:
          - 1
          reach-location-names:
          - TExit
          objective-override: Escape the Caves.
    rewards:
      money: 150
      quest-points: 1
      exp: 5

**Comment by FlyingPikachu** [comment]
@Zalakoth Please try Quests 2.6.4 and post the "new" error if still an issue.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP. If this is still an issue, follow my previous suggestion with the latest version of Quests. Thanks!
