### ISSUE TITLE
Exception when trying to save a quest in-game

### ISSUE THREAD

**Issue by j2ther** [FlyingPikachu/Quests#338]
Heyo,

Quests version 2.6.1-b100
Citizens version 2.0.18-SNAPSHOT (build 1371)
Spigot  git-Spigot-798f32d-0cd0397 (MC: 1.9.4)

I just did a fresh install of Quests and tried adding my first quest using the in-game editor.  Everything went fine until I went to save.  When trying to save the quest I get this exception in console

```
[04:52:18 ERROR]: Error handling conversation prompt
java.lang.NullPointerException
        at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1031) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Sp
igot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.conversations.ConversationTracker.acceptConversationInput(Co
nversationTracker.java:58) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:
1029) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection$5.evaluate(PlayerConnection.java:1198) [spigo
t.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-7
98f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:740) [spigot.jar:git-Sp
igot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Sp
igot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Sp
igot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-
Spigot-798f32d-0cd0397]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
```

Any help is appreciated, if you need any further information let me know!

**Comment by j2ther** [comment]
I apologize, you can close this as invalid.  I ended up deleting the quest.yml letting it regen and then redoing the quest in-game and everything worked out just fine!
