### ISSUE TITLE
Items can be taken out of Quest GUI [1.9 - 1.10]

### ISSUE THREAD

**Issue by MAZUU** [FlyingPikachu/Quests#343]
Console as following:

```
Could not pass event InventoryClickEvent to Quests v2.6.2-b101
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1851) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.IllegalArgumentException: Cannot create section at empty path
        at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.configuration.MemorySection.createSection(MemorySection.java:242) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.configuration.MemorySection.createSection(MemorySection.java:269) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at me.blackvein.quests.Quester.getBaseData(Quester.java:2089) ~[?:?]
        at me.blackvein.quests.Quester.saveData(Quester.java:2039) ~[?:?]
        at me.blackvein.quests.Quester.takeQuest(Quester.java:399) ~[?:?]
        at me.blackvein.quests.PlayerListener.onInventoryClickEvent(PlayerListener.java:175) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        ... 15 more
```

This is only happening on specific NPC's, could not reproduce on others.

**Comment by FlyingPikachu** [comment]
Seems to be an issue with one of your file's formatting. Upload your Quests folder?

**Comment by MAZUU** [comment]
https://www.dropbox.com/sh/mqcjtbn9bbl5tz5/AABbIZ0k4XT08Ow-n1KnW9lqa?dl=1 

Here you go.

**Comment by FlyingPikachu** [comment]
@MAZUU Reviewing this now.

**Comment by FlyingPikachu** [comment]
Didn't notice anything in particular wrong with your files. Please run this build of Quests I've cooked up, which should spit out more info next time there's an error. Kindly post back with results.

https://dl.dropboxusercontent.com/u/72509980/Quests-2.6.2.jar

**Comment by MAZUU** [comment]
@FlyingPikachu Here are the results i got:
`12:46:16 INFO]: Debug data for issue #343 - copy everything below this line including errors
[12:46:16 INFO]: Quest name: Durst.
[12:46:16 INFO]: data
[12:46:16 INFO]: dataSec: questData
[12:46:16 INFO]: DATAYamlConfiguration[path='', root='YamlConfiguration']
[12:46:16 ERROR]: Could not pass event InventoryClickEvent to Quests v2.6.2-b${env.BUILD_NUMBER}
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1851) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-8a048fe-71e5248]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.IllegalArgumentException: Cannot create section at empty path
        at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.configuration.MemorySection.createSection(MemorySection.java:242) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.configuration.MemorySection.createSection(MemorySection.java:269) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        at me.blackvein.quests.Quester.getBaseData(Quester.java:2094) ~[?:?]
        at me.blackvein.quests.Quester.saveData(Quester.java:2039) ~[?:?]
        at me.blackvein.quests.Quester.takeQuest(Quester.java:399) ~[?:?]
        at me.blackvein.quests.PlayerListener.onInventoryClickEvent(PlayerListener.java:175) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8a048fe-71e5248]
        ... 15 more
`

**Comment by MAZUU** [comment]
Update: This bug appears to happen on every Quest NPC now.

**Comment by FlyingPikachu** [comment]
@MAZUU I tested several of your quests and could not replicate the issue. However, I just noticed that several of your "npc-delivery-ids" in your quests.yml are duplicated. Backup your config, remove the duplicate entries and test the errors. For example:

          npc-delivery-ids:
         - 207
          - 207
          - 207

Should be

          npc-delivery-ids:
         - 207

AFTER you've tried that, if you're still getting errors, run this build of Quests which I've just exported for you. This will spit out additional information along with the error. Please reply back with the results. https://dl.dropboxusercontent.com/u/72509980/Quests-2.6.2-343.jar

**Comment by FlyingPikachu** [comment]
@MAZUU Your "custom7" quest is the problem. The quest's name, "Durst." cannot have that period in it. Periods are used to signify a new section of the configuration, so when the code reads that name, it thinks you are trying to place an additional node in the file.

I will have to either disallow periods in names or make the code a little smarter, but for now just remove the period from that quest name (and any others), and you should be golden! :)
