### ISSUE TITLE
NPE on player login

### ISSUE THREAD

**Issue by SullyTheUnusual** [FlyingPikachu/Quests#344]
Doesn't happen on every player, but some players trigger a NPE from Quests when logging in:
````

[19:44:58 WARN]: java.lang.NullPointerException
[19:44:58 WARN]:        at me.blackvein.quests.Quester.getObjectives(Quester.java:530)
[19:44:58 WARN]:        at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:379)
[19:44:58 WARN]:        at me.blackvein.quests.Quester.updateJournal(Quester.java:268)
[19:44:58 WARN]:        at me.blackvein.quests.Quester$4.put(Quester.java:193)
[19:44:58 WARN]:        at me.blackvein.quests.Quester$4.put(Quester.java:186)
[19:44:58 WARN]:        at me.blackvein.quests.Quester.hardDataPut(Quester.java:2565)
[19:44:58 WARN]:        at me.blackvein.quests.Quester.addEmptiesFor(Quester.java:1453)
[19:44:58 WARN]:        at me.blackvein.quests.Quester.loadData(Quester.java:1950)
[19:44:58 WARN]:        at me.blackvein.quests.PlayerListener.onPlayerJoin(PlayerListener.java:645)
[19:44:58 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:44:58 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:44:58 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:44:58 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[19:44:58 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[19:44:58 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:44:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[19:44:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[19:44:58 WARN]:        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346)
[19:44:58 WARN]:        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166)
[19:44:58 WARN]:        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
[19:44:58 WARN]:        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
[19:44:58 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
[19:44:58 WARN]:        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140)
[19:44:58 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842)
[19:44:58 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[19:44:58 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[19:44:58 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[19:44:58 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by FlyingPikachu** [comment]
The error appears to reference code which is for Deliver Item quests. Have you noticed whether any of these players have accepted a particular delivery quest (you can check this in player data under `/Quests/data/{player's UUID}`). It'd be immensely helpful to see which of your quests is causing this.

**Comment by SullyTheUnusual** [comment]
Here's my Quests data folder:

http://loveyland.net/Downloads/QuestData.tar.gz

Let me know if you'd rather have me go through them, I just thought you might find the problem faster.  :)

**Comment by FlyingPikachu** [comment]
Thanks, but without a quests.yml to compare quest names against, there's nothing much I can do with that.

**Comment by SullyTheUnusual** [comment]
Oops, sorry about that.  Try the link again, it should be the entire Quests directory now.

**Comment by FlyingPikachu** [comment]
Sorry I wasn't able to get to finishing this issue. Chances are it has been resolved in recent builds of Quests. If you find that not to be the case, post the error generated by a recent version of Quests and I'll re-open the issue.
