### ISSUE TITLE
Cannot Save Quests

### ISSUE THREAD

**Issue by Fargus5** [FlyingPikachu/Quests#349]
[13:57:22] [Server thread/ERROR]: Error handling conversation prompt
java.lang.NullPointerException
	at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1031) ~[?:?]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1197) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.util.Waitable.run(Waitable.java:24) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

**Comment by FlyingPikachu** [comment]
Which version of Quests are you running?

**Comment by Fargus5** [comment]
Dear,

I'm running the 2.6.4 version

Best regards

**Comment by FlyingPikachu** [comment]
@Fargus5 Thanks. I've tried a few things but cannot replicate the error. Please post your quests.yml for testing.

**Comment by Fargus5** [comment]
Dear,

thanks, you can find it here

http://fargus.altervista.org/Quests.rar


waiting for news
best regards

**Comment by ParadiseRealms** [comment]
Hello Fargus,

I raised a case about this myself, however since then I have found a way around the issue. 

Instead of doing the whole quest in one go, do stages and save each time. For example, set the name of the Quest, the start and finish message; then Save it. Followed by /questadmin reload

Then add the Stages and when done, save it. Followed by /questadmin reload

Then add the rewards, when done, save it. Followed by /questadmin reload 

Then you should be good to go, this worked for me anyway! 

Ben M

**Comment by Fargus5** [comment]
It doesn't work...

I did like you told me... but anyway... basically it must not be the correct way to save a quest.... so there is at the same an error to fix....

At the end, when i put 13 to save, he ask to me if 1 yes or 2 no... I do 1 yes but anything happens.

Could you fix this?

`[20:27:43] [Server thread/ERROR]: Error handling conversation prompt
java.lang.NullPointerException
	at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1031) ~[?:?]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1197) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.util.Waitable.run(Waitable.java:24) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:747) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [minecraft_server-v1.10-SG1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]`

**Comment by ParadiseRealms** [comment]
I'm not anything to do with this plugin, just trying to offer a bit of support. 

At what step does it not let you save? Or if when I'm home I can jump on your server and take a look?

Thanks.

**Comment by Fargus5** [comment]
Dear,

When i finish To made quest And To set everything. . I have To do 13 To Save.The Last Save . But doesn't works.
I told You 

Anyway yes if You want To come in thé server You Can

I come At 18h30 Pm (FRANCE TIME)

if You cannot please To send me a /mail ... I Will ad You in administration And You Will be able To come When You want To See how thé plugin works 

IP: emptyvoid.nitroserv.eu

Please To help me becouse quest i essential for m'y server

**Comment by FlyingPikachu** [comment]
@Fargus5 I ask that you please be more patient. Having me use your server will not do any good.

Just found time to look at the quests.yml from your RAR file, but it is empty. In other words, there is no data (other than the "quests:" string). Maybe you upload the wrong one? Please post a valid file. Thanks!

**Comment by Fargus5** [comment]
Dear

I'm sorry, i didn't understand 
So ok, you can find here the complete plugin:
http://fargus.altervista.org/Quests.rar

and here you can find only the file requested:
http://fargus.altervista.org/quests.yml

I hope that this will help you

**Comment by FlyingPikachu** [comment]
@Fargus5 Even being unable to save quests, that file should not be empty as there are supposed to be example quests. If you are unable to delete the "data" folder, this may be a problem with your OS permissions. What OS are you running (Windows, Mac, Ubuntu, et al.)?

Try deleting your entire Quests folder and restarting the server (do a full restart, no /reload). If that does not populate quests.yml, copy and paste this into it manually and restart - http://pastebin.com/VMFdizB5

**Comment by Fargus5** [comment]
Now it works thanks, i will let you know if there are any problems
