### ISSUE TITLE
Plugin Error on Startup

### ISSUE THREAD

**Issue by LoociM00** [FlyingPikachu/Quests#360]
**What is your Quests version / build number (do _not_ say "latest")?**
3.2.7

**Please describe the problem and how to replicate it. Any console errors?**
`[18:40:53] [Server thread/INFO]: [Quests] Enabling Quests v3.2.7-b284
[18:40:53] [Server thread/ERROR]: Error occurred while enabling Quests v3.2.7-b284 (Is it up to date?)
java.lang.NullPointerException: null
	at me.blackvein.quests.util.Lang.loadLang(Lang.java:141) ~[?:?]
	at me.blackvein.quests.Quests.setupLang(Quests.java:234) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:191) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]`

**Comment by AIphaDragon** [comment]
Perhaps the plugin for the economy is not installed? (Vault)

**Comment by FlyingPikachu** [comment]
@AIphaDragon This has nothing to do with Vault.

@LoociM00 Try moving/deleting your language files and let the plugin generate fresh ones.

**Comment by LoociM00** [comment]
@AlphaDragon Always had Vault - thanks for the help though. :)

@FlyingPikachu Will try that now - thank you!
