### ISSUE TITLE
Wont Load Plugin

### ISSUE THREAD

**Issue by FunkyMoneyMan** [FlyingPikachu/Quests#363]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.7
(__Required__) Please describe the problem and how to replicate it. Any console errors?
There are no console errors
`Could not load 'plugins/Quests-3.2.7.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Vault
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [minecraft_server.jar:git-Spigot-28463de-a2af8f0]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [minecraft_server.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [minecraft_server.jar:git-Spigot-28463de-a2af8f0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [minecraft_server.jar:git-Spigot-28463de-a2af8f0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`
Just when I load the server up
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by FlyingPikachu** [comment]
User did not have the necessary dependency [Vault](https://www.spigotmc.org/resources/vault.34315/) installed.
