### ISSUE TITLE
error on player death

### ISSUE THREAD

**Issue by newbie029** [FlyingPikachu/Quests#369]
Using Paperspigot 1.12.2 latest build

> [16:34:20 ERROR]: Could not pass event PlayerDeathEvent to Quests v3.3.1-b302
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1391]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1391]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1391]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1391]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1391]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:414) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:458) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:979) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:612) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.Explosion.a(Explosion.java:140) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.World.createExplosion(World.java:2041) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.WorldServer.createExplosion(WorldServer.java:1250) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.EntityTNTPrimed.explode(EntityTNTPrimed.java:101) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.EntityTNTPrimed.B_(EntityTNTPrimed.java:81) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1391]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
at me.blackvein.quests.PlayerListener.onPlayerDeath(PlayerListener.java:538) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor856.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1391]
... 23 more
> [16:34:20 INFO]: HelloAurora blew up

**Comment by FlyingPikachu** [comment]
This build should resolve the issue:

http://ci.ac3-servers.eu/job/Quests/305/
