### ISSUE TITLE
Quests sometimes not working to some random players

### ISSUE THREAD

**Issue by Nariko13** [FlyingPikachu/Quests#37]
-Spigot 1.11.2 / QUest 2.8.7

- Well people accept a quest, like delivering something, killing something, telling a password to someone, but when they have to talk back to the quest giver, or after telling the password, well nothing happen ! it just say 'no more quests avaiable' when you click a npc butwhen they to /quest, it's written they still need to do it but with the requirement done, like "bring a diamond_sword to npc : 1/1"
Here is an error who might be related !

[15:31:54] [Async Chat Thread - #97/ERROR]: Could not pass event AsyncPlayerChatEvent to Quests v2.8.7-b134

org.bukkit.event.EventException

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1266) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1204) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Caused by: java.lang.IllegalStateException: Asynchronous entity track!

	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.EntityTracker.addEntity(EntityTracker.java:108) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.EntityTracker.track(EntityTracker.java:90) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.WorldManager.a(WorldManager.java:21) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.World.b(World.java:1089) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.WorldServer.b(WorldServer.java:1112) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.WorldServer.a(WorldServer.java:1077) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.Chunk.addEntities(Chunk.java:753) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.World.getChunkAt(World.java:329) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.World.getChunkAtWorldCoords(World.java:325) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.World.getType(World.java:806) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.BlockBed.b(SourceFile:181) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.BlockBed.a(SourceFile:166) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.EntityHuman.getBed(EntityHuman.java:1367) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.getBedSpawnLocation(CraftPlayer.java:883) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at me.blackvein.quests.Quester.resetCompass(Quester.java:2602) ~[?:?]

	at me.blackvein.quests.Quest.nextStage(Quest.java:89) ~[?:?]

	at me.blackvein.quests.Quester.finishObjective(Quester.java:1094) ~[?:?]

	at me.blackvein.quests.Quester.sayPass(Quester.java:1042) ~[?:?]

	at me.blackvein.quests.PlayerListener.onPlayerChat(PlayerListener.java:302) ~[?:?]

	at sun.reflect.GeneratedMethodAccessor631.invoke(Unknown Source) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	... 11 more

- i can't give you an example quests because it seems to be randomly done, SOme players can do a quest, other cannot, but for an other quest it could be the reverse

Thx for reading, i hope it could be fixed because this is the best quest plugin, really (tested every other)

**Comment by FlyingPikachu** [comment]
My first impression is that this is an issue with Spigot, but I can't be certain. A new version of Quests will be available in the next few days - please hang on til release and we'll take a closer look :)

**Comment by FlyingPikachu** [comment]
@Nariko13 Please give version 2.9.0 a try and if there's still an error, post it (even if it looks similar).

**Comment by Nariko13** [comment]
Ok it works well on most of the quest, people had to quit and retry the quest for this

Until one quest... This quest need you to say a password to someone bug maybe the password is too long ? Cause we put a somehow long password ^^

[16:00:34] [Async Chat Thread - #22/ERROR]: Could not pass event AsyncPlayerChatEvent to Quests v2.9.0-b140

org.bukkit.event.EventException

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1266) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1204) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Caused by: java.lang.IllegalStateException: Asynchronous entity track!

	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.EntityTracker.addEntity(EntityTracker.java:108) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.EntityTracker.track(EntityTracker.java:88) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.WorldManager.a(WorldManager.java:21) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.World.b(World.java:1089) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.WorldServer.b(WorldServer.java:1112) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.WorldServer.a(WorldServer.java:1077) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.Chunk.addEntities(Chunk.java:753) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.World.getChunkAt(World.java:329) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.World.getChunkAtWorldCoords(World.java:325) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.World.getType(World.java:806) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at net.minecraft.server.v1_11_R1.EntityHuman.getBed(EntityHuman.java:1355) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.getBedSpawnLocation(CraftPlayer.java:883) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	at me.blackvein.quests.Quester.resetCompass(Quester.java:2569) ~[?:?]

	at me.blackvein.quests.Quest.nextStage(Quest.java:90) ~[?:?]

	at me.blackvein.quests.Quester.finishObjective(Quester.java:1061) ~[?:?]

	at me.blackvein.quests.Quester.sayPass(Quester.java:1009) ~[?:?]

	at me.blackvein.quests.PlayerListener.onPlayerChat(PlayerListener.java:300) ~[?:?]

	at sun.reflect.GeneratedMethodAccessor384.invoke(Unknown Source) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]

	... 11 more

**Comment by Nariko13** [comment]
Ok some edition now, i have noticed it might be i have clicked one more time on the npc and first time he said like : oh a message for me,? what is is ? 
But if you have the error to make a second click on it, it wrote "no more quest avaiable", but i don't think it causes the problem, cause i couldn't verify it is the source of the problem either (i missed the password and quit direclty the quest xD)

**Comment by FlyingPikachu** [comment]
Closing as Op has claimed to have resolved issue.

For future reference, when Quests must reset the player's compass, the plugin sets it to point to the player's bed spawn location. It appears Spigot is having trouble supplying this location to Quests for some reason.
