### ISSUE TITLE
Many error in console

### ISSUE THREAD

**Issue by Mick43** [FlyingPikachu/Quests#37]
Quests-2.2.4 resolve the spawm error on my localhost server, but not on my real Serveur, the spam error continue, with all files regenerate.

[21:05:31] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v2.2.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:255) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInPosition.a(SourceFile:57) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [?:1.7.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:166) [?:1.7.0]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0]
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:911) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-6ee12f6-33d5de3]
	... 15 more

**Comment by FlyingPikachu** [comment]
Can I get which versions of Java you're running on both your localhost and remote servers?

**Comment by Mick43** [comment]
I use the latest version of java 32 and 64 bit, Version 8 Update 31. But I do not know what version of java using my host, I rent my server at: http://www.omgserv.com/

**Comment by FlyingPikachu** [comment]
I could not find the Java version that they run, so I opened a support ticket. Hopefully we'll hear back soon.

**Comment by Mick43** [comment]
I also opened a ticket, he answered me on used version 7 of java.

**Comment by FlyingPikachu** [comment]
Interesting. Quests runs flawlessly on my test server which runs Java 7. The error did come from the OMGSERV server, correct? Not the Java 8 one?

**Comment by Mick43** [comment]
I did several tests and the error occurs either locally with version 7 Update 75 of Java. The error occurs when a player joins the server, even with "generate-files-on-join: false".

Here's what we suggest OMGSERV in a second ticket:

The crash log indicates that the plugin is compiled with the wrong "source / target". Seeing that there is a GitHub ticket, it would be useful to inform the author of the plugin to change its pom.xml to put the source / target in 1.7

![capture](https://cloud.githubusercontent.com/assets/10450256/6462752/21a3d44e-c1ac-11e4-91aa-caa94e2a9f71.PNG)

**Comment by FlyingPikachu** [comment]
They're close, the issue is actually this: https://gist.github.com/AlainODea/1375759b8720a3f9f094

Unfortunately I can't duplicate the error on my system even with Java 7. I think what I may end up doing is offering 2 different versions of Quests: one for Java 7 and one for Java 8. However, I'm going to try a few other things before I go that route.

**Comment by Mick43** [comment]
Please watch this very short video, it is very easy to reproduce the error locally.

https://www.youtube.com/watch?v=aZc0KJdVtyk

**Comment by FlyingPikachu** [comment]
Thank you for your confirmation video! I am, of course, still stumped as Quests runs on Java 7 for me with no issues (build 1.7.0_72-b14 to be precise). I suppose there could be a difference between build 72 and 75, but if that were the case it should error on Java 8 as well. At this point, I think I'll have to seek outside help. Your video will be very helpful in explaining the issue. Thanks!

**Comment by FlyingPikachu** [comment]
http://www.spigotmc.org/threads/10-solve-this-error.53316/

**Comment by Formula350** [comment]
As per your request, here is the specs for me. I'm using 72 and getitng the errors, too :(

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (amd64) version 3.10.23-xxxx-std-ipv6-64
	Java Version: 1.7.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

**Comment by Mick43** [comment]
To solve the problem, perhaps you could inspire you to version 1.9.0 Beta available here:
http://dev.bukkit.org/bukkit-plugins/quests/files/45-quests-1-9-0-beta/

Because it creates no error in the console of a server Spigot 1.8, errors are occurred since version 2.0.0 ALPHA.

**Comment by Formula350** [comment]
I HAD things fixed previously in build 27, then I went to build 33 or so, and was getting the UUID errors, and to blacklist them. I tried rolling back to build 27 and the issues still remained for some players. Quests in general were having issues now as well, but at least don't cause continual errors.

Going back to Pre 2.0 is possible but would mean all players starting over, which would suck, So as of this point in time that would be a last resort for me.

**Comment by FlyingPikachu** [comment]
Could I get both of you try http://ci.ac3-servers.eu/job/Quests/46/ ?

It's a fix suggested by 1Rouge.
(https://github.com/FlyingPikachu/Quests/commit/33a728dca81ab9886588317490a15f0fbf91043d)

**Comment by Mick43** [comment]
Thank you it works just fine, for against during my test I just realized that an error occurred in the reward money set:
https://github.com/FlyingPikachu/Quests/issues/44
Thank you for your work, I close this ticket.

**Comment by FlyingPikachu** [comment]
Great! Re-opening for a little while to see if @Formula350 can confirm.

**Comment by Formula350** [comment]
I have only gotten around to testing it on the Test server, with only me going on there. HOWEVER!!! There are NO errors when I join, and I was able to complete a quest without issues either :) So I'm quite hopeful that it'll have the same results on my main server!

**Comment by FlyingPikachu** [comment]
Good enough! Thanks, both of you!
