### ISSUE TITLE
Please help me WARN

### ISSUE THREAD

**Issue by McJoker123** [FlyingPikachu/Quests#370]
[15:07:19] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot create section at empty path
[15:07:19] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notEmpty(Validate.java:321)
[15:07:19] [Server thread/WARN]: 	at org.bukkit.configuration.MemorySection.createSection(MemorySection.java:243)
[15:07:19] [Server thread/WARN]: 	at org.bukkit.configuration.MemorySection.createSection(MemorySection.java:270)
[15:07:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester.getBaseData(Quester.java:1660)
[15:07:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester.saveData(Quester.java:1624)
[15:07:19] [Server thread/WARN]: 	at me.blackvein.quests.Quester.takeQuest(Quester.java:435)
[15:07:19] [Server thread/WARN]: 	at me.blackvein.quests.Quests$QuestPrompt.acceptInput(Quests.java:485)
[15:07:19] [Server thread/WARN]: 	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:228)
[15:07:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60)
[15:07:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1114)
[15:07:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1246)
[15:07:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24)
[15:07:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758)
[15:07:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[15:07:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[15:07:19] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[15:07:19] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

Hi, do not tell me that there are errors? my core 1.12.2 spigot new build

Please help me!

**Comment by McJoker123** [comment]
[15:16:45] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v3.3.0-b300
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:417) [citizens-2.0.22-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1580) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: Cannot create section at empty path
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.configuration.MemorySection.createSection(MemorySection.java:243) ~[spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.configuration.MemorySection.createSection(MemorySection.java:270) ~[spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at me.blackvein.quests.Quester.getBaseData(Quester.java:1660) ~[?:?]
	at me.blackvein.quests.Quester.saveData(Quester.java:1624) ~[?:?]
	at me.blackvein.quests.Quest.completeQuest(Quest.java:499) ~[?:?]
	at me.blackvein.quests.Quest.nextStage(Quest.java:116) ~[?:?]
	at me.blackvein.quests.Quester.finishObjective(Quester.java:1228) ~[?:?]
	at me.blackvein.quests.Quester.interactWithNPC(Quester.java:1076) ~[?:?]
	at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:104) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor218.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	... 23 more

+error =(((((((((((((((((((((((((((((((((((((((((((

**Comment by FlyingPikachu** [comment]
One of your quest names in quests.yml is missing or invalid. I'll push a commit which should suppress the errors, but there's nothing more I can do without seeing the file.
