### ISSUE TITLE
Another "quests top" error

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#373]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

3.3.0

(__Required__) Please describe the problem and how to replicate it. Any console errors?

```
[22:48:37] [Server thread/WARN]: java.io.FileNotFoundException: plugins/Quests/data/old (Is a directory)
[22:48:37] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[22:48:37] [Server thread/WARN]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[22:48:37] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[22:48:37] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[22:48:37] [Server thread/WARN]: 	at me.blackvein.quests.Quests.questsTop(Quests.java:1434)
[22:48:37] [Server thread/WARN]: 	at me.blackvein.quests.Quests.questActionsCommandHandler(Quests.java:1355)
[22:48:37] [Server thread/WARN]: 	at me.blackvein.quests.Quests.onCommand(Quests.java:712)
[22:48:37] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:48:37] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:48:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[22:48:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[22:48:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[22:48:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:48:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:48:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:48:37] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:48:37] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:48:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[22:48:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[22:48:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[22:48:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[22:48:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[22:48:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:48:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'quests' in plugin Quests v3.3.0-b300
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-eadd615-4509a14]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-eadd615-4509a14]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[Spigot.jar:git-Spigot-eadd615-4509a14]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [Spigot.jar:git-Spigot-eadd615-4509a14]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [Spigot.jar:git-Spigot-eadd615-4509a14]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-eadd615-4509a14]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-eadd615-4509a14]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-eadd615-4509a14]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-eadd615-4509a14]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-eadd615-4509a14]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-eadd615-4509a14]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-eadd615-4509a14]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-eadd615-4509a14]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_162]
	at me.blackvein.quests.Quests.questsTop(Quests.java:1440) ~[?:?]
	at me.blackvein.quests.Quests.questActionsCommandHandler(Quests.java:1355) ~[?:?]
	at me.blackvein.quests.Quests.onCommand(Quests.java:712) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-eadd615-4509a14]
	... 15 more
```

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
N/A

**Comment by FlyingPikachu** [comment]
I could be mistaken, but do you have a folder named "old" in your Quests/data directory? Might be interfering with the way Quests cycles through files.

**Comment by SXRWahrheit** [comment]
Looks like that was doing it, thanks!
