### ISSUE TITLE
Cannot add more than 1 mob to the spawning list of mobs when creating an Event.

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#38]
Versions:
Spigot 1.11.2
Quests 2.9.0 (build 140)
Also tried for 2.8.4, and 2.8.7 (build 134) same result.

Description of problem & console errors:

I try to create an event where I spawn a few zombies and a skeleton, but I can only add 1 zombie to the list and after that I can't add another mob spawn to the list. See below for the error:
20:58:50 ERROR]: Error handling conversation prompt
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_45-internal]
at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_45-internal]
at me.blackvein.quests.EventFactory$QuestMobPrompt.acceptInput(EventFactory.java:1582) ~[?:?]
at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1058) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1203) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:757) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

My events.yml looks like this:
events:
  ExampleEvent:
    message: <red>Event happened!
    potion-effect-types:
    - Speed
    - Jump
    potion-effect-durations:
    - 100
    - 25
    potion-effect-amplifiers:
    - 3
    - 2
  GoodJob:
    message: <green>Good job!
  DeathFail:
    fail-quest: true
  FishingStart:
    message: <yellow>Type 'rod' in chat to get a fishing rod!
  RodEvent:
    message: <green>Here you go!
    items:
    - name-fishing_rod:amount-1
  SpawnMobs:
    mob-spawns:
      '0':
        spawn-location: world 1514.0 62.0 -310.0
        mob-type: ZOMBIE
        spawn-amounts: 1

**Comment by FlyingPikachu** [comment]
@OwnAgePau Fixed in latest dev build. Thanks!

**Comment by OwnAgePau** [comment]
Thanks, I can finally make the cool quests :)
