### ISSUE TITLE
Could not pass event EntityDeathEvent/PlayerDeathEvent to Quests - EventException: null

### ISSUE THREAD

**Issue by mibby** [FlyingPikachu/Quests#383]
Quests dev 311
http://ci.ac3-servers.eu/job/Quests/311/
Paper dev 1403 (Spigot 1.12.2)

Noticing these errors in console after updating dev builds. I assume it errors when someone kills a mob or dies themselves?
```
[12:22:13] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Quests v3.3.2-b311
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1403]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:396) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1139) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityZombie.die(EntityZombie.java:429) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:979) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.Explosion.a(Explosion.java:140) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.createExplosion(World.java:2041) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.WorldServer.createExplosion(WorldServer.java:1253) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityCreeper.dr(EntityCreeper.java:211) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityCreeper.B_(EntityCreeper.java:116) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1403]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quests.checkQuester(Quests.java:3787) ~[Quests-3.3.2.jar:?]
	at me.blackvein.quests.PlayerListener.killMob(PlayerListener.java:499) ~[Quests-3.3.2.jar:?]
	at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:483) ~[Quests-3.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1052.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1403]
	... 24 more
[12:22:13] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Quests v3.3.2-b311
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1403]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:396) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1139) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityZombie.die(EntityZombie.java:429) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:979) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.Explosion.a(Explosion.java:140) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.createExplosion(World.java:2041) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.WorldServer.createExplosion(WorldServer.java:1253) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityCreeper.dr(EntityCreeper.java:211) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityCreeper.B_(EntityCreeper.java:116) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1403]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quests.checkQuester(Quests.java:3787) ~[Quests-3.3.2.jar:?]
	at me.blackvein.quests.PlayerListener.killMob(PlayerListener.java:499) ~[Quests-3.3.2.jar:?]
	at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:483) ~[Quests-3.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1052.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1403]
	... 24 more
```

---

```
[13:12:19] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Quests v3.3.2-b311
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1403]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:414) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:458) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:979) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:612) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.Explosion.a(Explosion.java:140) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.createExplosion(World.java:2041) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.WorldServer.createExplosion(WorldServer.java:1253) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityCreeper.dr(EntityCreeper.java:211) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityCreeper.B_(EntityCreeper.java:116) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1403]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quests.checkQuester(Quests.java:3787) ~[Quests-3.3.2.jar:?]
	at me.blackvein.quests.PlayerListener.killPlayer(PlayerListener.java:591) ~[Quests-3.3.2.jar:?]
	at me.blackvein.quests.PlayerListener.onPlayerDeath(PlayerListener.java:552) ~[Quests-3.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1067.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1403]
	... 23 more
[13:12:19] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Quests v3.3.2-b311
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1403]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:414) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:458) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:979) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:612) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.Explosion.a(Explosion.java:140) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.createExplosion(World.java:2041) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.WorldServer.createExplosion(WorldServer.java:1253) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityCreeper.dr(EntityCreeper.java:211) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.EntityCreeper.B_(EntityCreeper.java:116) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1403]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quests.checkQuester(Quests.java:3787) ~[Quests-3.3.2.jar:?]
	at me.blackvein.quests.PlayerListener.killMob(PlayerListener.java:499) ~[Quests-3.3.2.jar:?]
	at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:483) ~[Quests-3.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1052.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1403]
	... 23 more
```

**Comment by mibby** [comment]
@FlyingPikachu Possibly related to issue https://github.com/FlyingPikachu/Quests/issues/381? Noticed they didn't post the full error there though.

**Comment by FlyingPikachu** [comment]
Posted the wrong link in my previous comment. Should've been:

http://ci.ac3-servers.eu/job/Quests/312/
