### ISSUE TITLE
Error 3.3.2

### ISSUE THREAD

**Issue by McJoker123** [FlyingPikachu/Quests#398]
[09:03:10] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Quests v3.3.2-b311
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.EntityFireworks.k(EntityFireworks.java:181) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.EntityFireworks.B_(EntityFireworks.java:132) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-61ca7d9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException

**Comment by Pugabyte** [comment]
I'm getting multiple similar errors http://paste.bear-nation.net/eluzo

**Comment by FlyingPikachu** [comment]
Use dev build 312 or greater:

http://ci.ac3-servers.eu/job/Quests/312/
