### ISSUE TITLE
Bug: Can't edit Break Blocks in a stage.

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#43]
Spigot 1.11.2
Quests 2.8.4 (build 130)

When trying to edit a quest, I can not edit Break Blocks.

Quest file:

custom3:
name: Bucket List
npc-giver-id: 16
ask-message: Do you want to help me? I have got some gold if you are interested!
finish-message: Thanks a lot, you helped me a great deal. Here be thy gold!
gui-display: name-BUCKET:amount-1
requirements:
items:
- name-BUCKET:amount-1
remove-items:
- true
fail-requirement-message: You don't have a bucket? Who are you!!
stages:
ordered:
'1':
break-block-names:
- IRON_ORE
break-block-amounts:
- 64
break-block-durability:
- 0
items-to-deliver:
- name-IRON_ORE:amount-64
npc-delivery-ids:
- 16
delivery-messages:
- Thanks!
start-message: I ran out of Iron Ore, can you get me some?
complete-message: Thanks! I can finally start making some more swords, the guards will be please (I hope).
rewards:
money: 10

Error handling conversation prompt
java.lang.ClassCastException: java.lang.Short cannot be cast to java.lang.Integer
at me.blackvein.quests.prompts.CreateStagePrompt$BreakBlockListPrompt.getPromptText(CreateStagePrompt.java:739) ~[?:?]
at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1058) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1203) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.util.Waitable.run(Waitable.java:24) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:757) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by FlyingPikachu** [comment]
Already fixed in version 2.8.6
