### ISSUE TITLE
The error occurs after the player leaves the server with an unfinished quest.

### ISSUE THREAD

**Issue by valenvaio** [FlyingPikachu/Quests#431]
The error occurs after the player leaves the server with an unfinished quest. And relogin the server.
3.3.4 b316
and
3.3.2 b312

```
[20:24:28] [Server thread/ERROR]: [Quests] currentStage was null for 02756a92-c259-32c7-a691-d981c1c114c7 on command
[20:24:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'quests' in plugin Quests v3.3.2-b312
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1437]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1437]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1437]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.jar:git-Paper-1437]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1437]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1437]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1437]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1437]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1437]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1437]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1437]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1437]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1437]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:447) ~[Quests-3.3.2.jar:?]
        at me.blackvein.quests.Quester.updateJournal(Quester.java:269) ~[Quests-3.3.2.jar:?]
        at me.blackvein.quests.Quests.questsJournal(Quests.java:1488) ~[Quests-3.3.2.jar:?]
        at me.blackvein.quests.Quests.questActionsCommandHandler(Quests.java:1295) ~[Quests-3.3.2.jar:?]
        at me.blackvein.quests.Quests.onCommand(Quests.java:687) ~[Quests-3.3.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1437]
        ... 15 more

```

**Comment by FlyingPikachu** [comment]
Likely related to #289 which has been resolved.

Try http://ci.ac3-servers.eu/job/Quests/521/
