### ISSUE TITLE
Version of vault

### ISSUE THREAD

**Issue by Olonto** [FlyingPikachu/Quests#434]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests : 3.3.4-b316
Vault : 1.6.6-b (the lateset)

(__Required__) Please describe the problem and how to replicate it. Any console errors?
I get this error :
`[13:44:10] [Server thread/ERROR]: This error is likely caused by an incompatible version of Vault. Please consider updating.
[13:44:10] [Server thread/WARN]: java.lang.NullPointerException
[13:44:10] [Server thread/WARN]: 	at me.blackvein.quests.util.ItemUtil.getName(ItemUtil.java:217)
[13:44:10] [Server thread/WARN]: 	at me.blackvein.quests.Quester.getObjectives(Quester.java:612)
[13:44:10] [Server thread/WARN]: 	at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:452)
[13:44:10] [Server thread/WARN]: 	at me.blackvein.quests.Quester.takeQuest(Quester.java:416)
[13:44:10] [Server thread/WARN]: 	at me.blackvein.quests.Quests.adminGive(Quests.java:941)
[13:44:10] [Server thread/WARN]: 	at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:702)
[13:44:10] [Server thread/WARN]: 	at me.blackvein.quests.Quests.onCommand(Quests.java:689)
[13:44:10] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:44:10] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[13:44:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676)
[13:44:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425)
[13:44:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230)
[13:44:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:44:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[13:44:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[13:44:10] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:44:10] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:44:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:44:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[13:44:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[13:44:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[13:44:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[13:44:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

Can i know what version of vault i have to use pls ?

**Comment by FlyingPikachu** [comment]
That does not look like an official Vault build. Afaik, there are only "1.6.6" and "1.6.7" version. No "1.6.6-b" version.

Download official development builds here - https://ci.md-5.net/job/Vault/
