### ISSUE TITLE
NPE on reload

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#436]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4-b316

(__Required__) Please describe the problem and how to replicate it. Any console errors?
```
[22:49:21] [Server thread/INFO]: [PLAYERCOMMAND} Wahrheit: [-1357 90 2526] => "/questadmin reload"
[22:49:21] [Server thread/INFO]: [Quests] Loaded language en-US. Translations via Crowdin
[22:49:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.3.4-b316
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quest.updateCompass(Quest.java:192) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quester.checkQuest(Quester.java:2443) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.reloadQuests(Quests.java:2007) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.adminReload(Quests.java:743) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:726) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.onCommand(Quests.java:689) ~[Quests-3.3.4.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	... 15 more

```

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

Can provide upon request, but doesn't appear to be related to config

**Comment by darknesscraft** [comment]
i have this same error on quests reload.

**Comment by SXRWahrheit** [comment]
Any progress here?

```
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.3.4-b316
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quest.updateCompass(Quest.java:192) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quester.checkQuest(Quester.java:2443) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.reloadQuests(Quests.java:2007) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.adminReload(Quests.java:743) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:726) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.onCommand(Quests.java:689) ~[Quests-3.3.4.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	... 15 more

```

**Comment by SXRWahrheit** [comment]
Issue persisting

```
[23:01:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.3.4-b316
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quest.updateCompass(Quest.java:192) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quester.checkQuest(Quester.java:2443) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.reloadQuests(Quests.java:2007) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.adminReload(Quests.java:743) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:726) ~[Quests-3.3.4.jar:?]
	at me.blackvein.quests.Quests.onCommand(Quests.java:689) ~[Quests-3.3.4.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-2086bb0-2f3ed3b]
	... 15 more

```

**Comment by FlyingPikachu** [comment]
Apologies for only getting around to this ticket now. Is this still an issue on Quests 3.4.3?

**Comment by FlyingPikachu** [comment]
Closing. Feel free to request re-open if issue persists (provide error on recent build).
