### ISSUE TITLE
Problem with auto remove/lost quests

### ISSUE THREAD

**Issue by darknesscraft** [FlyingPikachu/Quests#443]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests v3.3.4-b316
i also using version 1.11.2 spigot

(__Required__) Please describe the problem and how to replicate it. Any console errors?

[12:06:54] [Server thread/ERROR]: [Quests] currentStage was null for 1f61694fe-8b36-3caa-aa35-93865e1eb58c on command
[12:06:54] [Server thread/ERROR]: [Quests] currentStage was null for 3261d579e-847a-3806-a8bd-6b818b85dfb5 on command
[12:06:55] [Server thread/ERROR]: [Quests] currentStage was null for cee292e-cceb-32fc-8fc7-9f94ce0032f6 on chat
[12:06:55] [Server thread/ERROR]: [Quests] currentStage was null for cee225fe-cceb-32fc-8fc7-9f94ce0032f6 on chat

or

[12:19:54] [Server thread/INFO]: Player issued server command: /que
[12:19:54] [Server thread/ERROR]: [Quests] currentStage was null for 346356-1622-333e-81c9-e2449dc8de20 on command
[12:19:54] [Server thread/INFO]: Player [3cd51308-1622-333e-81c9-e2449dc8de40]: /que
[12:19:54] [Server thread/ERROR]: [Quests] currentStage was null for 346356-1622-333e-81c9-e2449dc8de20 on command
[12:19:54] [Server thread/WARN]: java.lang.NullPointerException
[12:19:54] [Server thread/WARN]: at me.blackvein.quests.Quests.showObjectives(Quests.java:1842)
[12:19:54] [Server thread/WARN]: at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1682)
[12:19:54] [Server thread/WARN]: at me.blackvein.quests.Quests.onCommand(Quests.java:685)
[12:19:54] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:19:54] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:19:54] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[12:19:54] [Server thread/WARN]: at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:581)
[12:19:54] [Server thread/WARN]: at ch.njol.skript.Skript.dispatchCommand(Skript.java:1131)
[12:19:54] [Server thread/WARN]: at net.dzikoysk.wildskript.effects.EffAsOp.execute(EffAsOp.java:34)
[12:19:54] [Server thread/WARN]: at ch.njol.skript.lang.Effect.run(Effect.java:52)
[12:19:54] [Server thread/WARN]: at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[12:19:54] [Server thread/WARN]: at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[12:19:54] [Server thread/WARN]: at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[12:19:54] [Server thread/WARN]: at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:266)
[12:19:54] [Server thread/WARN]: at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:230)
[12:19:54] [Server thread/WARN]: at ch.njol.skript.command.Commands.handleCommand(Commands.java:253)
[12:19:54] [Server thread/WARN]: at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
[12:19:54] [Server thread/WARN]: at sun.reflect.GeneratedMethodAccessor552.invoke(Unknown Source)
[12:19:54] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:19:54] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[12:19:54] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[12:19:54] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:19:54] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[12:19:54] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[12:19:54] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1336)
[12:19:54] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[12:19:54] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:19:54] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:19:54] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:19:54] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:19:54] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:19:54] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[12:19:54] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[12:19:54] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[12:19:54] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[12:19:54] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[12:19:54] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)

/que is skript that runing /quest command

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
quests:
custom1:
name: TestQuest
npc-giver-id: 921
redo-delay: 86400
...

this is config file:
# See https://github.com/FlyingPikachu/Quests/wiki/Configuration
accept-timeout: 20
allow-command-questing: false
allow-command-quests-with-npcs: false
allow-quitting: false
ask-confirmation: false
generate-files-on-join: true
ignore-locked-quests: false
kill-delay: 600
max-quests: 30
npc-effects:
enabled: true
new-quest: note
redo-quest: angry_villager
show-requirements: true
show-titles: true
translate-subcommands: false
use-compass: true
convert-data-on-startup: false
quester-blacklist:
- UUID
- UUID
- UUID
- UUID

Problem:

Some players on my server lossing quests without any reason, they have access only to /quests command and i dont know why but they randomly lossing access to quests that was already taken or started.

**Comment by FlyingPikachu** [comment]
mcuuid.net says no player with UUID `1f61694fe-8b36-3caa-aa35-93865e1eb58c` exists (from the start of the error you posted).

Seeing as your config contains the 'convert-data-on-startup' config option, it's safe to assume you've updated to 3.3.4 from an older version of Quests. This setting was removed because of the issues related to #343 in which you'll find the solution in the last comment.
