### ISSUE TITLE
Spaming console

### ISSUE THREAD

**Issue by jyrgas** [FlyingPikachu/Quests#46]
This is what i get in my console:
[02:29:02] [Server thread/WARN]: [Quests] Task #22 for Quests v2.0.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:26) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit18.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:668) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]

**Comment by jyrgas** [comment]
i got Bukkit 1.8

**Comment by Leescar** [comment]
Your using quests 2.0.0 
Updating to 2.5.5 should solve your issue.

**Comment by jyrgas** [comment]
I have the new version 2.5.5

**Comment by jyrgas** [comment]
Hm strange i will test it again, but the name of the file is 2.5.5 but in the text it says 2.0 I will test again

**Comment by FlyingPikachu** [comment]
Latest version is 2.2.5.

**Comment by Formula350** [comment]
You may have 2 jar files in your plugins directory, and one may be named something else? Though, when I've had that happen CB (and I would assume, Spigot) have always loaded the newer version. I suppose it's entirely possible that something has happened where BOTH are being loaded.

If you still haven't figured out what's wrong, my steps would be to create a folder in the Plugins directory and name it like DISABLED, and then drag all the JAR files into it. Next, go into the new folder and 1 by 1 move the JARs back into the Plugins directory, paying special attention of the names of each file to make sure everything you're running are what you have intended. Alternatively, instead of copying back all the plugins, just copy back the required few in order to have Quests work as needed (just as a test to make sure it doesn't error). So like Vault, Citizens (and Denizen, Sentry, if needed), and of course the Quests jar. Then you'll know if maybe the "2.5.5" (or 2.2.5 if your post was just a typo) is a mislabeled Quests and it is actually 2.0.0. 

I'd say just delete it and download it again, but the Quests Jenkins seems down currently (for me at least, 502 Bad Gateway error, could be just me...). **EDIT: Just before posted I tried just the as3-servers.eu link and it worked, so I followed it to the jenkins page and now everything is fine. Monday maintenance maybe.** Which on that note... :P FlyingPikachu, perhaps you could have a sub-dir on GitHub that is a repository for the latest builds, to act as a backup/mirror? :D

**Comment by jyrgas** [comment]
Here is the new error code:

Server thread/WARN]: [Quests] Task #22 for Quests v2.2.5 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit18.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:668) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
________________________________________________________

And here are the whole startup sequens:

[18:30:31] [Server thread/INFO]: Starting minecraft server version 1.8
[18:30:31] [Server thread/INFO]: Loading properties
[18:30:31] [Server thread/INFO]: Default game type: SURVIVAL
[18:30:31] [Server thread/INFO]: Generating keypair
[18:30:31] [Server thread/INFO]: Starting Minecraft server on *:25565
[18:30:31] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[18:30:32] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.0.2-SNAPSHOT;3366-2fedcf80
[18:30:32] [Server thread/INFO]: [Essentials] Loading Essentials vTeamCity
[18:30:32] [Server thread/INFO]: [EssentialsProtect] Loading EssentialsProtect vTeamCity
[18:30:32] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat vTeamCity
[18:30:32] [Server thread/INFO]: [GroupManager] Loading GroupManager v2.0 (Dev2.14.98) (Phoenix)
[18:30:32] [Server thread/INFO]: [ClearLag] Loading ClearLag v2.7.7
[18:30:32] [Server thread/INFO]: [EssentialsAntiBuild] Loading EssentialsAntiBuild vTeamCity
[18:30:32] [Server thread/INFO]: [Simple-AutoSave] Loading Simple-AutoSave v0.2.2
[18:30:32] [Server thread/INFO]: [WorldBorder] Loading WorldBorder v1.8.2
[18:30:32] [Server thread/INFO]: [Vault] Loading Vault v1.5.3-b37
[18:30:32] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn vTeamCity
[18:30:32] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v6.0.0-beta-05.1569-
[18:30:32] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.14-SNAPSHOT (build 1195)
[18:30:32] [Server thread/INFO]: [Shopkeepers] Loading Shopkeepers v1.49
[18:30:32] [Server thread/INFO]: [Quests] Loading Quests v2.2.5
[18:30:32] [Server thread/INFO]: [ServerSigns] Loading ServerSigns v3.1.0
[18:30:32] [Server thread/INFO]: [GriefPrevention] Loading GriefPrevention v11.0.1
[18:30:32] [Server thread/INFO]: [Vault] Enabling Vault v1.5.3-b37
[18:30:32] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[18:30:32] [Server thread/INFO]: [Vault] [Permission] GroupManager found: Waiting
[18:30:32] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[18:30:32] [Server thread/INFO]: [Vault] [Chat] GroupManager found: Waiting
[18:30:32] [Server thread/INFO]: [Vault] Enabled Version 1.5.3-b37
[18:30:32] [Server thread/INFO]: Preparing level "world"
[18:30:32] [Server thread/INFO]: Preparing start region for level 0 (Seed: 3875637541840021353)
[18:30:33] [Server thread/INFO]: Preparing spawn area: 0%
[18:30:34] [Server thread/INFO]: Preparing spawn area: 94%
[18:30:34] [Server thread/INFO]: Preparing start region for level 1 (Seed: -848396780138417376)
[18:30:35] [Server thread/INFO]: Preparing start region for level 2 (Seed: 3875637541840021353)
[18:30:35] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.0.2-SNAPSHOT;3366-2fedcf80
[18:30:35] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[18:30:35] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
[18:30:35] [Server thread/INFO]: [Essentials] Enabling Essentials vTeamCity
[18:30:35] [Server thread/INFO]: Bukkit version format changed. Version not checked.
[18:30:35] [Server thread/INFO]: git-Bukkit-33d5de3 (MC: 1.8)
[18:30:35] [Server thread/INFO]: 1.8-R0.1-SNAPSHOT
[18:30:36] [Server thread/INFO]: Using locale sv_SE
[18:30:36] [Server thread/INFO]: Using locale sv_SE
[18:30:36] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.
[18:30:36] [Server thread/INFO]: Essentials: Using config file enhanced permissions.
[18:30:36] [Server thread/INFO]: Permissions listed in as player-commands will be given to all users.
[18:30:36] [Server thread/INFO]: [EssentialsProtect] Enabling EssentialsProtect vTeamCity
[18:30:36] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat vTeamCity
[18:30:36] [Server thread/INFO]: [GroupManager] Enabling GroupManager v2.0 (Dev2.14.98) (Phoenix)
[18:30:36] [Server thread/INFO]: GroupManager - INFO - World Found: world
[18:30:36] [Server thread/INFO]: GroupManager - INFO - Superperms support enabled.
[18:30:36] [Server thread/INFO]: GroupManager - INFO - Scheduled Data Saving is set for every 10 minutes!
[18:30:36] [Server thread/INFO]: GroupManager - INFO - Backups will be retained for 24 hours!
[18:30:36] [Server thread/INFO]: GroupManager version 2.0 (Dev2.14.98) (Phoenix) is enabled!
[18:30:36] [Server thread/INFO]: WEPIF: GroupManager detected! Using GroupManager for permissions.
[18:30:36] [Server thread/INFO]: [Vault][Permission] GroupManager hooked.
[18:30:36] [Server thread/INFO]: [Vault][Chat] GroupManager - Chat hooked.
[18:30:36] [Server thread/INFO]: Essentials: Using GroupManager based permissions.
[18:30:36] [Server thread/INFO]: [ClearLag] Enabling ClearLag v2.7.7
[18:30:36] [Server thread/INFO]: [ClearLag] Loading modules...
[18:30:36] [Server thread/WARN]: [ClearLag] mob-range requires you to use bukkit v1.7_r4 (1.7.10)
[18:30:36] [Server thread/INFO]: [ClearLag] Modules have been loaded!
[18:30:36] [Server thread/INFO]: [ClearLag] Clearlag is now enabled!
[18:30:36] [Thread-8/INFO]: [ClearLag] Checking for updates...
[18:30:36] [Server thread/INFO]: [EssentialsAntiBuild] Enabling EssentialsAntiBuild vTeamCity
[18:30:36] [Server thread/INFO]: [Simple-AutoSave] Enabling Simple-AutoSave v0.2.2
[18:30:36] [Server thread/INFO]: [Simple-AutoSave] [Simple-AutoSave] 0.2.2 enabled.
[18:30:36] [Server thread/INFO]: [Simple-AutoSave] Autosave Started.
[18:30:36] [Server thread/INFO]: [WorldBorder] Enabling WorldBorder v1.8.2
[18:30:36] [Server thread/INFO]: [WorldBorder] [CONFIG] Using elliptic/round border, knockback of 3.0 blocks, and timer delay of 5.
[18:30:36] [Server thread/INFO]: [WorldBorder] [CONFIG] Border-checking timed task started.
[18:30:36] [Server thread/INFO]: [WorldBorder] [CONFIG] World "world" has border radius 6000 at X: -352,5 Z: 1252,5
[18:30:36] [Server thread/INFO]: [WorldBorder] For reference, the main world's spawn location is at X: -354,0 Y: 76,0 Z: 1252,0
[18:30:36] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vTeamCity
[18:30:36] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.0.0-beta-05.1569-
[18:30:36] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[18:30:36] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[18:30:36] [Server thread/INFO]: [WorldGuard] (world) Lava fire is blocked.
[18:30:36] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[18:30:36] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[18:30:36] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[18:30:36] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[18:30:36] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[18:30:36] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[18:30:36] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[18:30:36] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[18:30:36] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[18:30:36] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[18:30:36] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[18:30:36] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[18:30:36] [Server thread/INFO]: [WorldGuard] Loading region data...
[18:30:36] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.14-SNAPSHOT (build 1195)
[18:30:36] [Server thread/ERROR]: [Citizens] Missing preferred location bundle.
[18:30:36] [Server thread/ERROR]: [Citizens] Unable to find Rhino classes - javascript scripts won't see non-CraftBukkit classes
[18:30:37] [Server thread/INFO]: [Shopkeepers] Enabling Shopkeepers v1.49
[18:30:37] [Server thread/ERROR]: Error occurred while enabling Shopkeepers v1.49 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.nisovin.shopkeepers.ShopkeepersPlugin.onEnable(ShopkeepersPlugin.java:303) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit18.jar:git-Bukkit-33d5de3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[18:30:37] [Thread-8/INFO]: [ClearLag] No updates found!
[18:30:37] [Server thread/INFO]: [Quests] Enabling Quests v2.2.5
[18:30:37] [Server thread/INFO]: [Quests] Config not found, writing default to file.
[18:30:37] [Server thread/INFO]: [Quests] Translation data not found, writing defaults to file.
[18:30:37] [Server thread/INFO]: [Quests] Quest data not found, writing defaults to file.
[18:30:37] [Server thread/INFO]: [Quests] Events data not found, writing defaults to file.
[18:30:37] [Server thread/INFO]: [Quests] Data file not found, writing default to file.
[18:30:37] [Server thread/INFO]: [ServerSigns] Enabling ServerSigns v3.1.0
[18:30:37] [Server thread/INFO]: [ServerSigns] Successfully hooked into Vault
[18:30:37] [Server thread/INFO]: [ServerSigns] Version 3.1.0 is now enabled.
[18:30:37] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v11.0.1
[18:30:37] [Server thread/INFO]: GriefPrevention: Grief Prevention boot start.
[18:30:37] [Server thread/INFO]: GriefPrevention: Finished loading configuration.
[18:30:37] [Server thread/INFO]: GriefPrevention: 4 total claims loaded.
[18:30:38] [Server thread/INFO]: GriefPrevention: Customizable messages loaded.
[18:30:38] [Server thread/INFO]: GriefPrevention: Successfully hooked into WorldGuard.
[18:30:38] [Server thread/INFO]: GriefPrevention: Finished loading data (File Mode).
[18:30:38] [Server thread/INFO]: GriefPrevention: Boot finished.
[18:30:38] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:30:38] [Server thread/INFO]: Done (6,326s)! For help, type "help" or "?"
[18:30:38] [Server thread/INFO]: GroupManager - INFO - Bukkit Permissions Updated!
[18:30:38] [pool-3-thread-4/WARN]: Exception in thread "pool-3-thread-4" 
[18:30:38] [pool-3-thread-4/WARN]: org.apache.commons.lang.UnhandledException: Plugin ServerSigns v3.1.0 generated an exception while executing task 24
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at de.czymm.serversigns.Metrics.postPlugin(Metrics.java:335)
	at de.czymm.serversigns.Metrics.access$4(Metrics.java:326)
	at de.czymm.serversigns.Metrics$1.run(Metrics.java:244)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[18:30:38] [Server thread/INFO]: [Citizens] Loaded 5 NPCs.
[18:30:38] [pool-3-thread-3/INFO]: [Vault] Checking for Updates ... 
[18:30:39] [Server thread/INFO]: [Quests] 3 Quest(s) loaded.
[18:30:39] [Server thread/INFO]: [Quests] 5 Event(s) loaded.
[18:30:39] [Server thread/INFO]: [Quests] 827 Phrase(s) loaded.
[18:30:39] [Server thread/WARN]: [Quests] Task #23 for Quests v2.2.5 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at me.blackvein.quests.Quests.getOnlineQuesters(Quests.java:2513) ~[?:?]
	at me.blackvein.quests.Quests$1.run(Quests.java:226) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit18.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:668) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit18.jar:git-Bukkit-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[18:30:39] [pool-3-thread-3/INFO]: [Vault] No new version available
_____________________________________________
After this Quest starts to send those error codes

**Comment by jyrgas** [comment]
before this, i removed the quest jar, and the map, so i have no other quest versions on the server.

**Comment by FlyingPikachu** [comment]
@Formula350 If it can be automated then I'm all for that.

@jyrgas Try updating Spigot.

**Comment by Formula350** [comment]
He's actually using CraftBukkit, not Spigot.

I also have a suspicion that perhaps it is that his NPCs are set to be displayed as an Online Player, but Quests is having a hard time understanding that it isn't ***really*** a player. I've been having issues with Quests and Citizens2 as well, but problem is no error is being reported on mine, and given I've been a bit busy otherwise I just haven't gotten around to making a bug report on it. 

Tis my theory, at least :P

**Comment by jyrgas** [comment]
I have change to spigot and now it works, but almost every quest fails from my 1.7 bukkit server,  but it works at least

**Comment by FlyingPikachu** [comment]
@Formula350 You are correct, my bad. Still, I meant to update to a newer version. As I understood the error, Quests could not call the getOnlinePlayers() method as it did not exist. Since it should exist, I thought perhaps it was an issue with a certain CB/Spigot build. But your explanation seems reasonable, too.

@jyrgas Glad that worked for you! If you need any further assistance, please open a new ticket.
