### ISSUE TITLE
currentStage was null ... on command

### ISSUE THREAD

**Issue by smartmadio** [FlyingPikachu/Quests#463]
**Quests version / build number**
3.3.7-b483
_(old versions also have this problem)_

**Server environment:**
Paper(1418) 1.12.2-R0.1-SNAPSHOT / Java8

**One of the error messages:**
I just accepted a quest from citizen npc and then did nothing:
```
[18:07:44 ERROR]: [Quests] currentStage was null for 2a5a0cf7-2cf9-3c6c-b7ea-649f7329c6a2 on command
[18:07:44 WARN]: java.lang.NullPointerException
[18:07:44 WARN]:        at me.blackvein.quests.Quests.showObjectives(Quests.java:1848)
[18:07:44 WARN]:        at me.blackvein.quests.Quests.questCommandHandler(Quests.java:1688)
[18:07:44 WARN]:        at me.blackvein.quests.Quests.onCommand(Quests.java:691)
[18:07:44 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:07:44 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[18:07:44 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[18:07:44 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
[18:07:44 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
[18:07:44 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:07:44 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[18:07:44 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[18:07:44 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:07:44 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:07:44 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[18:07:44 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[18:07:44 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[18:07:44 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[18:07:44 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[18:07:44 WARN]:        at java.lang.Thread.run(Thread.java:748)
[18:31:31 ERROR]: [Quests] currentStage was null for 2a5a0cf7-2cf9-3c6c-b7ea-649f7329c6a2 on command
```

**And this is 2a5a0cf7-2cf9-3c6c-b7ea-649f7329c6a2's data yml:**
```
currentQuests:
- §6KILLMOB
currentStages:
- 0
quest-points: 0
questData:
  §6KILLMOB:
    mobs-killed:
    - Zombie
    mobs-killed-amounts:
    - 0
completed-Quests:
- §6KILLMOB
- §6KILLMOB2
completedRedoableQuests:
- §6KILLMOB
- §6KILLMOB2
completedQuestTimes:
- 1536487033715
- 1536487538111
amountsCompletedQuests:
- §6KILLMOB
- §6KILLMOB2
amountsCompleted:
- 5
- 6
hasJournal: false
lastKnownName: dazhanshen
```
**This's all of my quest file:**
```
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  custom1:
    name: '&6KILLMOB'
    npc-giver-id: 7
    ask-message: '&7GOGOGO'
    finish-message: '&6GOOD JOB'
    gui-display: name-STICK:amount-1
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 10
    rewards:
      commands:
      - addxp <player> 格斗 6000
    planner:
      cooldown: 180
  custom2:
    name: '&6KILLMOB2'
    npc-giver-id: 7
    ask-message: '&7GOGOGO'
    finish-message: '&6GOOD JOB'
    gui-display: name-IRON_AXE:amount-1
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Enderman
          mob-amounts:
          - 10
    rewards:
      commands:
      - addxp <player> 斧技 6000
    planner:
      cooldown: 180
```

 I'm sure and tested that `addxp <player> 斧技 6000` could be performed correctly in console.

**Comment by FlyingPikachu** [comment]
Hoping to look into this soon.

Note that PaperSpigot is not officially supported.

**Comment by FlyingPikachu** [comment]
The showObjectives() method has been updated in recent commits and _should_ resolve this issue.

Use http://ci.ac3-servers.eu/job/Quests/569/

If you continue to experience a problem, please open a new ticket.
