### ISSUE TITLE
Damage blocks corrupts progress

### ISSUE THREAD

**Issue by Xentax5** [FlyingPikachu/Quests#464]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests (3.3.4-b316)
Server is on version 1.8.8
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Hello,
first i will describe my situation. I have a quest with objective "Damage blocks". It has multiple stages and everything works good. Until player disconnects while having active this objective. Then next time he logs in, Quests starts spamming console with error, that is attached below and he can't do any quests. He can't use /quest (just error message is reported). He can't accept new quests, quit them and so...
Only possible solution is to manually override his quest data in his file (or to delete while file, but he will lose progress then). Questadmin commands also don't work on players with this issue.
Wierd is, that if player moves to stage with this objective, completes it and moves to next stage without logging off, then everything is okay. The issue only appears when he leaves with the objective active.
It doesn't matter which quest is it. Any quest with objective "damage blocks" has this issue.

Here is the error from console.
```
[15:27:00 INFO]: UUID of player MrFlashySvKs is 2113542c-558e-3891-9d7f-a921e7e19161
[15:27:00 ERROR]: Could not pass event PlayerJoinEvent to Quests v3.3.4-b316
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_74]
at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_74]
at me.blackvein.quests.QuestData$1.set(QuestData.java:46) ~[?:?]
at me.blackvein.quests.QuestData$1.set(QuestData.java:40) ~[?:?]
at me.blackvein.quests.Quester.loadData(Quester.java:2060) ~[?:?]
at me.blackvein.quests.PlayerListener.onPlayerJoin(PlayerListener.java:651) ~[?:?]
at sun.reflect.GeneratedMethodAccessor597.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
... 14 more
[15:27:00 INFO]: MrFlashySvKs[/185.152.115.240:49449] logged in with entity id 7189162 at ([Heaven]41.31272411291556, 67.0, 55.36050897494789)
[15:27:00 INFO]: [GAListener] Player: MrFlashySvKs has 1 votes
[15:27:01 WARN]: [Quests] Task #380 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_74]
at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_74]
at me.blackvein.quests.QuestData$1.set(QuestData.java:46) ~[?:?]
at me.blackvein.quests.QuestData$1.set(QuestData.java:40) ~[?:?]
at me.blackvein.quests.Quester.loadData(Quester.java:2060) ~[?:?]
at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[15:27:02 WARN]: [Quests] Task #380 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_74]
at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_74]
at me.blackvein.quests.QuestData$1.set(QuestData.java:46) ~[?:?]
at me.blackvein.quests.QuestData$1.set(QuestData.java:40) ~[?:?]
at me.blackvein.quests.Quester.loadData(Quester.java:2060) ~[?:?]
at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[15:27:03 WARN]: [Quests] Task #380 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_74]
at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_74]
at me.blackvein.quests.QuestData$1.set(QuestData.java:46) ~[?:?]
at me.blackvein.quests.QuestData$1.set(QuestData.java:40) ~[?:?]
at me.blackvein.quests.Quester.loadData(Quester.java:2060) ~[?:?]
at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[15:27:04 WARN]: [Quests] Task #380 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_74]
at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_74]
at me.blackvein.quests.QuestData$1.set(QuestData.java:46) ~[?:?]
at me.blackvein.quests.QuestData$1.set(QuestData.java:40) ~[?:?]
at me.blackvein.quests.Quester.loadData(Quester.java:2060) ~[?:?]
at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[15:27:05 WARN]: [Quests] Task #380 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_74]
at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_74]
at me.blackvein.quests.QuestData$1.set(QuestData.java:46) ~[?:?]
at me.blackvein.quests.QuestData$1.set(QuestData.java:40) ~[?:?]
at me.blackvein.quests.Quester.loadData(Quester.java:2060) ~[?:?]
at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[15:27:06 WARN]: [Quests] Task #380 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_74]
at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_74]
at me.blackvein.quests.QuestData$1.set(QuestData.java:46) ~[?:?]
at me.blackvein.quests.QuestData$1.set(QuestData.java:40) ~[?:?]
at me.blackvein.quests.Quester.loadData(Quester.java:2060) ~[?:?]
at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[15:27:07 WARN]: [Quests] Task #380 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_74]
at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_74]
at me.blackvein.quests.QuestData$1.set(QuestData.java:46) ~[?:?]
at me.blackvein.quests.QuestData$1.set(QuestData.java:40) ~[?:?]
at me.blackvein.quests.Quester.loadData(Quester.java:2060) ~[?:?]
at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[15:27:08 WARN]: [Quests] Task #380 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_74]
at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_74]
at me.blackvein.quests.QuestData$1.set(QuestData.java:46) ~[?:?]
at me.blackvein.quests.QuestData$1.set(QuestData.java:40) ~[?:?]
at me.blackvein.quests.Quester.loadData(Quester.java:2060) ~[?:?]
at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```
The second part of the error starting with ``[Quests] Task #380 for Quests v3.3.4-b316 generated an exception`` just keeps repeating and spamming until player logs out again.
For now I "fixed" this by deleting all stages including this objective. I don't really need this on my server, but i need the whole plugin to work and don't bug player progress. That's the main reason I'm reporting this.
Also I think that you might like to know, that I'm using plugin add-on "MythicMobsQuests.jar". The add-on loads fine and works quite good.

Thank you for your time, Xentax5.

**Comment by FlyingPikachu** [comment]
Looks as though this was related to #289 which was just resolved.

Please try the following dev build and post any new errors. Thanks!
http://ci.ac3-servers.eu/job/Quests/520/
