### ISSUE TITLE
Bug with quests

### ISSUE THREAD

**Issue by zocmoc57** [FlyingPikachu/Quests#465]
at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:09] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:10] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:11] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:12] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:13] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:13] [AntiBotDeluxe#Logger-1/INFO]: AntiBotDeluxe > _GluePowa_/cfad3c2e-0c25-39f8-a9d9-fbaef1cc9fa6 [142.116.218.208] logged in.
[22:02:13] [Server thread/INFO]: [+] _GluePowa_
[22:02:14] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:15] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:16] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:17] [Craft Scheduler Thread - 273/INFO]: [AuthMe] _GluePowa_ used the wrong password
[22:02:17] [Server thread/INFO]: [-] _GluePowa_
[22:02:17] [Server thread/WARN]: handleDisconnection() called twice
[22:02:17] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:18] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:19] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:20] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:02:21] [Server thread/WARN]: [Quests] Task #673447 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_161]
	at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_161]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[?:?]
	at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[?:?]
	at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by FlyingPikachu** [comment]
This should be resolved in recent versions of Quests. Try http://ci.ac3-servers.eu/job/Quests/520/
