### ISSUE TITLE
Magic Integration

### ISSUE THREAD

**Issue by Elxafil** [FlyingPikachu/Quests#469]
Build: # 483

Essentially the integration plugin does not include a plugin.yml
`[22:30:27] [Server thread/ERROR]: Could not load 'plugins/MagicQuests-1.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more`

**Comment by FlyingPikachu** [comment]
This is not an issue with Quests, but the MagicQuests module by NathanWolf. The proper place to request help is here:
https://github.com/elBukkit/MagicQuests
