### ISSUE TITLE
consol error

### ISSUE THREAD

**Issue by kaalitoukka** [FlyingPikachu/Quests#470]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?

(__Required__) Please describe the problem and how to replicate it. Any console errors?

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by kaalitoukka** [comment]
et.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13.1-R0.1-SNAPSHOT-b1916.jar:git-Spigot-6b015b4-94b8708]
16.09 09:12:38 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2140) ~[spigot-1.13.1-R0.1-SNAPSHOT-b1916.jar:git-Spigot-6b015b4-94b8708]
16.09 09:12:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1-R0.1-SNAPSHOT-b1916.jar:git-Spigot-6b015b4-94b8708]
16.09 09:12:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1-R0.1-SNAPSHOT-b1916.jar:git-Spigot-6b015b4-94b8708]
16.09 09:12:38 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1-R0.1-SNAPSHOT-b1916.jar:git-Spigot-6b015b4-94b8708]
16.09 09:12:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1-R0.1-SNAPSHOT-b1916.jar:git-Spigot-6b015b4-94b8708]
16.09 09:12:38 [Server] INFO org.bukkit.event.EventException: null
16.09 09:12:38 [Server] INFO [09:12:38 ERROR]: Could not pass event InventoryClickEvent to Quests v3.3.4-b316

**Comment by kaalitoukka** [comment]
update 1.13.1 plase
