### ISSUE TITLE
Error 1.13.1

### ISSUE THREAD

**Issue by Straiker123** [FlyingPikachu/Quests#475]
I use Quests 3.3.7-b483 on minecraft version 1.13.1
get this error if i looking to npc with quests or teleport to room with NPCs ..

[Quests] Task #32190 for Quests v3.3.7-b483 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_13_R1/entity/CraftPlayer
at me.blackvein.particles.Eff_1_13_R1.sendToPlayer(Eff_1_13_R1.java:119) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:130) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:88) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[18:34:55 WARN]: [Quests] Task #32190 for Quests v3.3.7-b483 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_13_R1/entity/CraftPlayer
at me.blackvein.particles.Eff_1_13_R1.sendToPlayer(Eff_1_13_R1.java:119) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:130) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:88) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[18:34:56 WARN]: [Quests] Task #32190 for Quests v3.3.7-b483 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_13_R1/entity/CraftPlayer
at me.blackvein.particles.Eff_1_13_R1.sendToPlayer(Eff_1_13_R1.java:119) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:130) ~[?:?]
at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:88) ~[?:?]
at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-500ff5d-1cead62]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

**Comment by mercurialmusic** [comment]
Also getting this. Can't do much with the plugin right now. :-/

**Comment by SanyaFox** [comment]
This error can be repeated, if you create quests and there are who did not do quests!

**Comment by FlyingPikachu** [comment]
Try http://ci.ac3-servers.eu/job/Quests/489/
