### ISSUE TITLE
Spamming Error Messages into my Console

### ISSUE THREAD

**Issue by gaRt3n** [FlyingPikachu/Quests#477]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests v3.3.4-b316
Server: git-paper-1500

(__Required__) Please describe the problem and how to replicate it. Any console errors?
```
[19:45:01 WARN]: [Quests] Task #1290 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_181]
        at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_181]
        at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[Quests.jar:?]
        at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[Quests.jar:?]
        at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[Quests.jar:?]
        at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[Quests.jar:?]
        at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[Quests.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[paperclip.jar:git-Paper-1500]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paperclip.jar:git-Paper-1500]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[19:45:01 ERROR]: Could not pass event PlayerMoveEvent to Quests v3.3.4-b316
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[paperclip.jar:git-Paper-1500]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperclip.jar:git-Paper-1500]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperclip.jar:git-Paper-1500]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[paperclip.jar:git-Paper-1500]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:692) ~[paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paperclip.jar:git-Paper-1500]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paperclip.jar:git-Paper-1500]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_181]
        at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_181]
        at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[Quests.jar:?]
        at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[Quests.jar:?]
        at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[Quests.jar:?]
        at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[Quests.jar:?]
        at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:726) ~[Quests.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1080.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[paperclip.jar:git-Paper-1500]
        ... 16 more

```
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://paste.md-5.net/payopemevi.yaml

**Comment by gaRt3n** [comment]
And still... Messages messages messages...

`[20:10:03 WARN]: [Quests] Task #1317 for Quests v3.3.4-b316 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_181]
        at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_181]
        at me.blackvein.quests.QuestData$2.set(QuestData.java:90) ~[Quests.jar:?]
        at me.blackvein.quests.QuestData$2.set(QuestData.java:84) ~[Quests.jar:?]
        at me.blackvein.quests.Quester.loadData(Quester.java:2045) ~[Quests.jar:?]
        at me.blackvein.quests.Quests.getQuester(Quests.java:2025) ~[Quests.jar:?]
        at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:45) ~[Quests.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[paperclip.jar:git-Paper-1500]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [paperclip.jar:git-Paper-1500]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paperclip.jar:git-Paper-1500]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
`

**Comment by FlyingPikachu** [comment]
This issue should be resolved in the latest dev builds, so please try upgrading. If the issue persists, post the new error here. Thanks!
