### ISSUE TITLE
cnoversation could not be held

### ISSUE THREAD

**Issue by neox91120** [FlyingPikachu/Quests#490]
quests 3.3.4
version 1.12.2
sorry in advance for my english im not english :/

i cand o some quests.
but sometimes the conversations stops. its like its invisible. it mainly happens when i do a delivery system and edit the itms delevered.

in console i have :
 Error handling conversation prompt
	at me.blackvein.quests.util.ItemUtil.getName(ItemUtil.java:217) ~[?:?]
	at me.blackvein.quests.prompts.CreateStagePrompt.getPromptText(CreateStagePrompt.java:160) ~[?:?]
	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1068) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1241) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

please i need help
thanks

**Comment by FlyingPikachu** [comment]
What version of Vault are you using?

**Comment by neox91120** [comment]
yeah it was outdated thx
