### ISSUE TITLE
Material Cannot be Null

### ISSUE THREAD

**Issue by nexlemav** [FlyingPikachu/Quests#496]
Quests 3.3.8-b488

[12:21:25 WARN]: [Quests] Task #144 for Quests v3.3.8-b488 generated an exception
java.lang.IllegalArgumentException: Material cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.13.1-R0.1-SNAPSHOT-b1953.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:69) ~[spigot-1.13.1-R0.1-SNAPSHOT-b1953.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:57) ~[spigot-1.13.1-R0.1-SNAPSHOT-b1953.jar:git-Spigot-f6a273b-8ab46ff]
        at me.blackvein.quests.Quests.processStages(Quests.java:2726) ~[?:?]
        at me.blackvein.quests.Quests.loadQuests(Quests.java:2173) ~[?:?]
        at me.blackvein.quests.Quests$1.run(Quests.java:290) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1-R0.1-SNAPSHOT-b1953.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1-R0.1-SNAPSHOT-b1953.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.1-R0.1-SNAPSHOT-b1953.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1-R0.1-SNAPSHOT-b1953.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1-R0.1-SNAPSHOT-b1953.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1-R0.1-SNAPSHOT-b1953.jar:git-Spigot-f6a273b-8ab46ff]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

This all happens on start up.

**Comment by FlyingPikachu** [comment]
Try http://ci.ac3-servers.eu/job/Quests/489/

**Comment by nexlemav** [comment]
Getting this on startup with that build

ERROR]: [Quests] Failed loading lang files for en-US because they were not found. Using default en-US

**Comment by FlyingPikachu** [comment]
Closing under the assumption the original error has been resolved.

Unless you are looking to use a language other than English, your new error can be ignored. If it bothers you, try having the plugin regenerate your lang folder. If that issue persists, please open a new ticket.
