### ISSUE TITLE
"Enter an option" Quest dialog opens everytime an event is triggered

### ISSUE THREAD

**Issue by NadeSwiiv** [FlyingPikachu/Quests#499]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-3.3.4.jar
(__Required__) Please describe the problem and how to replicate it. Any console errors?

The start of my quests work fine and as intended. but once a Teleport or Giveitem event is triggered (by the plugin itself) I get this dialog.
![image](https://user-images.githubusercontent.com/19294814/47587737-30979e80-d964-11e8-9d93-e6e0758e1ba7.png)
 (start dialog of the quest) If you answer no it will simply continiue the quest and nothing is broken. but if you answer "Yes" it will teleport you again or give the Item again, you can keep spamming "Yes" in chat and it will keep teleporting you and keep giving you the item. I can replicate this by adding a Giveitem event or Teleport event to ANY quest. Without an event in the quest (just a basic collect and deliver quest) it will not keep asking me this.

Console errors:
26.10 21:07:35 [Server] WARN [Quests] Plugin Quests v3.3.8-b488 generated an exception whilst handling conversation input
26.10 21:07:35 [Server] INFO java.lang.NoClassDefFoundError: ro/nicuch/citizensbooks/CitizensBooksAPI
26.10 21:07:35 [Server] INFO at me.blackvein.quests.Event.fire(Event.java:255) ~[Quests-3.3.8.jar:?]
26.10 21:07:35 [Server] INFO at me.blackvein.quests.Quester.takeQuest(Quester.java:434) ~[Quests-3.3.8.jar:?]
26.10 21:07:35 [Server] INFO at me.blackvein.quests.Quests$QuestPrompt.acceptInput(Quests.java:478) ~[Quests-3.3.8.jar:?]
26.10 21:07:35 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:228) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
26.10 21:07:35 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
26.10 21:07:35 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1203) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
26.10 21:07:35 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection$2.evaluate(PlayerConnection.java:1493) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
26.10 21:07:35 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.util.Waitable.run(Waitable.java:24) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
26.10 21:07:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:909) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
26.10 21:07:35 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
26.10 21:07:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
26.10 21:07:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
26.10 21:07:35 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/583xaVzn

Thanks in advance for the help!

**Comment by FlyingPikachu** [comment]
Error was the result of a likely typo in #466 

Use this build - http://ci.ac3-servers.eu/job/Quests/490/
