### ISSUE TITLE
Update to 1.8.3

### ISSUE THREAD

**Issue by Mick43** [FlyingPikachu/Quests#50]
Error with the last version http://ci.ac3-servers.eu/job/Quests/51/
Wrong he mentions spigot-1.8-R0.1-SNAPSHOT.jar but it is made in the 1.8.3 version of spigot I rename it.
And runs on Java 7.

[11:30:53] [Server thread/WARN]: [Quests] Task #39 for Quests v2.3.0 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
	at me.blackvein.quests.NpcEffectThread.showEffect_1_8_R1(NpcEffectThread.java:123) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:67) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:43) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[?:1.7.0]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[?:1.7.0]
	... 10 more

**Comment by FlyingPikachu** [comment]
This is because the NMS needs to be updated for Spigot 1.8.3. Will get around to it soon! :)

**Comment by FlyingPikachu** [comment]
Supported as of Quests 2.3.2!
