### ISSUE TITLE
1.13.1 InventoryClickEvent ERROR

### ISSUE THREAD

**Issue by Straiker123** [FlyingPikachu/Quests#503]
Plugin Version: Quests 3.4.0-b491

ERROR:
Could not pass event InventoryClickEvent to Quests v3.4.0-b491
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2142) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NoClassDefFoundError: ro/nicuch/citizensbooks/CitizensBooksAPI
at me.blackvein.quests.Event.fire(Event.java:255) ~[?:?]
at me.blackvein.quests.Quester.takeQuest(Quester.java:457) ~[?:?]
at me.blackvein.quests.PlayerListener.onInventoryClickEvent(PlayerListener.java:150) ~[?:?]
at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
... 15 more
Caused by: java.lang.ClassNotFoundException: ro.nicuch.citizensbooks.CitizensBooksAPI
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
at me.blackvein.quests.Event.fire(Event.java:255) ~[?:?]
at me.blackvein.quests.Quester.takeQuest(Quester.java:457) ~[?:?]
at me.blackvein.quests.PlayerListener.onInventoryClickEvent(PlayerListener.java:150) ~[?:?]
at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]

I got this error after receiving a reward.

**Comment by FlyingPikachu** [comment]
Use dev build 490 or greater - http://ci.ac3-servers.eu/job/Quests/491/

**Comment by Straiker123** [comment]
i have build 491..

**Comment by Straiker123** [comment]
super works no error but there is another problem .. look at the picture

**Comment by Straiker123** [comment]
![2018-11-05_20 02 40](https://user-images.githubusercontent.com/43417249/48020343-000aee00-e136-11e8-8542-9468528a64f7.png)

**Comment by Straiker123** [comment]
it's <green>, <red>, and %s

**Comment by Straiker123** [comment]
and new error...

` Could not pass event InventoryClickEvent to Quests v3.4.0-b492
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2142) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.ACHYCENÍ_RYB
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_152]
at org.bukkit.entity.EntityType.valueOf(EntityType.java:1) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at me.blackvein.quests.Quester.takeQuest(Quester.java:435) ~[?:?]
at me.blackvein.quests.PlayerListener.onInventoryClickEvent(PlayerListener.java:150) ~[?:?]
at sun.reflect.GeneratedMethodAccessor895.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
... 15 more`

**Comment by Straiker123** [comment]
now and now, the error is too much :D
`[Quests] Plugin Quests v3.4.0-b492 generated an exception while executing task 25251
java.lang.NullPointerException: null
at me.blackvein.quests.ObjectiveTimer.run(ObjectiveTimer.java:42) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

**Comment by FlyingPikachu** [comment]
Use this dev build once available - http://ci.ac3-servers.eu/job/Quests/495/
