### ISSUE TITLE
Bug when completing stage 1 it does NOT progress to stage 2. (Could not pass event NPCRightClickEvent to Quests v2.9.0-b140

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#51]
In your issue, please include:

Spigot 1.12 (but it give the same result on 1.11.2)
Quests 2.9.0 (build 140)

The problem is that I can't progress to a second stage after delivering the quest items.
Quest stage 1:

Break 64 iron ore blocks.
Deliver 64 iron ore to Hogard (the quest giver).
Quest stage 2 (never arrives). Gets stuck there.
Quest File Content:

custom3:
name: Bucket List
npc-giver-id: 16
ask-message: Do you want to help me? I have got some gold if you are interested!
finish-message: Thanks a lot, you helped me a great deal. Here be thy gold!
gui-display: name-BUCKET:amount-1
requirements:
items:
- name-BUCKET:amount-1
remove-items:
- true
fail-requirement-message: You don't have a bucket? Who are you!!
stages:
ordered:
'1':
break-block-names:
- IRON_ORE
break-block-amounts:
- 64
break-block-durability:
- 0
items-to-deliver:
- name-IRON_ORE:amount-64
npc-delivery-ids:
- 16
delivery-messages:
- Thanks!
start-message: I ran out of Iron Ore, can you get me some?
complete-message: Thanks! I can finally start making some more swords, the guards will be please (I hope).
'2':
break-block-names:
- GOLD_ORE
- COAL_ORE
break-block-amounts:
- 40
- 32
break-block-durability:
- 1
- 1
items-to-deliver:
- name-COAL:amount-32
- name-GOLD_ORE:amount-40
npc-delivery-ids:
- 16
- 16
delivery-messages:
- OOOOH SOO SHINY!!!
start-message: Hey, can you also get me some gold ore and some coal please?
complete-message: I am so grateful!
'3':
items-to-deliver:
- name-IRON_PICKAXE:amount-1
- name-IRON_PICKAXE:amount-1
- name-IRON_SWORD:amount-1
npc-delivery-ids:
- 18
- 18
- 17
delivery-messages:
- Ooh a brand new tool, finally (my pickaxe was starting to break apart).
- Ah, still no break? Thanks anyways.
- Thanks for the deliveries!
start-message: Our miners down the mine requested me to make them some tools, but I ain't going down that scary dark hole, here you bring it!
complete-message: Thanks, it saved me a dangerous trip down the treacherous paths of the that scary dark place. Ugh.
rewards:
money: 10

Error:
ug when completing stage 1 it does NOT progress to stage 2.
Could not pass event NPCRightClickEvent to Quests v2.9.0-b140
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:414) [citizens-2.0.22-SNAPSHOT.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45-internal]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45-internal]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1568) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
at me.blackvein.quests.Quester.getObjectives(Quester.java:376) ~[?:?]
at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:351) ~[?:?]
at me.blackvein.quests.Quest.setStage(Quest.java:142) ~[?:?]
at me.blackvein.quests.Quest.nextStage(Quest.java:105) ~[?:?]
at me.blackvein.quests.Quester.finishObjective(Quester.java:1126) ~[?:?]
at me.blackvein.quests.Quester.deliverItem(Quester.java:987) ~[?:?]
at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:59) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45-internal]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45-internal]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43
) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
... 24 more

**Comment by OwnAgePau** [comment]
It seems to be related to break blocks. I get the same error when doing doing Break Blocks in another quest.

**Comment by FlyingPikachu** [comment]
@OwnAgePau I was not able to replicate this in a quick test. Please do the following:

- Give the latest dev build a try and post the new error if it persists
- Post the quest using a site like Pastebin.com so it retains formatting

Thanks!

**Comment by OwnAgePau** [comment]
https://pastebin.com/YszdSYHp here is the pastebin of the quest.
Error is still there in v2.9.1-b143

**Comment by FlyingPikachu** [comment]
Thank you, but please post the new error as requested

**Comment by OwnAgePau** [comment]
Could not pass event NPCRightClickEvent to Quests v2.9.2-b146
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:414) [citizens-2.0.22-SNAPSHOT.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45-internal]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45-internal]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-inter
nal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1568) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
at me.blackvein.quests.Quester.getObjectives(Quester.java:376) ~[?:?]
at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:351) ~[?:?]
at me.blackvein.quests.Quest.setStage(Quest.java:142) ~[?:?]
at me.blackvein.quests.Quest.nextStage(Quest.java:105) ~[?:?]
at me.blackvein.quests.Quester.finishObjective(Quester.java:1137) ~[?:?]
at me.blackvein.quests.Quester.deliverItem(Quester.java:987) ~[?:?]
at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:59) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45-internal]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45-internal]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
... 24 more


It looks preeettty much the same.

**Comment by FlyingPikachu** [comment]
This appears to be related to #51 in which a method from Vault returns null.

Please try the build below. I'm quite confident it will solve the issue, but if not, feel free to request re-open.

http://ci.ac3-servers.eu/job/Quests/149/
