### ISSUE TITLE
Enabling but not working 1.13.X

### ISSUE THREAD

**Issue by StormyIceLeopard** [FlyingPikachu/Quests#511]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests Version 3.4.0-b494

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Plugin enables (according to /pl in-game) but nothing works. If you do /quests you get nothing but an insane amount of 'NULL'

[18:59:23] [Server thread/INFO]: [Quests] Enabling Quests v3.4.0-b494
[18:59:23] [Server thread/ERROR]: Error occurred while enabling Quests v3.4.0-b494 (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/nossr50/mcMMO
	at me.blackvein.quests.Quests.linkOtherPlugins(Quests.java:413) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:183) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [Spigot.jar:git-Spigot-2474d93-ca22de3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Spigot.jar:git-Spigot-2474d93-ca22de3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) [Spigot.jar:git-Spigot-2474d93-ca22de3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) [Spigot.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [Spigot.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [Spigot.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [Spigot.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [Spigot.jar:git-Spigot-2474d93-ca22de3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [Spigot.jar:git-Spigot-2474d93-ca22de3]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.mcMMO
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[Spigot.jar:git-Spigot-2474d93-ca22de3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:566) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[?:?]
	... 13 more

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Default .yml files. Deleted the folder to attempt to see if updating was the issue with outdated files.

**Comment by StormyIceLeopard** [comment]
1.6.0-SNAPSHOT

**Comment by FlyingPikachu** [comment]
This line of the error claims that mcMMO's main class file was not found:

`java.lang.NoClassDefFoundError: com/gmail/nossr50/mcMMO`

However, I've just checked mcMMO's Github, and it does indeed exist the latest version:

https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/mcMMO.java

Bottomline, either your server is not loading mcMMO correctly, or it's loading an older version than you think it is (make sure you don't have multiple mcMMO jars in the /plugin folder). Since this is not the fault of Quests, I must close this issue. However, if you'd still like help, feel free to post your server's startup log and I'll point you in the right direction.
