### ISSUE TITLE
Custom reward does not work without a reward name

### ISSUE THREAD

**Issue by arphox** [FlyingPikachu/Quests#53]
Hello!

I found a problem with custom rewards. Please fix it :)

**- Spigot and Quests versions (do not say "latest")**
Spigot version: PaperSpigot-1.12-b1150
Quests version: 2.9.0-b140

**- Description of problem & console errors**
_Problem_: When I try to test my new custom reward, I get an error message and the custom rewards does not apply.
_Console errors_:
```java
[20:58:45 ERROR]: Could not pass event NPCRightClickEvent to Quests v2.9.0-b140
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:414) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor91.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1614) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.Quest.completeQuest(Quest.java:427) ~[?:?]
        at me.blackvein.quests.Quest.nextStage(Quest.java:102) ~[?:?]
        at me.blackvein.quests.Quester.finishObjective(Quester.java:1126) ~[?:?]
        at me.blackvein.quests.Quester.deliverItem(Quester.java:982) ~[?:?]
        at me.blackvein.quests.NpcListener.onNPCRightClick(NpcListener.java:59) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor105.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot-1.12-b1150.jar:git-Paper-1150]
        ... 23 more

```

**- Pastebin an example quest from quests.yml for testing, if applicable**
[quests.yml part](https://pastebin.com/gzFg6sD7)
[my code](https://pastebin.com/rNknumTw)

Link to [Quests.java:427](https://github.com/FlyingPikachu/Quests/blob/master/src/main/java/me/blackvein/quests/Quest.java#L427) to make it easier to check.

**Comment by arphox** [comment]
Also when I try to edit the quest's custom reward, it does not recognize the custom reward's name, like:
**- Custom rewards -
- HighFiveReward**
(I type "HighFiveReward", hit enter, and then the same message comes again in an infinite loop.)

**Comment by arphox** [comment]
I downloaded your code, and tried to find the bug.
If I modify the line 427 to this:
```java
				    if (message == null){
					Bukkit.getLogger().info("message (found.getRewardName()) is null!");
				    }
				    else{
					message = message.replaceAll("%" + ((String) key) + "%", ((String) datamap.get(key)));
				    }
```
The message **is** null (and it gets logged to the console as expected), but (and this is important) the custom reward is handed out, so I can read:
"High five! x10" on the chat. :)

So it seems the problem is with getting the reward's name.

I am trying to get more informations about this bug in your code. :)

**Comment by arphox** [comment]
I managed to find the error:
I forgot to add a name for the reward, so inserting the
`this.setRewardName("This is a reward name.");` line to my code solved the problem.

I still **recommend** you to adding a null check, and if it is null, telling the log to give a reward name.

**Comment by arphox** [comment]
I also recommend you to open the editor for a custom reward again instead of saying "That custom reward has already been added!"

**Comment by FlyingPikachu** [comment]
@arphox Thanks!
