### ISSUE TITLE
Npc effect and quests not working ! 1.13.1

### ISSUE THREAD

**Issue by Straiker123** [FlyingPikachu/Quests#539]
3.4.4 build 511

[Quests] Task #224754 for Quests v3.4.3-b510 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_13_R1/entity/CraftPlayer
	at me.blackvein.particles.Eff_1_13_R1.sendToPlayer(Eff_1_13_R1.java:119) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect_1_13_R1(NpcEffectThread.java:234) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:76) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

Default

**Comment by FlyingPikachu** [comment]
Thanks for continuing this from #528

Fairly certain this build will fix the issue (once available):
http://ci.ac3-servers.eu/job/Quests/513/

**Comment by Straiker123** [comment]
no problem

**Comment by Straiker123** [comment]
and npc quests not working

**Comment by FlyingPikachu** [comment]
Ok, that’s an entirely different issue. There is something wrong with one of the item delivery quests. You’ll have to post your quests.yml _using Pastebin.com_

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Straiker123** [comment]
https://pastebin.com/CNd1nHBU

**Comment by Straiker123** [comment]
ok thanks
