### ISSUE TITLE
Error in v2.3.2

### ISSUE THREAD

**Issue by seema84** [FlyingPikachu/Quests#54]
Spigot 1.8.3
Quests v2.3.2

I get the following error when right-clicking

[Quests] Task #71 for Quests v2.3.2 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
	at me.blackvein.quests.NpcEffectThread.showEffect_1_8_R1(NpcEffectThread.java:246) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:68) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:44) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [craftbukkit.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [craftbukkit.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Spigot-529ff99-2acb9e4]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[craftbukkit.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-529ff99-2acb9e4]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	... 10 more

**Comment by seema84** [comment]
#54 its not for 1.8.3

**Comment by seema84** [comment]
ok the fix in #57 works, thanks

**Comment by FlyingPikachu** [comment]
I was referring to Github ticket 54, which is this ticket. The fix in dev build 57 is included in Quests 2.3.3:
http://www.spigotmc.org/resources/quests.3711/update?update=17128
