### ISSUE TITLE
Version Incompatible

### ISSUE THREAD

**Issue by madsenbassen** [FlyingPikachu/Quests#541]
Version for Quest: Quests version 3.4.3-b508
Version for Citizens: Citizens version 2.0.24-SNAPSHOT (build 1593)

Console error:
[19:48:40] [Server thread/ERROR]: Error occurred while enabling Quests v3.4.3-b508 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensPlugin
	at me.blackvein.quests.Quests.linkOtherPlugins(Quests.java:398) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:183) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Bukkit-162bda9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:331) [craftbukkit.jar:git-Bukkit-162bda9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Bukkit-162bda9]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:413) [craftbukkit.jar:git-Bukkit-162bda9]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339) [craftbukkit.jar:git-Bukkit-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:553) [craftbukkit.jar:git-Bukkit-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:515) [craftbukkit.jar:git-Bukkit-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:414) [craftbukkit.jar:git-Bukkit-162bda9]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:264) [craftbukkit.jar:git-Bukkit-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:664) [craftbukkit.jar:git-Bukkit-162bda9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:130) ~[craftbukkit.jar:git-Bukkit-162bda9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76) ~[craftbukkit.jar:git-Bukkit-162bda9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	... 13 more

**Comment by madsenbassen** [comment]
I have fixed it,

It was Citizens which had disabled because of it didn't support flat 1.13

Thanks for the quick respone though! :)

Den fre. 30. nov. 2018 kl. 20.29 skrev FlyingPikachu <
notifications@github.com>:
