### ISSUE TITLE
InventoryClickEvent

### ISSUE THREAD

**Issue by Straiker123** [FlyingPikachu/Quests#548]
Quests v3.4.4-b515

Could not pass event InventoryClickEvent to Quests v3.4.4-b515
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2142) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
at me.blackvein.quests.Quests.addItem(Quests.java:3765) ~[?:?]
at me.blackvein.quests.Event.fire(Event.java:211) ~[?:?]
at me.blackvein.quests.Quester.takeQuest(Quester.java:465) ~[?:?]
at me.blackvein.quests.PlayerListener.onInventoryClickEvent(PlayerListener.java:150) ~[?:?]
at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]

**Comment by Straiker123** [comment]
Thanks
