### ISSUE TITLE
PlayerQuitEvent Error 1.13.1

### ISSUE THREAD

**Issue by Straiker123** [FlyingPikachu/Quests#559]
3.4.6 b525

Could not pass event PlayerQuitEvent to Quests v3.4.6-b525
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:404) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1356) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:327) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:144) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
at me.blackvein.quests.PlayerListener.onPlayerQuit(PlayerListener.java:704) ~[?:?]
at sun.reflect.GeneratedMethodAccessor1524.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[minecraft_server.jar:git-Spigot-f6a273b-a639ae4]
... 12 more

**Comment by FlyingPikachu** [comment]
Use this build once available - http://ci.ac3-servers.eu/job/Quests/532/
