### ISSUE TITLE
Thermos server crash error

### ISSUE THREAD

**Issue by DwarfyAssassin** [FlyingPikachu/Quests#569]
Quest version: v3.5.0
Thermos version: 1.7.10-1614

I am using a [thermos server](https://cyberdynecc.github.io/Thermos/index) and the plugin errors on startup. This doesn't happen when I used v3.4.5 so it seems related to the latest update. I also tested it on a normal 1.7.10 spigot version and I get the same error on startup. (not the exact same because the #10 was a #5 but the but the rest was the same)

This is the error:
```
[20:52:39] [Server thread/WARN]: [Quests] Task #10 for Quests v3.5.0-b${env.BUILD_NUMBER} generated an exception
java.lang.NoClassDefFoundError: org/bukkit/inventory/ItemFlag
	at me.blackvein.quests.util.ItemUtil.readItemStack(ItemUtil.java:155) ~[?:?]
	at me.blackvein.quests.Quests.loadQuestRequirements(Quests.java:2349) ~[?:?]
	at me.blackvein.quests.Quests.loadQuests(Quests.java:2181) ~[?:?]
	at me.blackvein.quests.Quests$1.run(Quests.java:299) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.ItemFlag
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:440) ~[PluginClassLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.58]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	... 11 more
```

I have also added the complete server log.
[latest(1).log](https://github.com/FlyingPikachu/Quests/files/2669170/latest.1.log)

**Comment by FlyingPikachu** [comment]
Thanks for bringing this to my attention. Use the build I just released on Spigot - Quests 3.5.1
