### ISSUE TITLE
Again Delay - now it's generating exception v3.5.4 !

### ISSUE THREAD

**Issue by omatix** [FlyingPikachu/Quests#578]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.5.4-b565
(__Required__) Please describe the problem and how to replicate it. Any console errors?
`[12:55:52 WARN]: [Quests] Task #26925 for Quests v3.5.4-b565 generated an exception
java.lang.NullPointerException: null
        at me.blackvein.quests.StageTimer.run(StageTimer.java:68) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
`        '3':
          place-block-names:
          - SAPLING
          place-block-amounts:
          - 6
          place-block-durability:
          - 0
          delay: 25
          delay-message: DIALOG...
          objective-override: DIALOG.
          start-message: DIALOG
          complete-message: DIALOG...`

**Comment by FlyingPikachu** [comment]
Please use Pastebin to post your example quest, per the instructions. I’ll need the full quest, not just that 3rd stage.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FlyingPikachu** [comment]
Fixed in this build:
http://ci.ac3-servers.eu/job/Quests/567/
