### ISSUE TITLE
Peoples can't take quest at a citizen

### ISSUE THREAD

**Issue by Musicalink** [FlyingPikachu/Quests#583]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.5.1

(__Required__) Please describe the problem and how to replicate it. Any console errors?

When peoples try to take a quest at a Citizen, there is an error and they need to disconnect reconnect.

[14:07:21 WARN]: java.lang.NullPointerException
[14:07:21 WARN]:        at me.blackvein.quests.Quester.takeQuest(Quester.java:317)
[14:07:21 WARN]:        at me.blackvein.quests.Quests$QuestPrompt.acceptInput(Quests.java:491)
[14:07:21 WARN]:        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:228)
[14:07:21 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.conversations.ConversationTracker.acceptConversationInpu
t(ConversationTracker.java:60)
[14:07:21 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.j
ava:1203)
[14:07:21 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection$2.evaluate(PlayerConnection.java:1497)
[14:07:21 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.util.Waitable.run(Waitable.java:24)
[14:07:21 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:913)
[14:07:21 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[14:07:21 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[14:07:21 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[14:07:21 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by FlyingPikachu** [comment]
Please check if the latest dev build resolves the issue:
http://ci.ac3-servers.eu/job/Quests/

**Comment by FlyingPikachu** [comment]
Haven't been able to replicate on latest dev build. Feel free to post new information if the issue persists.
