### ISSUE TITLE
I can't set Deliver Items/ MythicItems NPC Deliver Objective by error

### ISSUE THREAD

**Issue by Nerwo** [FlyingPikachu/Quests#584]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
**3.5.1(on 3.5.5 not working)**

(__Required__) Please describe the problem and how to replicate it. Any console errors?
**I can't set any items in option Deliver Items/MythicItem NPC Deliver Objective and normal items for example from gamemode 1 ...**

Error:  https://pastebin.com/f9XRkkCj

or

`[13:51:05 WARN]: [com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2] Failed to convert NBTTagList
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTBase.b_()Ljava/lang/String;
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:437) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNativeList(Spigot_v1_13_R2.java:463) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:427) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:66) ~[?:?]
        at com.boydti.fawe.bukkit.v0.BukkitQueue_0.toNative(BukkitQueue_0.java:179) ~[?:?]
        at com.boydti.fawe.bukkit.util.ItemUtil.getNBT(ItemUtil.java:71) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitItemStack.getNbtData(BukkitItemStack.java:63) ~[?:?]
        at com.boydti.fawe.util.BrushCache.getTool(BrushCache.java:41) ~[?:?]
        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:961) ~[?:?]
        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:956) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handleBlockInteract(PlatformManager.java:382) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) ~[?:?]
        at com.sk89q.worldedit.WorldEdit.handleBlockRightClick(WorldEdit.java:544) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:153) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-476]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-476]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-476]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-476]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1397) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-476]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-476]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[13:51:05 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagInt.e()I
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:422)
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410)
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410)
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:66)
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.v0.BukkitQueue_0.toNative(BukkitQueue_0.java:179)
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.util.ItemUtil.getNBT(ItemUtil.java:71)
[13:51:05 WARN]:        at com.sk89q.worldedit.bukkit.BukkitItemStack.getNbtData(BukkitItemStack.java:63)
[13:51:05 WARN]:        at com.boydti.fawe.util.BrushCache.getTool(BrushCache.java:41)
[13:51:05 WARN]:        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:961)
[13:51:05 WARN]:        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:956)
[13:51:05 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager.handleBlockInteract(PlatformManager.java:382)
[13:51:05 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:51:05 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:51:05 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:51:05 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:51:05 WARN]:        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[13:51:05 WARN]:        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[13:51:05 WARN]:        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
[13:51:05 WARN]:        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
[13:51:05 WARN]:        at com.sk89q.worldedit.WorldEdit.handleBlockRightClick(WorldEdit.java:544)
[13:51:05 WARN]:        at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:153)
[13:51:05 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source)
[13:51:05 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[13:51:05 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:51:05 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:51:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[13:51:05 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1397)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[13:51:05 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:51:05 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[13:51:05 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:51:05 WARN]: [com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2] Failed to convert NBTTagList
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTBase.b_()Ljava/lang/String;
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:437) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNativeList(Spigot_v1_13_R2.java:463) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:427) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:66) ~[?:?]
        at com.boydti.fawe.bukkit.v0.BukkitQueue_0.toNative(BukkitQueue_0.java:179) ~[?:?]
        at com.boydti.fawe.bukkit.util.ItemUtil.getNBT(ItemUtil.java:71) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitItemStack.getNbtData(BukkitItemStack.java:63) ~[?:?]
        at com.boydti.fawe.util.BrushCache.getTool(BrushCache.java:41) ~[?:?]
        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:961) ~[?:?]
        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:956) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:494) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) ~[?:?]
        at com.sk89q.worldedit.WorldEdit.handleRightClick(WorldEdit.java:531) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:157) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-476]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-476]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-476]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-476]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1397) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-476]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-476]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-476]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[13:51:05 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagInt.e()I
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:422)
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410)
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410)
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:66)
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.v0.BukkitQueue_0.toNative(BukkitQueue_0.java:179)
[13:51:05 WARN]:        at com.boydti.fawe.bukkit.util.ItemUtil.getNBT(ItemUtil.java:71)
[13:51:05 WARN]:        at com.sk89q.worldedit.bukkit.BukkitItemStack.getNbtData(BukkitItemStack.java:63)
[13:51:05 WARN]:        at com.boydti.fawe.util.BrushCache.getTool(BrushCache.java:41)
[13:51:05 WARN]:        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:961)
[13:51:05 WARN]:        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:956)
[13:51:05 WARN]:        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:494)
[13:51:05 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:51:05 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:51:05 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:51:05 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:51:05 WARN]:        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[13:51:05 WARN]:        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[13:51:05 WARN]:        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
[13:51:05 WARN]:        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
[13:51:05 WARN]:        at com.sk89q.worldedit.WorldEdit.handleRightClick(WorldEdit.java:531)
[13:51:05 WARN]:        at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:157)
[13:51:05 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source)
[13:51:05 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[13:51:05 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:51:05 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:51:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[13:51:05 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1397)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[13:51:05 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:51:05 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[13:51:05 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[13:51:05 WARN]:        at java.lang.Thread.run(Unknown Source)`

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
**I can't because error makes it impossible.**

**Comment by FlyingPikachu** [comment]
This is an issue with WorldEdit. Seek help from that plugin’s developer or perhaps try updating WorldEdit.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
