### ISSUE TITLE
error after dying for TNT

### ISSUE THREAD

**Issue by LogikozRC** [FlyingPikachu/Quests#590]
Error killing me with a TnT during a MobArena game.

**OBS: I was not with any QUEST in progress.**

https://i.imgur.com/lcaTQar.png

```
`[17:31:02] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Quests v3.5.1-b${env.BUILD_NUMBER}
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:425) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:822) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.Explosion.a(Explosion.java:138) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.World.createExplosion(World.java:1910) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.WorldServer.createExplosion(WorldServer.java:1053) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityTNTPrimed.explode(EntityTNTPrimed.java:116) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityTNTPrimed.t_(EntityTNTPrimed.java:87) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1644) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1611) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1448) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
	at me.blackvein.quests.PlayerListener.killPlayer(PlayerListener.java:600) ~[?:?]
	at me.blackvein.quests.PlayerListener.onPlayerDeath(PlayerListener.java:547) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	... 23 more`
```

**Comment by FlyingPikachu** [comment]
Thanks for the report. Please update to the build that was released on Spigot today. If that doesn't resolve the issue, post the error generated by that build.

**Comment by FlyingPikachu** [comment]
Unable to replicate on latest dev builds. Feel free to post the requested information if issue persists.
