### ISSUE TITLE
Upon adding a Break Block to a stage it creates wrong data in the file, not saving the quests properly.

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#62]
Spigot 1.12 (but it give the same result on 1.11.2)
Quests 2.9.0 (build 140)

When creating a quest with a stage in which you have to break blocks, it creates the wrong data in the file even though I have set the block break durability in the quests menu, it still comes out wrong.
It generated the quest like this : https://pastebin.com/PsVBMwQD
After going into the file and adjusting the break-block section to
          break-block-durability:
          - 0
It works just fine.

Which when trying to do a /questsadmin reload gives the following error: 

null
org.bukkit.command.CommandException: Unhandled exception executing command 'questsadmin' in plugin Quests v2.9.2-b146
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_45-internal]
at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_45-internal]
at me.blackvein.quests.Quests.processStages(Quests.java:2536) ~[?:?]
at me.blackvein.quests.Quests.loadQuests(Quests.java:2093) ~[?:?]
at me.blackvein.quests.Quests.reloadQuests(Quests.java:1915) ~[?:?]
at me.blackvein.quests.Quests.adminReload(Quests.java:660) ~[?:?]
at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:615) ~[?:?]
at me.blackvein.quests.Quests.onCommand(Quests.java:604) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
... 15 more

**Comment by FlyingPikachu** [comment]
When you created the quest, did you set a durability for the item, or leave the field blank?

**Comment by OwnAgePau** [comment]
I did, just like I sayd "even though I have set the block break durability in the quests menu".

**Comment by FlyingPikachu** [comment]
Fixed in http://ci.ac3-servers.eu/job/Quests/147/
