### ISSUE TITLE
Getting console error spam when players move.

### ISSUE THREAD

**Issue by dawm** [FlyingPikachu/Quests#64]
>[11:37:30] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v2.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:265) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PacketPlayInFlying.a(SourceFile:126) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_76]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_76]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/World
	at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:122) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.java:128) ~[?:?]
	at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:902) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.World
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_76]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_76]
	at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:122) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.java:128) ~[?:?]
	at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:902) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	... 15 more
[11:37:31] [Server thread/WARN]: [Quests] Task #36 for Quests v2.3.4 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/World
	at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:122) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.java:128) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:40) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.World
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-61ef214]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_76]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_76]
	... 10 more

**Comment by FlyingPikachu** [comment]
What is your Citizens version?

**Comment by dawm** [comment]
That I did not update.. doh. yeah I updated to your lastest version but didnt even think about citizens.
I was using citizens-2.0.14-SNAPSHOT#1212

**Comment by FlyingPikachu** [comment]
Closing as Citizens build was not compatible with Spigot 1.8.3. Thanks!
