### ISSUE TITLE
Java errors on quest 3.6.0 B-13 (location reached principaly)

### ISSUE THREAD

**Issue by tiradorus** [FlyingPikachu/Quests#646]
**What is your Quests version / build number (do _not_ say "latest")?**

 Quests 3.6.0-b613
Minecraft 1.8.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Tons of java errors, i'll post it here, so you can know where to fix some bugs:

#1:
```
[16:25:01] [Server thread/INFO]: [BungeePerms] Login by Iscale (1fd89b29-b369-422c-8e8b-ec1f7fc8b4df)
[16:25:01] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Quests v3.6.0-b613
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_181]
	at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_181]
	at me.blackvein.quests.Quester.getObjectives(Quester.java:761) ~[?:?]
	at me.blackvein.quests.Quester.updateJournal(Quester.java:355) ~[?:?]
	at me.blackvein.quests.QuestData$17.add(QuestData.java:877) ~[?:?]
	at me.blackvein.quests.QuestData$17.add(QuestData.java:869) ~[?:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2399) ~[?:?]
	at me.blackvein.quests.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:686) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	... 14 more
```

#2:
```
[16:25:18] [Server thread/ERROR]: [Quests] An error has occurred with Quests. Please report on Github. Include the info below
[16:25:18] [Server thread/ERROR]: [Quests] index = 0
[16:25:18] [Server thread/ERROR]: [Quests] locationsReached = [Location{world=CraftWorld{name=world},x=514.0,y=195.0,z=97.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=526.0,y=195.0,z=104.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=514.0,y=194.0,z=106.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=506.0,y=195.0,z=119.0,pitch=0.0,yaw=0.0}]
[16:25:18] [Server thread/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[16:25:18] [Server thread/WARN]: 	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
[16:25:18] [Server thread/WARN]: 	at java.util.LinkedList.get(LinkedList.java:476)
[16:25:18] [Server thread/WARN]: 	at me.blackvein.quests.Quester.reachLocation(Quester.java:1267)
[16:25:18] [Server thread/WARN]: 	at me.blackvein.quests.listeners.PlayerListener.onPlayerMove(PlayerListener.java:775)
[16:25:18] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
[16:25:18] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:25:18] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:25:18] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:25:18] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:25:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:25:18] [Server thread/ERROR]: [Quests] An error has occurred with Quests. Please report on Github. Include the info below
[16:25:18] [Server thread/ERROR]: [Quests] index = 1
[16:25:18] [Server thread/ERROR]: [Quests] locationsReached = [Location{world=CraftWorld{name=world},x=514.0,y=195.0,z=97.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=526.0,y=195.0,z=104.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=514.0,y=194.0,z=106.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=506.0,y=195.0,z=119.0,pitch=0.0,yaw=0.0}]
[16:25:18] [Server thread/WARN]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
[16:25:18] [Server thread/WARN]: 	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
[16:25:18] [Server thread/WARN]: 	at java.util.LinkedList.get(LinkedList.java:476)
[16:25:18] [Server thread/WARN]: 	at me.blackvein.quests.Quester.reachLocation(Quester.java:1267)
[16:25:18] [Server thread/WARN]: 	at me.blackvein.quests.listeners.PlayerListener.onPlayerMove(PlayerListener.java:775)
[16:25:18] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
[16:25:18] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:25:18] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:25:18] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:25:18] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:25:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:25:18] [Server thread/ERROR]: [Quests] An error has occurred with Quests. Please report on Github. Include the info below
[16:25:18] [Server thread/ERROR]: [Quests] index = 2
[16:25:18] [Server thread/ERROR]: [Quests] locationsReached = [Location{world=CraftWorld{name=world},x=514.0,y=195.0,z=97.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=526.0,y=195.0,z=104.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=514.0,y=194.0,z=106.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=506.0,y=195.0,z=119.0,pitch=0.0,yaw=0.0}]
[16:25:18] [Server thread/WARN]: java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
[16:25:18] [Server thread/WARN]: 	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
[16:25:18] [Server thread/WARN]: 	at java.util.LinkedList.get(LinkedList.java:476)
[16:25:18] [Server thread/WARN]: 	at me.blackvein.quests.Quester.reachLocation(Quester.java:1267)
[16:25:18] [Server thread/WARN]: 	at me.blackvein.quests.listeners.PlayerListener.onPlayerMove(PlayerListener.java:775)
[16:25:18] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
[16:25:18] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:25:18] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:25:18] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:25:18] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:25:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:25:18] [Server thread/ERROR]: [Quests] An error has occurred with Quests. Please report on Github. Include the info below
[16:25:18] [Server thread/ERROR]: [Quests] index = 3
[16:25:18] [Server thread/ERROR]: [Quests] locationsReached = [Location{world=CraftWorld{name=world},x=514.0,y=195.0,z=97.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=526.0,y=195.0,z=104.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=514.0,y=194.0,z=106.0,pitch=0.0,yaw=0.0}, Location{world=CraftWorld{name=world},x=506.0,y=195.0,z=119.0,pitch=0.0,yaw=0.0}]
[16:25:18] [Server thread/WARN]: java.lang.IndexOutOfBoundsException: Index: 3, Size: 0
[16:25:18] [Server thread/WARN]: 	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
[16:25:18] [Server thread/WARN]: 	at java.util.LinkedList.get(LinkedList.java:476)
[16:25:18] [Server thread/WARN]: 	at me.blackvein.quests.Quester.reachLocation(Quester.java:1267)
[16:25:18] [Server thread/WARN]: 	at me.blackvein.quests.listeners.PlayerListener.onPlayerMove(PlayerListener.java:775)
[16:25:18] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
[16:25:18] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:25:18] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:25:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:25:18] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:25:18] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:25:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:25:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

#3:
```
[22:14:46] [Server thread/ERROR]: [Quests] An error has occurred with Quests. Please report on Github. Include the info below
[22:14:46] [Server thread/ERROR]: [Quests] index = -1
[22:14:46] [Server thread/ERROR]: [Quests] locationsReached = []
[22:14:46] [Server thread/WARN]: java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
[22:14:46] [Server thread/WARN]: 	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
[22:14:46] [Server thread/WARN]: 	at java.util.LinkedList.get(LinkedList.java:476)
[22:14:46] [Server thread/WARN]: 	at me.blackvein.quests.Quester.reachLocation(Quester.java:1266)
[22:14:46] [Server thread/WARN]: 	at me.blackvein.quests.listeners.PlayerListener.onPlayerMove(PlayerListener.java:775)
[22:14:46] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
[22:14:46] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:14:46] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:14:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[22:14:46] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:14:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[22:14:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[22:14:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)
[22:14:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)
[22:14:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[22:14:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[22:14:46] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:14:46] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:14:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[22:14:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[22:14:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[22:14:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[22:14:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[22:14:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

```
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

And here is one of the bugged quest.
Ths quest wasn't bugged into my olf version of quest, 3.2.7.

```
  custom27:
    name: Des choses anormales se préparent
    npc-giver-id: 47
    ask-message: '§bDémontre ta confiance au prince en §bservant contre les §eelfes
      noirs §f[§cRewards: §a+600 Money§f, §9+2450 §9Exp, §dQuêtes§f]'
    finish-message: §e** §b+2450 §9Expérience §e**
    gui-display: name-ARROW:amount-1
    requirements:
      quests:
      - La trame principale
      fail-requirement-message: Nope
    stages:
      ordered:
        '1':
          locations-to-reach:
          - world 503.0 192.0 65.0
          reach-location-radii:
          - 4
          reach-location-names:
          - Sortie du pont SUD
          start-message: '&eAlderian: &bSalutation étranger, si tu es ici c''est que
            &eEvely &bt''as laissé passé et a considéré que tu étais digne de confiance.
            Je vais mettre cette confiance à l''epreuve! Il y a peu nous avons remarqué
            des activitées anormales du côté des &eelfes noirs&b, sur les &eîles adjacentes&b.
            Allez voir ce qu''il se passe et faites un rapport sur la situation extérieure.'
          complete-message: '&f[&aObjective-Quest&f]: &ePoursuivre les recherches
            en travsersant le pont.'
        '2':
          locations-to-reach:
          - world 503.0 195.0 90.0
          reach-location-radii:
          - 4
          reach-location-names:
          - Traversée du pont
          complete-message: '&f[&aObjective-Quest&f]: &eEssayez de comprendre ce qu''il
            se trame par ici. Inspectez les lieux'
        '3':
          locations-to-reach:
          - world 514.0 195.0 97.0
          - world 526.0 195.0 104.0
          - world 514.0 194.0 106.0
          - world 506.0 195.0 119.0
          reach-location-radii:
          - 3
          - 3
          - 2
          - 3
          reach-location-names:
          - Tour
          - Pont du château
          - Arrière de la tour de construction
          - Avant de la charette
          complete-message: '&f[&aObjective-Quest&f]: &eVous avez assez d''éléments,
            rentrez faire votre rapport à &eAlderian&b.'
        '4':
          npc-ids-to-talk-to:
          - 47
          objective-override: '§cAllez parler à §6§Alderian §cen §6[§d470,193,3§6]'
          complete-message: '&eAlderian: &bIntéréssant, les &cElfes noirs &bont l''air
            de s''intérésser au cristal, je ne sais pas ce qu''ils préparent mais
            ce n''a rien de bon. Surtout que si ils le retirent, l''île toute entière
            tombera.'
    rewards:
      money: 600
      commands:
      - class exp <player> 2450
```

Ps: i can't use version B-17 c'ause MythicMobs extension isn't compatible with, i have to deal with the B13

**Comment by FlyingPikachu** [comment]
Thanks for your report! Please post the contents of the following file from your plugins directory:

/Quests/data/1fd89b29-b369-422c-8e8b-ec1f7fc8b4df.yml

**Comment by tiradorus** [comment]
Here we have:

```
currentQuests:
- Des choses anormales se préparent
- Une île ravagée
- Retour de mission
- Aide au ravitaillement
currentStages:
- 2
- 0
- 1
- 0
quest-points: 450
questData:
  Des choses anormales se préparent:
    locations-to-reach:
    - world 514.0 195.0 97.0
    - world 526.0 195.0 104.0
    - world 514.0 194.0 106.0
    - world 506.0 195.0 119.0
    has-reached-location:
    - true
    radii-to-reach-within: []
  Une île ravagée:
    citizen-ids-to-talk-to:
    - 25
    has-talked-to:
    - true
  Retour de mission:
    citizen-ids-to-talk-to:
    - 4
    has-talked-to:
    - false
  Aide au ravitaillement:
    locations-to-reach:
    - world 562.0 178.0 41.0
    has-reached-location:
    - false
    radii-to-reach-within:
    - 4
completed-Quests:
- Histoire de l'île
- Les chevaliers corrompus
- Les panthères sauvages
- La grande infection
- Les zombifiacs distordus
- Les brasieros enflammés
- En route!
- Attaqué par les gobelins
- En manque de nourriture
- Une lettre à remettre
- Au coeur de la forêt
- Les sorciers déchus
- Une rencontre Féerique
- Des esclaves et des gobelins
- Des orcs à la chaîne
- L'aventure se poursuit
- Le recensement
- Nettoyage de zone 1
- Nettoyage de zone 2
- Nettoyage de zone 3
- Une inquiétante disparition
- Il faut arrêter la prolifération!
- Les grandes pondeuses
- Vers l'inconnu
- La source prolifique noire
- L'île desertique
- Droit d'entrée du desert
- Bienvenue!
- Dehors les envahisseurs!
- Une terreur desertique
- Nos anciens soldats tombés
- La malédiction du cristal desertique
- Droit d'entrée féerique
- La trame principale
- La pêche c'est sacré
- Bienvenue chez nous
completedRedoableQuests:
- Les panthères sauvages
- La grande infection
- La pêche c'est sacré
- Dehors les envahisseurs!
- Des orcs à la chaîne
- Les zombifiacs distordus
- Il faut arrêter la prolifération!
- Nos anciens soldats tombés
- Les grandes pondeuses
- Les brasieros enflammés
- Au coeur de la forêt
- Les sorciers déchus
- En manque de nourriture
- Les chevaliers corrompus
- Attaqué par les gobelins
- Nettoyage de zone 1
- Nettoyage de zone 2
- Des esclaves et des gobelins
- Nettoyage de zone 3
- Une terreur desertique
completedQuestTimes:
- 1547298080352
- 1547313220765
- 1547849686593
- 1547847694553
- 1547657641714
- 1547372033074
- 1547669667653
- 1547847931041
- 1547724400881
- 1547372585319
- 1547572355067
- 1547573238034
- 1547551408808
- 1547297780266
- 1547375062182
- 1547663452523
- 1547663842866
- 1547657087083
- 1547664541857
- 1547847800902
amountsCompletedQuests:
- Les panthères sauvages
- La grande infection
- La pêche c'est sacré
- Dehors les envahisseurs!
- Des orcs à la chaîne
- Les zombifiacs distordus
- Il faut arrêter la prolifération!
- Nos anciens soldats tombés
- Les grandes pondeuses
- Les brasieros enflammés
- Au coeur de la forêt
- Les sorciers déchus
- En manque de nourriture
- Les chevaliers corrompus
- Attaqué par les gobelins
- Nettoyage de zone 1
- Nettoyage de zone 2
- Des esclaves et des gobelins
- Nettoyage de zone 3
- Une terreur desertique
amountsCompleted:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
hasJournal: true
lastKnownName: Iscale
```

**Comment by FlyingPikachu** [comment]
I wasn't able to find the cause of this problem, but I've added a stopgap that will add the missing values in memory when the data is loaded. The file won't be altered, but it should stop the errors and let the player complete the quest, at which point the missing values won't matter.

Use this build once available - http://ci.ac3-servers.eu/job/Quests/623/
