### ISSUE TITLE
Errors and not working on Questseditor

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#660]
Server version: 1.8.8 Spigot
Plugin version: 3.6.0-b635

first the Error:

> [07:17:09 ERROR]: Error handling conversation prompt
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.LinkedList
        at me.blackvein.quests.QuestFactory.saveQuest(QuestFactory.java:832) ~[Quests.jar:?]
        at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:711) ~[Quests.jar:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:1011) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:729) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

> 
After some times in the Questeditor with this quest it shows up on try to save the quest.

>  
custom1:
    name: (1) Mach dich für den Kampf bereit!
    npc-giver-id: 42
    ask-message: Besorge Ausrüstung und Liefere diese.
    finish-message: test
    requirements:
      items:
      - name-DIAMOND_SWORD:amount-1
      - name-DIAMOND_SWORD:amount-1
      - name-DIAMOND_CHESTPLATE:amount-1
      - name-DIAMOND_LEGGINGS:amount-1
      - name-DIAMOND_BOOTS:amount-1
      remove-items:
      - false
      - false
      - false
      - false
      - false
      quests:
      - (0) Farmmap verstehen & benutzen! (Tutorial)
      fail-requirement-message: da fehlt dir quest oder di
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-DIAMOND_SWORD:amount-1
          - name-DIAMOND_HELMET:amount-1
          - name-DIAMOND_CHESTPLATE:amount-1
          - name-DIAMOND_LEGGINGS:amount-1
          - name-DIAMOND_LEGGINGS:amount-1
          npc-delivery-ids:
          - 7
          - 7
          - 7
          - 7
          - 7
          delivery-messages:
          - Fertig mein freund

>

**Comment by FlyingPikachu** [comment]
Issue has already been resolved. Use the latest Jenkins build :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FlyingPikachu** [comment]
@kleinesgumi Thanks for your report. Please give this build a try once available - http://ci.ac3-servers.eu/job/Quests/636/
