### ISSUE TITLE
Plugin Quests v3.6.0-b636 generated an exception whilst handling conversation input

### ISSUE THREAD

**Issue by mistek131995** [FlyingPikachu/Quests#665]
Log file: https://drive.google.com/open?id=1sFsJ2ciRd6KQPo07Uw6rsW7CLI8NvrS9

I tried to remove the default quest and got this error. Set Russian language  in config file.

**Plugin:** Quests v3.6.0-b636
**Server:**  [13:52:31 INFO]: This server is running CraftBukkit version git-Spigot-518206a-a
5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by mistek131995** [comment]
In last build...
`
[16:42:07] [Server thread/INFO]: mistek issued server command: /quests editor
[16:42:20] [Server thread/ERROR]: [Quests] Iron Miner inside quests: Requirement for Quest Mob Hunter is not a valid Quest name!
[16:42:20] [Server thread/ERROR]: [Quests] Make sure you aren't using the config section identifier.
[16:42:20] [Server thread/ERROR]: [Quests] Iron Miner inside quests: Requirement for Quest Catch Fish is not a valid Quest name!
[16:42:20] [Server thread/ERROR]: [Quests] Make sure you aren't using the config section identifier.
[16:42:20] [Server thread/INFO]: [Quests] Loaded language en-US. Translations via Crowdin
[16:42:20] [Server thread/WARN]: [Quests] Plugin Quests v3.6.2-b642 generated an exception whilst handling conversation input
java.lang.NullPointerException: null
	at me.blackvein.quests.Quests.loadCustomSections(Quests.java:2016) ~[?:?]
	at me.blackvein.quests.Quests.loadModules(Quests.java:522) ~[?:?]
	at me.blackvein.quests.Quests.reloadQuests(Quests.java:786) ~[?:?]
	at me.blackvein.quests.QuestFactory.deleteQuest(QuestFactory.java:1797) ~[?:?]
	at me.blackvein.quests.QuestFactory.access$1700(QuestFactory.java:60) ~[?:?]
	at me.blackvein.quests.QuestFactory$DeletePrompt.acceptInput(QuestFactory.java:1760) ~[?:?]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:228) ~[Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1203) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnection$2.evaluate(PlayerConnection.java:1490) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.util.Waitable.run(Waitable.java:24) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:908) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

`

**Comment by FlyingPikachu** [comment]
The first few lines of your error are telling you that, although you removed Iron Miner, there are still a few quests left that depends on it. You will need to edit or remove any reference of it from the Mob Hunter and Catch Fish quests.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
