### ISSUE TITLE
Custom Reward

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#672]
Questversion: 3.6.2-b644
MythicMobs addon: 362 version

> 

try to Set Custom rewards and then write MythicMobs Itemreward 
this error comes up: 

> Error handling conversation prompt
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at me.blackvein.quests.prompts.RewardsPrompt$RewardCustomDataListPrompt.getPromptText(RewardsPrompt.java:852) ~[Quests.jar:?]
        at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:1011) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:729) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

> 

and now stuck in the editor, try cancel or anything this error comes up until restart Quests

**Comment by FlyingPikachu** [comment]
Thanks for using Quests. Please try the following build, once available:

http://ci.ac3-servers.eu/job/Quests/646/
