### ISSUE TITLE
Stagetimer Error/Bug

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#677]
Quests version 3.6.2-b646
The problem is after the first timeris done you can make two stages in a row without timer that got skipped and this Errors comes. 

>ordered:
        '1':
          items-to-deliver:
          - name-INK_SACK:amount-1:data-4:enchantment-DURABILITY 1:displayname-§9§lBlauer Kristall:lore-§7Wird hauptsächlich dazu verwendet Items:lore-§7Herzustellen.:lore-:lore-§8[§4§l!§8] §dDroppt von allen Monster Spheren.:lore-§8[§4§l!§8] §cVerwendbar nur in der Farmmap.:meta-type-UNSPECIFIC:enchants-{DURABILITY=1}:ItemFlags-[HIDE_ENCHANTS]
          npc-delivery-ids:
          - 46
          delivery-messages:
          - DELIVERY MESSAGE
          delay: 5
          start-message: 'START MESSAGE'
          complete-message: 'DONE Message'
        '2':
          items-to-deliver:
          - name-INK_SACK:amount-1:data-4:enchantment-DURABILITY 1:displayname-§9§lBlauer Kristall:lore-§7Wird hauptsächlich dazu verwendet Items:lore-§7Herzustellen.:lore-:lore-§8[§4§l!§8] §dDroppt von allen Monster Spheren.:lore-§8[§4§l!§8] §cVerwendbar nur in der Farmmap.:meta-type-UNSPECIFIC:enchants-{DURABILITY=1}:ItemFlags-[HIDE_ENCHANTS]
          npc-delivery-ids:
          - 46
          delivery-messages:
          - DELIVERY MESSAGE
          delay: 5
          start-message: 'START MESSAGE'
          complete-message: 'DONE Message'
        '3':
          items-to-deliver:
          - name-INK_SACK:amount-1:data-4:enchantment-DURABILITY 1:displayname-§9§lBlauer Kristall:lore-§7Wird hauptsächlich dazu verwendet Items:lore-§7Herzustellen.:lore-:lore-§8[§4§l!§8] §dDroppt von allen Monster Spheren.:lore-§8[§4§l!§8] §cVerwendbar nur in der Farmmap.:meta-type-UNSPECIFIC:enchants-{DURABILITY=1}:ItemFlags-[HIDE_ENCHANTS]
          npc-delivery-ids:
          - 46
          delivery-messages:
          - DELIVERY MESSAGE
          delay: 5
          start-message: 'START MESSAGE'
          complete-message: 'DONE Message'

> 

> [Quests] Task #47276 for Quests v3.6.2-b646 generated an exception
java.lang.NullPointerException
        at me.blackvein.quests.timers.StageTimer.run(StageTimer.java:38) ~[Quests.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

>

**Comment by FlyingPikachu** [comment]
Thanks for your report. The issue should be resolved in the following build, once available:
http://ci.ac3-servers.eu/job/Quests/653/
