### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by mistek131995** [FlyingPikachu/Quests#694]
```
[21:18:38 ERROR]: Could not pass event AsyncPlayerChatEvent to Quests v3.6.3-b656
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.chat(PlayerConnection.java:1558) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1496) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_201]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IllegalStateException: Asynchronous command dispatch!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at me.blackvein.quests.Quest.completeQuest(Quest.java:558) ~[?:?]
        at me.blackvein.quests.Quest.nextStage(Quest.java:189) ~[?:?]
        at me.blackvein.quests.Quester.finishObjective(Quester.java:1515) ~[?:?]

        at me.blackvein.quests.Quester.sayPassword(Quester.java:1461) ~[?:?]
        at me.blackvein.quests.listeners.PlayerListener.onPlayerChat(PlayerListener.java:361) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        ... 11 more
```

Quests v3.6.3-b656
This server is running CraftBukkit version git-Spigot-b0f4c22-a2dd0e3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

The error appears when you complete a job with a password and location.

**Comment by FlyingPikachu** [comment]
This was caused by the password objective trying to display the "Quest Complete" title in manner which isn't thread-safe. Please use the following build to resolve the issue:

http://ci.ac3-servers.eu/job/Quests/657/
