### ISSUE TITLE
Save Quest Not Functioning

### ISSUE THREAD

**Issue by mecray** [FlyingPikachu/Quests#7]
Hi.

I have recently downloaded this plugin. When I completely setup everything and type in 13, and then 1, it gives me this error -

```
ERROR Error handling conversation prompt
23.06 17:14:01 [Server] INFO java.lang.NullPointerException: null
23.06 17:14:01 [Server] INFO at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:1036) ~[?:?]
23.06 17:14:01 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
23.06 17:14:01 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
23.06 17:14:01 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1038) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
23.06 17:14:01 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1234) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
23.06 17:14:01 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
23.06 17:14:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:757) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
23.06 17:14:01 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
23.06 17:14:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
23.06 17:14:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
23.06 17:14:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

I have all required dependencies installed. What should I do? This is preventing me from saving any quest.

Thanks
- meCray

**Comment by FlyingPikachu** [comment]
@mecray Which version of Quests are you using? If possible, download the latest version from Spigot and duplicate the error, the post it here.

**Comment by mecray** [comment]
I am currently using the latest version.

Right now I am unable to replicate the issue, but I can describe it. I first create a quest with the quest editor, and after filling out all of the fields I put it in "Save". It says put 1 to save and close, and 2 to cancel. I press one, and it gives me the error above.

**Comment by FlyingPikachu** [comment]
@mecray "Latest" is not sufficient. The line referenced in your error `(QuestFactory.java:1036`) is a blank line in the current build, so chances are you're weren't using 2.8.6.

Since you cannot replicate the issue, and didn't provide a version number, I have little choice but to close this.
