### ISSUE TITLE
/questadmin reload

### ISSUE THREAD

**Issue by Wafffidooe** [FlyingPikachu/Quests#704]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.2-b654
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
[00:13:52] [Server thread/INFO]: Wafffidooe issued server command: /questadmin reload
[00:13:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.6.2-b654
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Material.matchMaterial(Ljava/lang/String;Z)Lorg/bukkit/Material;
	at me.blackvein.quests.util.ItemUtil.processItemStack(ItemUtil.java:135) ~[?:?]
	at me.blackvein.quests.util.ItemUtil.readItemStack(ItemUtil.java:295) ~[?:?]
	at me.blackvein.quests.Event.loadEvent(Event.java:485) ~[?:?]
	at me.blackvein.quests.Quests.loadEvents(Quests.java:2193) ~[?:?]
	at me.blackvein.quests.Quests.reloadQuests(Quests.java:782) ~[?:?]
	at me.blackvein.quests.listeners.CmdExecutor.adminReload(CmdExecutor.java:840) ~[?:?]
	at me.blackvein.quests.listeners.CmdExecutor.questAdminCommandHandler(CmdExecutor.java:262) ~[?:?]
	at me.blackvein.quests.listeners.CmdExecutor.onCommand(CmdExecutor.java:73) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	... 15 more

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by FlyingPikachu** [comment]
Should be resolved in http://ci.ac3-servers.eu/job/Quests/689/
