### ISSUE TITLE
Task #411

### ISSUE THREAD

**Issue by 6594k** [FlyingPikachu/Quests#71]
paperspigot 1.11.2 
quests 2.9.5

(RUN SERVER)[19:07:37 WARN]: [Quests] Task #411 for Quests v2.9.5-b152 generated an exception
java.lang.NullPointerException
        at me.blackvein.quests.Quests.loadEvents(Quests.java:3238) ~[?:?]
        at me.blackvein.quests.Quests$1.run(Quests.java:193) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[spigot.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [spigot.jar:git-Paper-1104]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
>questadmin reload
[19:09:00 WARN]: Unexpected exception while parsing console command "questadmin reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v2.9.5-b152
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Paper-1104]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[spigot.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) ~[spigot.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:638) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:441) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:404) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [spigot.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [spigot.jar:git-Paper-1104]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.Quests.loadEvents(Quests.java:3238) ~[?:?]
        at me.blackvein.quests.Quests.reloadQuests(Quests.java:1917) ~[?:?]
        at me.blackvein.quests.Quests.adminReload(Quests.java:660) ~[?:?]
        at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:615) ~[?:?]
        at me.blackvein.quests.Quests.onCommand(Quests.java:604) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1104]
        ... 8 more

**Comment by LinearBotSystems** [comment]
Your events.yml is either empty or has some wrong formats in it.

**Comment by LinearBotSystems** [comment]
I can't sleep so my suggestion to FlyingPikachu to avoid crashing like this is
`if (eventsFile.length() != 0) {

			ConfigurationSection sec = config.getConfigurationSection("events");
			if (sec == null) {
				getLogger().log(Level.SEVERE, "Failed to load Events possible format errors in it");
			} else {
				for (String s : sec.getKeys(false)) {
					Event event = Event.loadEvent(s, this);
					if (event != null) {
						events.add(event);
					} else {
						getLogger().log(Level.SEVERE, "Failed to load Event \"" + s + "\". Skipping.");
					}
				}
			}
		}`
This should make an empty events.yml valid and should stop crashes in any case but gives a big warning.

**Comment by FlyingPikachu** [comment]
I'm curious as to why events.yml would be empty, but will apply @LinearBotSystems solution shortly.
