### ISSUE TITLE
Exception on questadmin reload

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#714]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.3-b667

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

`/questadmin reload`

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

This paste will expire in 2 weeks: https://pastebin.com/EmdQDST8

**Comment by FlyingPikachu** [comment]
Are you able to share the exception?

**Comment by SXRWahrheit** [comment]
whoops

```
[22:51:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.6.3-b667
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-e8ded36-acbc348]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-e8ded36-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-e8ded36-acbc348]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-e8ded36-acbc348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quest.updateCompass(Quest.java:331) ~[Quests-3.6.3.jar:?]
	at me.blackvein.quests.Quester.checkQuest(Quester.java:2787) ~[Quests-3.6.3.jar:?]
	at me.blackvein.quests.Quests.reloadQuests(Quests.java:804) ~[Quests-3.6.3.jar:?]
	at me.blackvein.quests.listeners.CmdExecutor.adminReload(CmdExecutor.java:840) ~[Quests-3.6.3.jar:?]
	at me.blackvein.quests.listeners.CmdExecutor.questAdminCommandHandler(CmdExecutor.java:262) ~[Quests-3.6.3.jar:?]
	at me.blackvein.quests.listeners.CmdExecutor.onCommand(CmdExecutor.java:73) ~[Quests-3.6.3.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-e8ded36-acbc348]
	... 15 more

```

**Comment by FlyingPikachu** [comment]
@SXRWahrheit Despite the commit description, I'm not 100% sure it will resolve the issue. Please try the following dev build and let me know whether or not it works:
http://ci.ac3-servers.eu/job/Quests/674/
