### ISSUE TITLE
Not allowed to set block break durability to 0 0 while this is the only valid option according to previous conversation.

### ISSUE THREAD

**Issue by OwnAgePau** [FlyingPikachu/Quests#76]
Spigot 1.12
Quests 2.9.5

So in a previous bug I described how I couldn't have my gold ore and coal ore break block to work, now I tried adjusting the durability from 1 1 to 0 0 but it displays "0 null" in the chat and asks me to enter the block durability (again). so I CAN'T set the block durability to be both or even just 1 to 0. Apperently 0 should be the only valid and working solution for these break blocks.
When first trying to edit the break blocks section (with durability set to 1,1) it would not show me the data from the entire block break section, only when I entered 4 (which I remembered being "clear") it shows me the renewed and empty section. It could be that the shown error below has something to do with this instead.

Quest: 
https://pastebin.com/0MTSaaEX

This error also appears:

Error handling conversation prompt
java.lang.ClassCastException: java.lang.Short cannot be cast to java.lang.Integer
at me.blackvein.quests.prompts.CreateStagePrompt$BreakBlockListPrompt.getPromptText(CreateStagePrompt.java:580) ~[?:?]
at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1038) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1234) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:757) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at net.minecraft.server.v1_12_R1.
MinecraftServer.run(MinecraftServer.java:576) [gbinvl_minecraft_spigot_1_12.jar:git-Spigot-ede465d-bb4ae3b]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by LinearBotSystems** [comment]
Oh I had this too I'm not 100% sure normally you can cast short to int the only reason I see maybe because it Short and Integer so they are classes. Maybe this is a new behavior from Java or why did this not pop up before as a problem ? . I did write a fix for this but haven't test it if it solve the problem.
[QuestFactory.zip](https://github.com/FlyingPikachu/Quests/files/1175278/QuestFactory.zip)

It simply create and Integer object with the Short as input if this doesn't solve it then there must be some wrong format problem with the input/save file.

**Comment by LinearBotSystems** [comment]
Okay tested it works

**Comment by FlyingPikachu** [comment]
I also found the issue and have applied a fix - http://ci.ac3-servers.eu/job/Quests/155/

@LinearBotSystems I have no way to compare your code in the way you've presented it. For future contributions, I think we'd both benefit if you'd use the Pull Request system. Thanks!

**Comment by OwnAgePau** [comment]
Even though this is marked as fixed, I still can't set the durability to 0 0 using the built in system. It does now always properly show me the break block section but it still says 0 null when trying to add 0 0.

**Comment by FlyingPikachu** [comment]
@OwnAgePau Do you have a new error? I assume you're using the dev build I linked or newer, in which case the error would have changed slightly.

**Comment by OwnAgePau** [comment]
No error appeared in the console when trying to change that, I have now fixed the quest by editting it myself in the file directly.
