### ISSUE TITLE
show-npc-effects dont work

### ISSUE THREAD

**Issue by SimbaZockt** [FlyingPikachu/Quests#8]
show-npc-effects in the config dont work!
No errors nothing

**Comment by FlyingPikachu** [comment]
How is this supposed to work?

**Comment by Leescar** [comment]
Maybe its referring to npc-effect where an npc is supposed to emit a note block jingle symbol?
As well as other settable particle effects.

Tested with particles set to all and show-npc-effects: true
No effect above npc head.

**Comment by SimbaZockt** [comment]
if a npc have a quest for a player it gives a note about the npcs head.
if the player finished the quest the effect is gone.

**Comment by FlyingPikachu** [comment]
Could I get you to post your server version? You can get this when starting up your server:

"This server is running CraftBukkit version......."

**Comment by SimbaZockt** [comment]
This server is running CraftBukkit version git-Spigot-e497721-96d09e3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Comment by FlyingPikachu** [comment]
Try this dev build: http://ci.ac3-servers.eu/job/Quests/21/

**Comment by SimbaZockt** [comment]
[23:43:46] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.server.v1_8_R1.EnumParticle field net.minecraft.server.v1_8_R1.PacketPlayOutWorldParticles.a to java.lang.String
[23:43:46] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[23:43:46] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[23:43:46] [Server thread/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
[23:43:46] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Unknown Source)
[23:43:46] [Server thread/WARN]: 	at me.blackvein.quests.util.ReflectionUtil.setValue(ReflectionUtil.java:10)
[23:43:46] [Server thread/WARN]: 	at me.blackvein.particles.Eff_1_8_R1.sendToPlayer(Eff_1_8_R1.java:56)
[23:43:46] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.showEffect_1_8_R1(NpcEffectThread.java:123)
[23:43:46] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:67)
[23:43:46] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:43)
[23:43:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[23:43:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[23:43:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694)
[23:43:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[23:43:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[23:43:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[23:43:46] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by FlyingPikachu** [comment]
Okay, try this: http://ci.ac3-servers.eu/job/Quests/22/

**Comment by SimbaZockt** [comment]
11:55:52] [Server thread/INFO]: SimbaZockt issued server command: /questadmin reload
[11:55:52] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.server.v1_8_R1.EnumParticle field net.minecraft.server.v1_8_R1.PacketPlayOutWorldParticles.a to java.lang.String
[11:55:52] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[11:55:52] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[11:55:52] [Server thread/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
[11:55:52] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Unknown Source)
[11:55:52] [Server thread/WARN]: 	at me.blackvein.quests.util.ReflectionUtil.setValue(ReflectionUtil.java:10)
[11:55:52] [Server thread/WARN]: 	at me.blackvein.particles.Eff_1_8_R1.sendToPlayer(Eff_1_8_R1.java:63)
[11:55:52] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.showEffect_1_8_R1(NpcEffectThread.java:124)
[11:55:52] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:67)
[11:55:52] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:43)
[11:55:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[11:55:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[11:55:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694)
[11:55:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[11:55:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[11:55:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[11:55:52] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by FlyingPikachu** [comment]
Alright, up next: http://ci.ac3-servers.eu/job/Quests/23/

**Comment by SimbaZockt** [comment]
Did i need too change something in the config?


[19:43:59] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.server.v1_8_R1.EnumParticle field net.minecraft.server.v1_8_R1.PacketPlayOutWorldParticles.a to java.lang.Integer
[19:43:59] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[19:43:59] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[19:43:59] [Server thread/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
[19:43:59] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Unknown Source)
[19:43:59] [Server thread/WARN]: 	at me.blackvein.quests.util.ReflectionUtil.setValue(ReflectionUtil.java:10)
[19:43:59] [Server thread/WARN]: 	at me.blackvein.particles.Eff_1_8_R1.sendToPlayer(Eff_1_8_R1.java:63)
[19:43:59] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.showEffect_1_8_R1(NpcEffectThread.java:124)
[19:43:59] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:67)
[19:43:59] [Server thread/WARN]: 	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:43)
[19:43:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[19:43:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:43:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694)
[19:43:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[19:43:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[19:43:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[19:43:59] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by FlyingPikachu** [comment]
No, and I'm surprised that didn't work. I've recreated the error on my test server, will hopefully have a fix soon.
