### ISSUE TITLE
Cant set Deliver Item in Quest Stage

### ISSUE THREAD

**Issue by PlayHadde** [FlyingPikachu/Quests#81]
At first i set the Item for the GUI. After this, i try to set the deliver item for the quest.

There ist no matter what i do between the two actions.

When I try to set the item now, an error appeare in the console:

> [23:35:38 ERROR]: Error handling conversation prompt
java.lang.NullPointerException
at me.blackvein.quests.util.ItemUtil.getDisplayString(ItemUtil.java:168) ~[?:?]
at me.blackvein.quests.prompts.CreateStagePrompt$DeliveryListPrompt.getPromptText(CreateStagePrompt.java:2058) ~[?:?]
at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[minecraft_server.jar:git-Spigot-081dfa5-4470462]
at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [minecraft_server.jar:git-Spigot-081dfa5-4470462]
at org.bukkit.craftbukkit.v1_8_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [minecraft_server.jar:git-Spigot-081dfa5-4470462]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1033) [minecraft_server.jar:git-Spigot-081dfa5-4470462]
at net.minecraft.server.v1_8_R1.PlayerConnection$2.evaluate(PlayerConnection.java:964) [minecraft_server.jar:git-Spigot-081dfa5-4470462]
at org.bukkit.craftbukkit.v1_8_R1.util.Waitable.run(Waitable.java:24) [minecraft_server.jar:git-Spigot-081dfa5-4470462]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:700) [minecraft_server.jar:git-Spigot-081dfa5-4470462]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [minecraft_server.jar:git-Spigot-081dfa5-4470462]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [minecraft_server.jar:git-Spigot-081dfa5-4470462]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [minecraft_server.jar:git-Spigot-081dfa5-4470462]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_67]

**Comment by FlyingPikachu** [comment]
I was able to recreate this, but am still investigating the issue.

**Comment by FlyingPikachu** [comment]
Bug #57 may be have been related to this issue and has since been resolved. Please update to at least this dev build and check if it resolves the issue.

http://ci.ac3-servers.eu/job/Quests/81/

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
