### ISSUE TITLE
Quests 2.9.8 not loading

### ISSUE THREAD

**Issue by Ronnie0982** [FlyingPikachu/Quests#87]
The log says it... so i don't know
Version: 2.9.8

[11:53:05 ERROR]: Could not load 'plugins\Quests-2.9.8.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_60]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	... 5 more

**Comment by FlyingPikachu** [comment]
Unfortunately, 2.8.6 will remain broken until the issues with Jenkins are resolved. However, I've re-posted 2.9.7 to the Spigot page, so I urge you to give that a try. Thanks the head's up! :)

**Comment by Ronnie0982** [comment]
Okay Thx :)
