### ISSUE TITLE
Flood error console ...

### ISSUE THREAD

**Issue by Max633** [FlyingPikachu/Quests#93]
Hi

http://pastebin.com/hnQNwb9n

Thank you,

**Comment by FlyingPikachu** [comment]
Please post your quests.yml. Also, do you know which quest causes this error?

**Comment by Max633** [comment]
http://pastebin.com/DELj69ZA

thank you

**Comment by FlyingPikachu** [comment]
Your quests.yml looks good to me. Try this dev build: http://ci.ac3-servers.eu/job/Quests/74/

If that doesn't fix your issue, post the error you get while using the dev build (even if it's similar).

**Comment by Max633** [comment]
Ok thank you, i'll let you know

**Comment by Max633** [comment]
Hi,

Console error flood with dev build 74

http://pastebin.com/9mff8zpg

...

**Comment by Max633** [comment]
When I reset the Data folder all went well ... But from my players lose them made their progression quest. The problem must be there.

**Comment by FlyingPikachu** [comment]
Sorry, I do not understand "But from my players lose them made their progression quest."

Please rephrase? :)

**Comment by Max633** [comment]
If I delete the "Data" folder my players inevitably lose them their progression quests

I'm sorry, I use google translation

**Comment by Max633** [comment]
when a player has two quests, there is an issue

**Comment by FlyingPikachu** [comment]
The issue with two quests is a known issue: https://github.com/FlyingPikachu/Quests/issues/57

At this point, I can only experiment. Next time you receive the error, please upload your /data folder.

**Comment by Max633** [comment]
OK :)

**Comment by Max633** [comment]
Hello, as we said I send you the data folder and error logs about the double quests.

http://cube-of-eternity.com//launcher/dl/data + log.rar

Ty

**Comment by FlyingPikachu** [comment]
Alright, please start running this dev build:

http://ci.ac3-servers.eu/job/Quests/75/

It will provide additional information next time you experience the error. Once you get it, simply post the error (no need to upload data/log this time - thank you for doing so).

**Comment by Max633** [comment]
Ok, no problem

**Comment by Max633** [comment]
HI

[21:41:36] [Server thread/ERROR]: [Quests] Issue grabbing data. Please report these values in Github ticket #93:
[21:41:36] [Server thread/ERROR]: [Quests] quest = Devenir Alchimiste, delivered = 999, amt = 999, npc = null
[21:41:36] [Server thread/WARN]: java.lang.NullPointerException
[21:41:36] [Server thread/WARN]: 	at me.blackvein.quests.Quester.getObjectives(Quester.java:674)
[21:41:36] [Server thread/WARN]: 	at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:415)
[21:41:36] [Server thread/WARN]: 	at me.blackvein.quests.Quester.updateJournal(Quester.java:289)
[21:41:36] [Server thread/WARN]: 	at me.blackvein.quests.Quester$4.put(Quester.java:185)
[21:41:36] [Server thread/WARN]: 	at me.blackvein.quests.Quester$4.put(Quester.java:178)
[21:41:36] [Server thread/WARN]: 	at me.blackvein.quests.Quester.hardDataPut(Quester.java:3451)
[21:41:36] [Server thread/WARN]: 	at me.blackvein.quests.Quester.addEmpties(Quester.java:1713)
[21:41:36] [Server thread/WARN]: 	at me.blackvein.quests.Quester.loadData(Quester.java:2612)
[21:41:36] [Server thread/WARN]: 	at me.blackvein.quests.PlayerListener.onPlayerJoin(PlayerListener.java:845)
[21:41:36] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor618.invoke(Unknown Source)
[21:41:36] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:41:36] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[21:41:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[21:41:36] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:41:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[21:41:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[21:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerList.onPlayerJoin(PlayerList.java:296)
[21:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerList.a(PlayerList.java:156)
[21:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.LoginListener.b(LoginListener.java:144)
[21:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.LoginListener.c(LoginListener.java:54)
[21:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:231)
[21:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.ServerConnection.c(ServerConnection.java:148)
[21:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:811)
[21:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[21:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[21:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[21:41:36] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:744)
[21:41:36] [Server thread/ERROR]: null
java.lang.NullPointerException
	at me.blackvein.quests.Quester.getObjectives(Quester.java:694) ~[quests-2.4.0.jar:?]
	at me.blackvein.quests.Quester.getObjectivesReal(Quester.java:415) ~[quests-2.4.0.jar:?]
	at me.blackvein.quests.Quester.updateJournal(Quester.java:289) ~[quests-2.4.0.jar:?]
	at me.blackvein.quests.Quester$4.put(Quester.java:185) ~[quests-2.4.0.jar:?]
	at me.blackvein.quests.Quester$4.put(Quester.java:178) ~[quests-2.4.0.jar:?]
	at me.blackvein.quests.Quester.hardDataPut(Quester.java:3451) [quests-2.4.0.jar:?]
	at me.blackvein.quests.Quester.addEmpties(Quester.java:1713) [quests-2.4.0.jar:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2612) [quests-2.4.0.jar:?]
	at me.blackvein.quests.PlayerListener.onPlayerJoin(PlayerListener.java:845) [quests-2.4.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor618.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PlayerList.onPlayerJoin(PlayerList.java:296) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PlayerList.a(PlayerList.java:156) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:811) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at java.lang.Thread.run(Thread.java:744) [?:1.7.0_55]

And

[22:38:58] [Server thread/ERROR]: [Quests] Issue grabbing data. Please report these values in Github ticket #93:
[22:38:58] [Server thread/ERROR]: [Quests] quest = Devenir Alchimiste, delivered = 999, amt = 999, npc = null
[22:38:58] [Server thread/WARN]: java.lang.NullPointerException
[22:38:58] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v2.4.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:270) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_55]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_55]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at java.lang.Thread.run(Thread.java:744) [?:1.7.0_55]
Caused by: java.lang.NullPointerException

In flood console

**Comment by Max633** [comment]
upppppppppppppppppppp heeeeeeeeeeeeeeellllllllpppppppppppppppppppp


[11:05:15] [Server thread/WARN]: [Quests] Task #50 for Quests v2.4.0 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
	at me.blackvein.quests.NpcEffectThread.showEffect_1_8_R1(NpcEffectThread.java:245) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.showEffect(NpcEffectThread.java:69) ~[?:?]
	at me.blackvein.quests.NpcEffectThread.run(NpcEffectThread.java:43) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
	... 10 more

thank you ...

**Comment by FlyingPikachu** [comment]
Bug #57 (mentioned earlier) may have been related to this issue and has since been resolved. Please update to at least this dev build and check if it resolves the issue.

http://ci.ac3-servers.eu/job/Quests/81/
